#define w23 "<" gX3
#define w13 "<=" gX3
#define w03 )/a;}q3
#define oZ3 ),gP gE
#define oY3 q0(1))+
#define oX3 *fp_or(
#define oW3 qK exp(
#define oV3 " < "
#define oU3 " " qD3
#define oT3 " <= "
#define oS3 +q0(gO(
#define oR3 -a);}q3
#define oQ3 gZ1 dK1
#define oP3 gZ1 dJ1
#define oO3 dN 1,hI
#define oN3 Sqrneq0
#define oM3 Gt1_abs
#define oL3 Gt0_abs
#define oK3 Ge1_abs
#define oJ3 Ge0_abs
#define oI3 Cmp_sqr
#define oH3 Cmp_neg
#define oG3 Cmp_add
#define oF3 Absneq0
#define oE3 2 dN hS
#define oD3 "-125)"
#define oC3 ,y);}q3
#define oB3 2,-3,3,
#define oA3 Ifmerge
#define o93 Xaddnot
#define o83 Sqr_yxx
#define o73 Sqr_xnx
#define o63 Sqr_nxx
#define o53 Absnzlt
#define o43 Absnzge
#define o33 " +" o13" "
#define o23 o13"  "
#define o13 "   "
#define o03 qO2" "
#define dZ3 o1", "
#define dY3 h42" "
#define dX3 h12" "
#define dW3 "x*0+ "
#define dV3 40000.0
#define dU3 )*wE*x*x
#define dT3 gZ1 0l))
#define dS3 qV qP-g2
#define dR3 q0(0l qQ
#define dQ3 hN1") "
#define dP3 Multodiv
#define dO3 "if" oU2
#define dN3 Nor2plus
#define dM3 Lt_or_ne
#define dL3 Lt_or_le
#define dK3 Lt_or_gt
#define dJ3 Lt_or_ge
#define dI3 Lt_or_eq
#define dH3 Le_or_ne
#define dG3 Le_or_eq
#define dF3 L_notnot
#define dE3 L_mulneg
#define dD3 L_mulabs
#define dC3 Ifmerge2
#define dB3 Gt_or_ne
#define dA3 Gt_or_le
#define d93 Gt_or_ge
#define d83 Gt_or_eq
#define d73 Ge_or_ne
#define d63 Ge_or_le
#define d53 Ge_or_eq
#define d43 "y,x,y)"
#define d33 g11" "
#define d23 wO"4) "
#define d13 Xxsqrdup
#define d03 Sqr_yxnx
#define hZ3 Sqr_ynxx
#define hY3 "abs(x)"
#define hX3 (x mP
#define hW3 aG1"1 > "
#define hV3 qR2"1 < "
#define hU3 aF1"0 > "
#define hT3 qQ2"0 < "
#define hS3 "!x * !y"
#define hR3 hC2" !!y"
#define hQ3 "0.0625)"
#define hP3 "!x & !y"
#define hO3 Nand2plus
#define hN3 "!x | !y"
#define hM3 a3" | "
#define hL3 Lt_and_ne
#define hK3 Lt_and_le
#define hJ3 Lt_and_gt
#define hI3 Lt_and_ge
#define hH3 Lt_and_eq
#define hG3 Le_and_ne
#define hF3 Le_and_eq
#define hE3 Ifmerge2b
#define hD3 Gt_and_ne
#define hC3 Gt_and_le
#define hB3 Gt_and_ge
#define hA3 Gt_and_eq
#define h93 Ge_and_ne
#define h83 Ge_and_le
#define h73 Ge_and_eq
#define h63 Notnotnot
#define h53 Dupminmax
#define h43 w61"1 >= "
#define h33 aE1"1 <= "
#define h23 w41"0 >= "
#define h13 aD1"0 <= "
#define h03 a1 o13
#define gZ3 " != "
#define gY3 dW o13
#define gX3 " " hX
#define gW3 Cmp_mulpos
#define gV3 Cmp_mulneg
#define gU3 wE1 o22" "
#define gT3 Xaddnotnot
#define gS3 Notnotnot2
#define gR3 Dupxmuladd
#define gQ3 Dupminmax3
#define gP3 Dupminmax2
#define gO3 Dupaddmul7
#define gN3 "abs" hF1
#define gM3 "abs" h71
#define gL3 o42 o13" "
#define gK3 "y,y,x)"
#define gJ3 Cmp_sqr_neg
#define gI3 "floor" qK2
#define gH3 Mixedminmax
#define gG3 Mergemulabs
#define gF3 Addconstmul
#define gE3 "acos" hF1
#define gD3 "ceil" qL2
#define gC3 "-0.015625)"
#define gB3 If_join_mul2
#define gA3 If_join_add2
#define g93 Cmpzz_minmax
#define g83 Cmpne_minmax
#define g73 Cmplt_minmax
#define g63 Cmple_minmax
#define g53 Cmpgt_minmax
#define g43 Cmpge_minmax
#define g33 "y," h22
#define g23 Cmpeq_minmax
#define g13 Addnegmulpos
#define g03 Addnegmulneg
#define qZ3 Absnotnotnot
#define qY3 Cmpzz_add_imm
#define qX3 Cmpne_add_imm
#define qW3 Cmplt_add_imm
#define qV3 Cmple_add_imm
#define qU3 Cmpgt_add_imm
#define qT3 Cmpge_add_imm
#define qS3 Cmpeq_add_imm
#define qR3 "sin(x))"},
#define qQ3 "25" gO2
#define qP3 h72 aM2"  "
#define qO3 If_extract_mul
#define qN3 If_extract_min
#define qM3 If_extract_add
#define qL3 If_extract_abs
#define qK3 Addmulconstmul
#define qJ3 gM3" "
#define qI3 "acos" w7 o7
#define qH3 If_extract_mul2
#define qG3 If_extract_mul1
#define qF3 If_extract_add2
#define qE3 If_extract_add1
#define qD3 "(5.0625 "
#define qC3 If_extract_or2_l
#define qB3 If_extract_or1_l
#define qA3 Cmpzz_minmax_rev
#define q93 Cmpzz_addadd_imm
#define q83 Cmpzz_add_reduce
#define q73 Cmpne_minmax_rev
#define q63 Cmpne_addadd_imm
#define q53 Cmpne_add_reduce
#define q43 Cmplt_minmax_rev
#define q33 Cmplt_addadd_imm
#define q23 Cmplt_add_reduce
#define q13 Cmple_minmax_rev
#define q03 Cmple_addadd_imm
#define mZ2 Cmple_add_reduce
#define mY2 Cmpgt_minmax_rev
#define mX2 Cmpgt_addadd_imm
#define mW2 Cmpgt_add_reduce
#define mV2 Cmpge_minmax_rev
#define mU2 Cmpge_addadd_imm
#define mT2 Cmpge_add_reduce
#define mS2 "y,y," aN1
#define mR2 Cmpeq_minmax_rev
#define mQ2 Cmpeq_addadd_imm
#define mP2 Cmpeq_add_reduce
#define mO2 If_extract_or2_nl
#define mN2 If_extract_or1_nl
#define mM2 If_extract_and2_l
#define mL2 If_extract_and1_l
#define mK2 Cmpzz_mul_imm_pos
#define mJ2 Cmpzz_mul_imm_neg
#define mI2 Cmpne_mul_imm_pos
#define mH2 Cmpne_mul_imm_neg
#define mG2 Cmplt_mul_imm_pos
#define mF2 Cmplt_mul_imm_neg
#define mE2 Cmple_mul_imm_pos
#define mD2 Cmple_mul_imm_neg
#define mC2 Cmpgt_mul_imm_pos
#define mB2 Cmpgt_mul_imm_neg
#define mA2 Cmpge_mul_imm_pos
#define m92 Cmpge_mul_imm_neg
#define m82 Cmpeq_mul_imm_pos
#define m72 Cmpeq_mul_imm_neg
#define m62 d4"5.0625 "
#define m52 "-125" gO2
#define m42 If_extract_and2_nl
#define m32 If_extract_and1_nl
#define m22 "y, 0,1" gO2
#define m12 Cmpzz_mulmul_imm_pos
#define m02 Cmpzz_mulmul_imm_neg
#define aZ2 Cmpne_mulmul_imm_pos
#define aY2 Cmpne_mulmul_imm_neg
#define aX2 Cmplt_mulmul_imm_pos
#define aW2 Cmplt_mulmul_imm_neg
#define aV2 Cmple_mulmul_imm_pos
#define aU2 Cmple_mulmul_imm_neg
#define aT2 Cmpgt_mulmul_imm_pos
#define aS2 Cmpgt_mulmul_imm_neg
#define aR2 Cmpge_mulmul_imm_pos
#define aQ2 Cmpge_mulmul_imm_neg
#define aP2 Cmpeq_mulmul_imm_pos
#define aO2 Cmpeq_mulmul_imm_neg
#define aN2 "0.0625" gO2
#define aM2 o13 o13
#define aL2 cpp_03unit_constants::
#define aK2 "-0.015625" gO2
#define aJ2 cpp_02unit_functions::
#define aI2 hA LNG_ONLY
#define aH2 cpp_99misc::
#define aG2 cpp_50regressions::
#define aF2 cpp_01unit_operators::
#define aE2 cpp_10optimizer_bytecode::
#define aD2 cpp_11optimizer_constaddmul::
#define aC2 DBL_ONLY
#define aB2 cpp_20optimizer_optimizations::
#define aA2 q0(0 mY
#define a92 "a" gK2
#define a82 qP gM2
#define a72 (qK qP
#define a62 {1 oG
#define a52 {1,0,dD
#define a42 fp_pow(
#define a32 {2,hE1
#define a22 fp_less(
#define a12 -400 mR
#define a02 o13" 4"
#define wZ2 " " qB1
#define wY2 fp_and(
#define wX2 (fp_acos(
#define wW2 q0(dJ))
#define wV2 -6,6,1 qL
#define wU2 {1,-10,10,
#define wT2 {2,N(.1),
#define wS2 (qK tanf
#define wR2 fp_ceil(
#define wQ2 "a",qE
#define wP2 *q0(0)+q0(
#define wO2 (aD y),qK1
#define wN2 qA mV1
#define wM2 "<4)" aV
#define wL2 "*(" w0
#define wK2 N(0.5,0.0),
#define wJ2 {1,-1000,1000,
#define wI2 TestType<q0>
#define wH2 {using namespace FUNCTIONPARSERTYPES;q0
#define wG2 4.0l hU
#define wF2 "(" h02
#define wE2 "x",oK
#define wD2 "(1,0,1"
#define wC2 (1.1f
#define wB2 4.0f hU
#define wA2 q42 x*x
#define w92 "(" dQ1
#define w82 "(" w5
#define w72 "(" aZ1
#define w62 aT1/gE+
#define w52 (qH oL
#define w42 fp_max(
#define w32 aD x-gF
#define w22 *q0 dV2+
#define w12 *wW1 wT1
#define w02 ,w42
#define oZ2 ,fp_min(
#define oY2 0l);}q3
#define oX2 wH h0(x
#define oW2 wH gZ x
#define oV2 ")" gJ2
#define oU2 "(x" dU
#define oT2 1.1)h81
#define oS2 "y" gO2
#define oR2 "abs(a"
#define oQ2 ")/a"},
#define oP2 ")*0"},
#define oO2 "*" hT2
#define oN2 ")*" gV2
#define oM2 ")*a"},
#define oL2 wQ1" +"
#define oK2 o13" 2"
#define oJ2 N(.5)h8
#define oI2 "5" o42
#define oH2 *wE mU*x
#define oG2 (qK x*
#define oF2 qA,oZ
#define oE2 N(.2)h8
#define oD2 "expex"
#define oC2 "p" hF1
#define oB2 "acosh"
#define oA2 (qH q0
#define o92 q0(1.1l))+
#define o82 q0(5l)
#define o72 ")" mS1
#define o62 mflit0_25
#define o52 *-q0 h6
#define o42 ") +"
#define o32 "*z" o42
#define o22 "<=y &"
#define o12 mB" | "
#define o02 mB" & "
#define dZ2 g01 hD1
#define dY2 o6")"
#define dX2 "x))"},
#define dW2 -x),wG
#define dV2 (6l)/gE
#define dU2 hQ gE)
#define dT2 hQ x),
#define dS2 hQ hQ1
#define dR2 oC gE)
#define dQ2 oB gE)
#define dP2 "(" a0
#define dO2 ")+(x"
#define dN2 +q0(gH(
#define dM2 +q0(gW(
#define dL2 +q0 h6
#define dK2 (qK aD x)+
#define dJ2 "exp("
#define dI2 dH2"/"
#define dH2 qA g5
#define dG2 gZ3
#define dF2 " >= "
#define dE2 "m_deg",
#define dD2 mflit2_5
#define dC2 mflit7_1
#define dB2 d2r(wZ
#define dA2 5),q0(4)
#define d92 qK oQ1
#define d82 hA qA oJ
#define d72 logf(x
#define d62 true q4
#define d52 q0(3l))
#define d42 q0(2.0l)
#define d32 0.0l))+
#define d22 aS1;}q3
#define d12 fp_not(z
#define d02 mV);}q3
#define hZ2 fp_cosh(
#define hY2 qK-x;}q3
#define hX2 qH x+oV1
#define hW2 " " dC1
#define hV2 o1 dE" "
#define hU2 "a,b",oK
#define hT2 "atan2"
#define hS2 hN1"))"
#define hR2 gC1")"
#define hQ2 gC1"))"
#define hP2 "abs(b"
#define hO2 ")" wI1
#define hN2 oA"-5)"
#define hM2 oA"5)"
#define hL2 wL"  32"
#define hK2 wL d21
#define hJ2 N(-6.0,0.0),wS
#define hI2 wL d31
#define hH2 q91"))*"
#define hG2 N(.15)h8
#define hF2 "x+-x+-"
#define hE2 N(.1)h8
#define hD2 "7/2" o42
#define hC2 "!!x *"
#define hB2 "180/pi"
#define hA2 10,10,h7
#define h92 mG1 1,hI
#define h82 ",-" w01
#define h72 "," w01
#define h62 "*" g11
#define h52 " " qX1
#define h42 "x" hA1
#define h32 {1,q2
#define h22 "x,y" gO2
#define h12 "x",o1
#define h02 "1,4,0"
#define gZ2 "x,y,z",
#define gY2 fp_exp2(
#define gX2 fp_cos(
#define gW2 gX2 y
#define gV2 "5"},
#define gU2 "hm_deg",
#define gT2 ",y" gO2{
#define gS2 (qH gG1
#define gR2 ")" mO"+"
#define gQ2 qR dE1
#define gP2 qA dF1
#define gO2 ")"},
#define gN2 gK;}q0
#define gM2 gY;}q0
#define gL2 gJ;}q0
#define gK2 "sinh"
#define gJ2 ",if("
#define gI2 fp_exp(-x)
#define gH2 fp_exp(x)
#define gG2 mflit1_5*
#define gF2 (oY3
#define gE2 q0(2)+q0(
#define gD2 atan2l(
#define gC2 sqrtl(x*x
#define gB2 atan2f(
#define gA2 "^1506"},
#define g92 +x+x+x+x
#define g82 +aD x+gF*
#define g72 (qH a6*y,
#define g62 +a22
#define g52 (qH x>=oV1
#define g42 0x0010l)*
#define g32 fp_nequal
#define g22 (hE(o82
#define g12 qK a42
#define g02 o82*
#define qZ2 fp_tan(
#define qY2 qP-hZ))
#define qX2 gC),-wG
#define qW2 )wV1 dX,y),
#define qV2 oE-hR))
#define qU2 gB-gE
#define qT2 "(x*" q12
#define qS2 "(x) +"
#define qR2 " > 1" o9
#define qQ2 " > 0" o9
#define qP2 ")+x+("
#define qO2 "xp" wL
#define qN2 "(log(x+"
#define qM2 o13"if(x"
#define qL2 "(x)" g71
#define qK2 "(x)" o31
#define qJ2 -3,3,1,q7
#define qI2 "(x^2" gO2
#define qH2 "pow(x"
#define qG2 qA",y,z",
#define qF2 "x!=y" o42
#define qE2 a3" & "
#define qD2 4 dN 1,q7
#define qC2 " > 6" gO2
#define qB2 qK fp_not(
#define qA2 ") > " g01 aC
#define q92 ") <= " g01 aG
#define q82 "*(" wU
#define q72 "*(" aS
#define q62 ") < " g01 aE
#define q52 " = 6" gO2
#define q42 sqrtf(
#define q32 =vars[1]
#define q22 fp_sqrt(
#define q12 "5" gO2
#define q02 "cmp_ex"
#define mZ1 ")/log("
#define mY1 "(1.0"
#define mX1 {1 dN hS
#define mW1 "pi/180"
#define mV1 ",y,z",oZ
#define mU1 "x" mV1
#define mT1 {2,3,5,hS
#define mS1 " + (x*"
#define mR1 ,N(0.25)
#define mQ1 1 mR1,
#define mP1 ,0,1,1,q7
#define mO1 {3 mP1
#define mN1 "x" dH
#define mM1 gA1" | "
#define mL1 gA1" & "
#define mK1 qZ1"*y)"
#define mJ1 qY1"*y)"
#define mI1 1,-5,5,1
#define mH1 N(2.0,0.0)
#define mG1 ,-2,2,
#define mF1 2 mG1 1,qM
#define mE1 ];return
#define mD1 qZ2 y)+
#define mC1 q0(10l)
#define mB1 y),w8,y mY
#define mA1 ,"abs("
#define m91 a42 x*z+q0(17l),
#define m81 a42 fp_exp(m6
#define m71 w42 q0(
#define m61 fp_min(q0(
#define m51 +fp_min(x,
#define m41 ,q0(25l mY
#define m31 wH dN2 x
#define m21 (oY 1l);}q3
#define m11 wH dM2 x
#define m01 wH oS3 x
#define aZ1 "0.7" gG
#define aY1 qK r2d(
#define aX1 ,dZ3"y"
#define aW1 qH q0(hF(
#define aV1 dA x:y)+q0(
#define aU1 dA y:m1
#define aT1 q0(7l)
#define aS1 q0(0l)
#define aR1 (qK fp_exp(
#define aQ1 qT aS1,
#define aP1 qK log(1.1)
#define aO1 qX aS1,
#define aN1 "x)"},
#define aM1 gW2*q0(1.5l))
#define aL1 q0(1l)
#define aK1 (qK aL1/
#define aJ1 mY dF 0l),
#define aI1 N(4.0,0.0)
#define aH1 "log(x)"},
#define aG1 " < 1" g81
#define aF1 " < 0" g81
#define aE1 " >= 1" o9
#define aD1 " >= 0" o9
#define aC1 ")" oS1
#define aB1 "(x*z+17)"
#define aA1 "sub(sub("
#define a91 10,10,1,hI
#define a81 " >= 6" wI
#define a71 " > 6)" aC
#define a61 " < 6)"
#define a51 " <= 6" gO2
#define a41 " >= 6" gO2
#define a31 wO"-4)"
#define a21 mflit0_5
#define a11 ,qG"/sin"
#define a01 q0(0.5l)
#define wZ1 ")" d7 gL
#define wY1 (qH wY2 x
#define wX1 userDefFuncSqr<q0>((
#define wW1 q0(2l)
#define wV1 *wY2
#define wU1 fp_atan2(
#define wT1 /d52+
#define wS1 fp_or(q0(
#define wR1 aL1))
#define wQ1 "sin(x)"
#define wP1 {3 dN hS
#define wO1 w02 x w02
#define wN1 h2"x)"
#define wM1 "(-" aN1
#define wL1 ">-4)" mD
#define wK1 "<-4)" aV
#define wJ1 "=-4)" aU
#define wI1 " " wH1
#define wH1 "+ 32"
#define wG1 "=-2" o9
#define wF1 "(x>4" gO2
#define wE1 "*(x"
#define wD1 2 dN 1 qL
#define wC1 ))+mflit1_2*
#define wB1 ))+mflit1_1*
#define wA1 q0(5 mY 1)/
#define w91 mflit0_7 hU
#define w81 q22 q0(
#define w71 " cos(x)"},
#define w61 " <= 1" g81
#define w51 ,"(sin(x)"
#define w41 " <= 0" g81
#define w31 ",max(x,ma"
#define w21 o13"10*" o1
#define w11 qA q8"/pow"
#define w01 "x)) +"
#define oZ1 " <= 6)" aG
#define oY1 "dupminmax"
#define oX1 (oL,q0(4l)qQ
#define oW1 dG2 g01 d7
#define oV1 y;}q3
#define oU1 qK g32(
#define oT1 (qK a22
#define oS1 "^(1/"
#define oR1 q0(fp_abs(x)
#define oQ1 r2d(q0::
#define oP1 gW2)+
#define oO1 N(1e-6)mR dP
#define oN1 "(acos(x)"
#define oM1 (qK logf wC2
#define oL1 "(abs(x)"
#define oK1 d2r(x)mP
#define oJ1 1 dN N(0.01)
#define oI1 =vars[0],&
#define oH1 fp_or(y,z)
#define oG1 x*-q0(dZ+q0(
#define oF1 ),hQ x+q0(6l))
#define oE1 q0(0.5l qQ
#define oD1 wY2 q0(
#define oC1 d2r(x qQ
#define oB1 )-fp_int(
#define oA1 {1 dN 1,q7
#define o91 h3")"
#define o81 oS"pow"
#define o71 "<=-4)" aW
#define o61 "*((-x)"
#define o51 ">4)" mD
#define o41 "=4)" aU
#define o31 ",ceil(x))+"
#define o21 g11 dU"))"},
#define o11 "cmpeq_"
#define o01 gR"cmpne_"
#define dZ1 gR"cmplt_"
#define dY1 gR"cmpge_"
#define dX1 "cbrt(x^6"
#define dW1 ")), int("
#define dV1 gZ3"6)"
#define dU1 wO"4*y)"
#define dT1 q5"/"
#define dS1 40,40,3,qM
#define dR1 fp_lessOrEq(
#define dQ1 "y" o42" x/"
#define dP1 qK q0(hF(
#define dO1 fp_abs(a)
#define dN1 ,-q0(16l)
#define dM1 "sin(" a0
#define dL1 4000,N(0.1)dP
#define dK1 1l))qT aL1,
#define dJ1 1l))qX aL1,
#define dI1 1l mY dF 1l),
#define dH1 dN 2 q6
#define dG1 3,3,N(0.41)qL
#define dF1 ",y",oZ
#define dE1 "if_ex"
#define dD1 wY2 y,z)
#define dC1 "+ " hH1"*"
#define dB1 {2,q2
#define dA1 +o82;}q3
#define d91 "!=4" gO2
#define d81 " " gL",2)"
#define d71 " " gL",3)"
#define d61 "x" dF1
#define d51 oB3 2,q7
#define d41 2,-4,4,1,q7
#define d31 o13" 8"
#define d21 o13" 16"
#define d11 "(2))"},
#define d01 oO"(" hG1
#define hZ1 oO"(x)"
#define hY1 "(x" gZ3"y" gO2
#define hX1 "(x = y" gO2
#define hW1 aD x)+mflit1_2
#define hV1 hE((aL1/mL)
#define hU1 oD qN-hR))
#define hT1 -q0(2l qQ
#define hS1 {1,-36,36,1 qL
#define hR1 wU2 1 qL
#define hQ1 x),-gE
#define hP1 gR"cmple_"
#define hO1 gR"cmpgt_"
#define hN1 "1,1,1"
#define hM1 "1.1^x*4.1" gO2
#define hL1 "<=4)" aW
#define hK1 "!=-2" gO2
#define hJ1 wL a02
#define hI1 wL oK2
#define hH1 "sin(x+pi"
#define hG1 "abs(x))"
#define hF1 "(x))"},
#define hE1 -3,3,2 qL
#define hD1 g1"0010 *"
#define hC1 wO"-4*y)"
#define hB1 " & (y+2" gO2
#define hA1 "_rev",o1
#define h91 wW1 qQ
#define h81 +x;}q3
#define h71 w7"*(abs(x)"
#define h61 " + sin(x-pi*"
#define h51 ,"((-5.1)*x*y)"
#define h41 {1,-4,4,1 qL
#define h31 oS"powx"
#define h21 " " gL",-2)"
#define h11 " " gL",-3)"
#define h01 q0(5l mY 1l)/
#define gZ1 x),q0(
#define gY1 dA y:x)+q0(
#define gX1 (x mS y,q0(6l mY
#define gW1 (qK dR1
#define gV1 fp_not(-fp_not(
#define gU1 "*(" aR
#define gT1 {1,0,4,N(0.1)qL
#define gS1 d2r wC2)hU
#define gR1 fp_notNot(x
#define gQ1 fp_abs(dT3
#define gP1 fp_abs(x qQ
#define gO1 g0 o3"+y+z"
#define gN1 "x" q8"/"
#define gM1 },{2,-4,4,N(0.05)
#define gL1 true qI
#define gK1 ,q0(25l qQ
#define gJ1 fp_int(q0(
#define gI1 "x" g5"/"
#define gH1 "x" qW1
#define gG1 fp_equal(x
#define gF1 (qK fp_equal
#define gE1 5l),d52+x
#define gD1 ")) " aY"if("
#define gC1 "1,0,0"
#define gB1 {2,-460,100,8,qM
#define gA1 ,"(x > y)"
#define g91 {1 mP1
#define g81 ") " aY
#define g71 ",floor(x))+"
#define g61 ",y" q8"/pow"
#define g51 "(x <= y)"
#define g41 " + cos(x-pi*"
#define g31 fp_abs(x)>=a21
#define g21 1,N(-5.0,0.0),N(5.0,0.0),mH1,q7
#define g11 " if(x"
#define g01 "(y+6))"
#define qZ1 " " wO"4"
#define qY1 " " wO"-4"
#define qX1 o6"+y)"
#define qW1 ",y",g7
#define qV1 hC-1,1,N(0.01)
#define qU1 log(x+sqrt(x*x
#define qT1 " +" oK2"*(if("
#define qS1 "pow(-4,y))"
#define qR1 (aD x)+gW2))*
#define qQ1 10,10,N(0.8)qL
#define qP1 -6,6,N(0.5),qM
#define qO1 "*(5+" o1
#define qN1 3 dN 1,q7
#define qM1 gW2*mflit1_5)
#define qL1 d2r(1.1l)hU
#define qK1 gW2)):
#define qJ1 gH2,
#define qI1 hM x+y+x+x-z h81
#define qH1 qK q0(0x0001)*a22
#define qG1 ,"((1/" o13"abs(b))*"
#define qF1 "*(sinh(x)"
#define qE1 {1,N(0.5)o8
#define qD1 "*(atan(x)"
#define qC1 "(x*if(1,-1,0))"},
#define qB1 "(pow(2,x)"
#define qA1 a22 y,q0(1l
#define q91 "(sin(x)+cos(y"
#define q81 o42" cos(x+pi*"
#define q71 fp_not(x)*fp_not(y)
#define q61 -3,3,N(0.1)qL
#define q51 q0(4l qQ
#define q41 fp_tanh(x),gE
#define q31 x*gZ1 16l))
#define q21 fp_asin(x),gE
#define q11 fp_acos(x),gE
#define q01 gR"cmpzz_pow"
#define mZ dA x:y);}q3
#define mY ))+q0(
#define mX qK fp_greater(
#define mW "pow(1.5,x))"
#define mV *q0(5l
#define mU *x*x*x*x
#define mT x*x,-q0(125l qQ
#define mS +q0(4l)+
#define mR ,400,N(0.1)
#define mQ )*(o82+(
#define mP );}q0
#define mO o23
#define mN +q0(0x0020)*fp_equal(
#define mM ,aS1)gM x:-x mY
#define mL fp_abs(b)
#define mK {2,qD
#define mJ qK logl(
#define mI gX2 x
#define mH {1,-15,15,2 q6
#define mG {1,-3 o8
#define mF log(1.1+sqrt(1.1*
#define mE ">=4" hO2
#define mD " +" wV
#define mC dN N(0.5)qL
#define mB "(x >= y)"
#define mA +q0(0x0010)*g32(
#define m9 qN 1.1l),x)*q0(4.1l qQ
#define m8 +q0(0x0008)*fp_greaterOrEq(
#define m7 +q0(0x0004)*fp_greater(
#define m6 q0(1.0l)
#define m5 (1.1l hU
#define m4 40000,40000,5
#define m3 *x*x,-q0(125l))
#define m2 a22 x
#define m1 x);}q3
#define m0 q0(4l)*d5
#define aZ /d52)
#define aY "+  8*("
#define aX ">=-2" o42"  32"
#define aW " +" o13"8"
#define aV " +" o13"4"
#define aU " +" o13"2"
#define aT "<-2" o42 a02
#define aS "exp2(x)"
#define aR "exp(x)"
#define aQ "*((1-x+x+5)"
#define aP "x,y,z" q8"/"
#define aO "(1.1" gG qL
#define aN +q0(0x0002)*dR1
#define aM fp_or(fp_not(x),fp_not(y
#define aL (fp_truth(
#define aK ,qG"/"
#define aJ qA",y,z" q8"/"
#define aI qA",y" q8"/"
#define aH N(-1.25),N(1.25)mR1
#define aG g1"0004 *"
#define aF ,aS1)gM-x:x mY
#define aE g1"0002 *"
#define aD fp_sin(
#define aC g1"0008 * "
#define aB wY2 fp_not(x),fp_not(y
#define aA gR1)*fp_notNot(y)
#define a9 ">-2" o42 d21
#define a8 "<=-2" o42 d31
#define a7 qS1},
#define a6 a42(q0(-5.1l))*x
#define a5 qH a42(mflitm5_1)*x*y,
#define a4 N(-7.25),N(7.25),N(0.5),qM
#define a3 ,"(x < y)"
#define a2 LNG_ONLY(0)q5"/x"
#define a1 "^6.1)) +"
#define a0 "0.75)) +"
#define wZ mflit1_1)hU
#define wY A_very_long_variable_name_1
#define wX N(-1.0,0.0)qJ N(1.0,0.0),q7
#define wW "*((x*x)"
#define wV o13"16"
#define wU "log2(x)"
#define wT mW},
#define wS N(6.0,0.0),wK2 qM
#define wR {1 dN N(0.25)qL
#define wQ qA qW1
#define wP 2 mG1 1,q7
#define wO "((x*"
#define wN qP-gE,q0(0.0625l))
#define wM qK fp_greaterOrEq(
#define wL "(2)) +"
#define wK N(-.1),N(.1),N(0.01)qL
#define wJ qA,"03unit_constants/"
#define wI ")" hD1
#define wH (4l),y+q0(6l))
#define wG q0(4l))
#define wF ,q0(1)/q0(
#define wE a42 x*x
#define wD +q0(4l)*a22
#define wC 2,N(-3.0,0.0),N(3.0,0.0)qJ q7
#define wB {3,N(0.0,0.0)qJ N(1.0,0.0),q7
#define wA "*(log2(" hG1
#define w9 ,aL1/q0(
#define w8 g32(x
#define w7 "(x))" o33"4"
#define w6 LNG_ONLY(0)q5"/pow"
#define w5 "1.1)+x"},
#define w4 const q0*vars){const q0&
#define w3 gY2 x),-q0(4l
#define w2 "sin(x))" o33"4*(sin(x)"
#define w1 h2"(x/3))"
#define w0 "log10(x)"
#define oZ "99misc/"
#define oY qH x*aS1+y*aS1+q0(
#define oX qN 2l),x),qN-4l),y))
#define oW qJ1 fp_exp(gE)
#define oV qH m2,wG gM
#define oU "(1.061^(x/3)))"
#define oT "((-1.061)^x))"
#define oS qZ"cmp_"
#define oR qK qW
#define oQ hA wJ
#define oP "*(tanh(x)"
#define oO "*(log"
#define oN "*(a" wQ1
#define oM 5.0625l),qN 1.5l),x))
#define oL fp_greater(x
#define oK "50regressions/"
#define oJ ",y","02unit_functions"
#define oI qP-gE,q0(0.0625l qQ
#define oH "1.1" gG,d62
#define oG ,0,1,1 qL
#define oF fp_sinh(x),fp_sinh(
#define oE gC/d52,qN
#define oD qN-gC),
#define oC gY2 x),gY2
#define oB fp_atan(x),fp_atan(
#define oA "*((x/2*x*"
#define o9 o42 oK2"*("
#define o8 ,3,N(0.5)qL
#define o7 "*(acos(x)"
#define o6 "((x+4"
#define o5 ),q0(1l mY 2l)*dR1 aL1,
#define o4 N(-2.0,0.0),mH1,wK2 q7
#define o3 "+y+z+y+z+y+z"
#define o2 x dO g92 g3 g3+y+z)
#define o1 "if(x"
#define o0 fp_truth(x)gM
#define dZ 4l)*y,q0(6l))
#define dY (gW2+aL1),aD y+aL1 qQ
#define dX dR1 x
#define dW "(x^-6.1)) +"
#define dV gZ1 0l mY 2l)*dR1 aS1,
#define dU "<4, cos(y),sin(y+1"
#define dT ,"0x0001 *"
#define dS "((((x*5/2)+x*x-2))"
#define dR 2,N(-4.0,0.0),aI1 qJ q7
#define dQ {2 mP1
#define dP ,false qI
#define dO g92+x+x
#define dN ,-1,1,
#define dM 1 dN 1 qL
#define dL N(-7.25,0.0),N(7.25,0.0),wK2 qM
#define dK qN 2l),x),qN-4l),y qQ
#define dJ 1l)-x+x+o82),q0(4l
#define dI "*(log10(" hG1
#define dH ",y,z" q8"/" dE1
#define dG 5.0625l),qN 1.5l),x qQ
#define dF 8l)*fp_greaterOrEq(q0(
#define dE "<4, sin(y),cos(y+1))"
#define dD 1,1,false,aL2
#define dC {1,-5,5,2,q7
#define dB {1,wX
#define dA ,y)!=aS1)?
#define d9 /wW1*x*-o82),q0(4l
#define d8 /wW1*x mV)),q0(4l
#define d7 " +  0x0020 * "
#define d6 qP-d52,-q0(0.015625l
#define d5 y,q0(6l qQ
#define d4 "pow_imm_pospos_base","("
#define d3 "pow_imm_pospos",gL",2)"
#define d2 "pow_imm_posneg",gL",3)"
#define d1 fp_greaterOrEq(x
#define d0 g2 qP q0(6.1l)))
#define hZ g2 qP-q0(6.1l)
#define hY "pow_imm_negpos",gL",-2)"
#define hX g01},
#define hW 1,-6,6,1,q7
#define hV "pow_imm_negneg",gL",-3)"
#define hU )+x;}q0
#define hT 2,N(-3.0,0.0),N(3.0,0.0),mH1,q7
#define hS N(0.5),q7
#define hR 1.061l),x
#define hQ fp_log(
#define hP LNG_ONLY(0)q5"/sin"
#define hO fp_tanh(x),fp_tanh(q0(0.75l)
#define hN ,N(-1.0,0.0)qJ wK2 q7
#define hM (qC,&y q32,&z=vars[2 mE1
#define hL fp_asin(x),fp_asin(q0(0.75l)
#define hK fp_acos(x),fp_acos(q0(0.75l)
#define hJ {mQ1 3 mR1 qL
#define hI false,aG2
#define hH "powpow_imm_base",qB1
#define hG ,&x=vars[2],&y=vars[3 mE1(o0 aL y)gM
#define hF 0x0001l)*fp_less
#define hE const q9
#define hD "a,b",qE
#define hC "(x)"},{1,
#define hB fp_log2(
#define hA aC2(0)
#define h9 {2,N(-1.75),N(1.75)mR1,qM
#define h8 ,false,aH2
#define h7 1 h8
#define h6 (4l),y+q0(6l qQ
#define h5 N(3.0,0.0),N(5.0,0.0),wK2 q7
#define h4 "*((x^5.1)"
#define h3 "*((x^-5.1"
#define h2 "*((2.051^"
#define h1 wO"5/2)+abs(x)))"
#define h0 +q0(0x0020l)*fp_equal
#define gZ +q0(g42 g32(
#define gY -q0(2)),mflit0_0625)
#define gX N(-1.0,0.0)qJ mH1 q6
#define gW 0x0004l)*fp_greater
#define gV N(1e-6,0.0),N(4000.0,0.0),N(0.1,0.0)dP
#define gU {3,wX
#define gT {2,N(-2.0,0.0),mH1 qJ q7
#define gS 2,N(0.0,0.0)qJ N(1.0,0.0),q7
#define gR qA q8"/"
#define gQ mflit1_1 hU
#define gP fp_log10(
#define gO 0x0002l)*fp_lessOrEq
#define gN N(-6.0,-3.0),N(6.0,+3.0),N(0.5,+0.25),qM
#define gM !=aS1?
#define gL "(pow(x"
#define gK mflit5_0625,a42 mflit1_5,x))
#define gJ qP-q0(3)),-mflit0_015625)
#define gI N(-1.75,0.0),N(1.75,0.0),N(0.25,0.0),qM
#define gH 0x0008l)*fp_greaterOrEq
#define gG ")+x"},{1,0,1,1
#define gF fp_const_pi<q0>()
#define gE wW1)
#define gD {1,N(-0.7),N(0.7),N(0.28)qL
#define gC 2.051l),x
#define gB fp_abs(x)),
#define gA (((x mV)/gE+x*x-gE,((x mV)/gE+fp_abs(x)
#define g9 {2,-6,6,1,q7
#define g8 (w4 a=vars[0 mE1
#define g7 "01unit_operators/"
#define g6 {2,-15,15,2 q6
#define g5 ",y","10optimizer_bytecode"
#define g4 "*(((-2.051)^x)"
#define g3 +y+z+y+z+y+z+y+z
#define g2 q0(5.1l)),
#define g1 o33"0x"
#define g0 "y+z" o3"+y+z"
#define qZ LNG_ONLY(0)dT1
#define qY qC,&y q32,&z=vars[2 mE1 o0
#define qX +wW1*a22
#define qW aL1*fp_equal(
#define qV +q0(32l)*g32(
#define qU +q0(16l)*fp_greaterOrEq(
#define qT +q0(8l)*fp_greater(
#define qS +q0(4l)*dR1
#define qR "x,y" q8"/"
#define qQ ));}q3
#define qP a42 x,
#define qO qA,"02unit_functions"
#define qN a42 q0(
#define qM false,aF2
#define qL ,false q4
#define qK qC;return
#define qJ ,N(1.0,0.0),
#define qI ,aJ2
#define qH qC,&y=vars[1 mE1
#define qG aI2(0)q5
#define qF ,hA qO
#define qE "11optimizer_constaddmul/"
#define qD N(-15.0,0.0),N(15.0,0.0),mH1 q6
#define qC const q0 q1
#define qB qK q0::
#define qA LNG_ONLY(0)"x"
#define q9 q0*vars){const q0&a oI1 b=vars[1 mE1
#define q8 ,"20optimizer_optimizations"
#define q7 false,aB2
#define q6 ,false,aD2
#define q5 "x","10optimizer_bytecode"
#define q4 ,aE2
#define q3 template<typename q0>static q0
#define q2 N(-6.0,0.0),N(6.0,0.0)qJ q7
#define q1 *vars){const q0&x=vars[0]
#define q0 Value_t
#ifdef FP_TEST_WANT_DOUBLE_TYPE
#define DBL_ONLY(p) p,
#else
#define DBL_ONLY(p)
#endif
#ifdef FP_TEST_WANT_LONG_INT_TYPE
#define LNG_ONLY(p) p,
#else
#define LNG_ONLY(p)
#endif
#define APP(x,y) x##y
#define S {2,-dS1 Add_i,aI2(aF2 Add_i)gH1"add_i","x+y"},
#define T {3,-dS1 Addsub_i,aI2(aF2 Addsub_i)gZ2 g7"addsub_i","x+y+x+x-z+x"},
#define U {mF1 And_i,aI2(aF2 And_i)gH1"and_i","x&y"},
#define W {mF1 Cmpeq_i,aI2(aF2 Cmpeq_i)gH1"cmpeq_i","x=y"},
#define Y {mF1 Cmpge_i,aI2(aF2 Cmpge_i)gH1"cmpge_i","x>=y"},
#define S1 {mF1 Cmpgt_i,aI2(aF2 Cmpgt_i)gH1"cmpgt_i","x>y"},
#define T1 {mF1 Cmple_i,aI2(aF2 Cmple_i)gH1"cmple_i","x<=y"},
#define U1 {mF1 Cmplt_i,aI2(aF2 Cmplt_i)gH1"cmplt_i","x<y"},
#define W1 {mF1 Cmpne_i,aI2(aF2 Cmpne_i)gH1"cmpne_i","x!=y"},
#define Y1 gB1 Div_i,aI2(aF2 Div_i)gH1"div_i","x/(y+3" gO2
#define S2 {3,-46,40,2,qM Divmul_i,aI2(aF2 Divmul_i)gZ2 g7"divmul_i","x*y*x*x/(z+3)*(x+4" gO2
#define T2 {1,-41,40,3,qM Inv_i,aI2(aF2 Inv_i)"x",g7"inv_i","1/x"},
#define U2 gB1 Mod_i,aI2(aF2 Mod_i)"x,z",g7"mod_i","x%(z+3" gO2
#define W2 gB1 Mul_i,aI2(aF2 Mul_i)gH1"mul_i","x*(y+4" gO2
#define Y2 {1,-dS1 Neg_i,aI2(aF2 Neg_i)"x",g7"neg_i","-x"},
#define S3 {1 mG1 1,qM Not_i,aI2(aF2 Not_i)"x",g7"not_i","!x"},
#define T3 {1 mG1 1,qM Notnot_i,aI2(aF2 Notnot_i)"x",g7"notnot_i","!!x"},
#define U3 {mF1 Or_i,aI2(aF2 Or_i)gH1"or_i","x|y"},
#define W3 {2,-dS1 Sub_i,aI2(aF2 Sub_i)gH1"sub_i","x-y"},
#define Y3 {1,-40000,40000,1 dP Abs_i,aI2(aJ2 Abs_i)"x","02unit_functions/abs_i",hY3},
#define S4 {3 mG1 1 dP If_i,aI2(aJ2 If_i)gZ2"02unit_functions/if_i",o1",y,z" gO2
#define T4 {2,-4,4,1 dP Max,aC2(aJ2 Max)LNG_ONLY(aJ2 Max)"x" oJ"/max","max(x,y" gO2
#define U4 {2,-4,4,1 dP Min,aC2(aJ2 Min)LNG_ONLY(aJ2 Min)"x" oJ"/min","min(x,y" gO2
#define W4 a62 Abs,aC2(aE2 Abs)LNG_ONLY(aE2 Abs)dT1"abs","(abs(-3))+x"},
#define Y4 {dM Absnot,aC2(aE2 Absnot)LNG_ONLY(aE2 Absnot)dT1"absnot","!(abs" hF1
#define S5 {dM qZ3,aC2(aE2 qZ3)LNG_ONLY(aE2 qZ3)dT1"absnotnotnot","!(!!((x*x)))"},
#define T5 {mI1 qL o43,aC2(aE2 o43)LNG_ONLY(aE2 o43)dT1"absnzge","sub" oL1" >= 4, " hY3" >= 0" gO2
#define U5 {mI1 qL o53,aC2(aE2 o53)LNG_ONLY(aE2 o53)dT1"absnzlt","sub" oL1" < 4, " hY3" < 0" gO2
#define W5 {dM Abssqr,aC2(aE2 Abssqr)LNG_ONLY(aE2 Abssqr)dT1"abssqr","abs(x)*abs(x)"},
#define Y5 {1,-3,3,1 qL gO3,aC2(aE2 gO3)LNG_ONLY(aE2 gO3)dT1"dupaddmul7","(x+x)*7"},
#define S6 hR1 h53,aC2(aE2 h53)LNG_ONLY(aE2 h53)dT1 oY1,"sub(min(x,x), max(x," dX2
#define T6 hR1 gP3,aC2(aE2 gP3)LNG_ONLY(aE2 gP3)dT1 oY1"2","sub(x+min(x,x), x+max(x," dX2
#define U6 {2 mG1 1 qL gQ3,aC2(aE2 gQ3)LNG_ONLY(aE2 gQ3)gI1 oY1"3","sub(min(min(y,x),x), max(max(y,x)," dX2
#define W6 hR1 gR3,aC2(aE2 gR3)LNG_ONLY(aE2 gR3)dT1"dupxmuladd","x+(x*4" gO2
#define Y6 a32 Invmul,aC2(aE2 Invmul)LNG_ONLY(aE2 Invmul)gI1"invmul","y*(1/x)"},
#define S7 a62 Max,aC2(aE2 Max)LNG_ONLY(aE2 Max)dT1"max","max(5,4)+x"},
#define T7 a62 Min,aC2(aE2 Min)LNG_ONLY(aE2 Min)dT1"min","min(4,5)+x"},
#define U7 a62 Mul2,aC2(aE2 Mul2)LNG_ONLY(aE2 Mul2)dT1"mul2","x*2"},
#define W7 {oB3 1 qL Mul4,aC2(aE2 Mul4)LNG_ONLY(aE2 Mul4)gI1"mul4","y*(x*2)*2 + (y*2)*2"},
#define Y7 {dM Negabs,aC2(aE2 Negabs)LNG_ONLY(aE2 Negabs)dT1"negabs","abs" wM1
#define S8 {dM Negdiv,aC2(aE2 Negdiv)LNG_ONLY(aE2 Negdiv)dT1"negdiv","(-x)/" gV2
#define T8 {1,hE1 Negneg,aC2(aE2 Negneg)LNG_ONLY(aE2 Negneg)dT1"negneg","-(-(-(-(-(-(x))))))"},
#define U8 {dM Negnot,aC2(aE2 Negnot)LNG_ONLY(aE2 Negnot)dT1"negnot","!" wM1
#define W8 {dM Negsqr,aC2(aE2 Negsqr)LNG_ONLY(aE2 Negsqr)dT1"negsqr","(-x)*(-" aN1
#define Y8 {2 oG Not_eq,aC2(aE2 Not_eq)LNG_ONLY(aE2 Not_eq)gI1"not_eq","!" hX1
#define S9 {2 oG Not_ge,aC2(aE2 Not_ge)LNG_ONLY(aE2 Not_ge)gI1"not_ge","!" mB},
#define T9 {2 oG Not_gt,aC2(aE2 Not_gt)LNG_ONLY(aE2 Not_gt)gI1"not_gt","!(x > y" gO2
#define U9 {2 oG Not_le,aC2(aE2 Not_le)LNG_ONLY(aE2 Not_le)gI1"not_le","!" g51},
#define W9 {2 oG Not_lt,aC2(aE2 Not_lt)LNG_ONLY(aE2 Not_lt)gI1"not_lt","!(x < y" gO2
#define Y9 {2 oG Not_ne,aC2(aE2 Not_ne)LNG_ONLY(aE2 Not_ne)gI1"not_ne","!" hY1
#define SA {dM Notnot,aC2(aE2 Notnot)LNG_ONLY(aE2 Notnot)dT1"notnot","!!(x)"},
#define TA {dM h63,aC2(aE2 h63)LNG_ONLY(aE2 h63)dT1"notnotnot","!!!(x)"},
#define UA {dM gS3,aC2(aE2 gS3)LNG_ONLY(aE2 gS3)dT1"notnotnot2","!x&!x"},
#define WA {dM o63,aC2(aE2 o63)LNG_ONLY(aE2 o63)dT1"sqr_nxx","(-x)*x"},
#define YA {dM o73,aC2(aE2 o73)LNG_ONLY(aE2 o73)dT1"sqr_xnx","x*(-" aN1
#define SB {dM Sqr_xx,aC2(aE2 Sqr_xx)LNG_ONLY(aE2 Sqr_xx)dT1"sqr_xx","x*x"},
#define TB {wD1 hZ3,aC2(aE2 hZ3)LNG_ONLY(aE2 hZ3)gI1"sqr_ynxx","y*-x*x"},
#define UB {wD1 d03,aC2(aE2 d03)LNG_ONLY(aE2 d03)gI1"sqr_yxnx","y*x*-x"},
#define WB {wD1 o83,aC2(aE2 o83)LNG_ONLY(aE2 o83)gI1"sqr_yxx","y*x*x"},
#define YB {mI1 qL o93,aC2(aE2 o93)LNG_ONLY(aE2 o93)q5"/xaddnot","!(x+4" gO2
#define SC {mI1 qL gT3,aC2(aE2 gT3)LNG_ONLY(aE2 gT3)q5"/xaddnotnot","!!(x+4" gO2
#define TC {dM Xxdup,aC2(aE2 Xxdup)LNG_ONLY(aE2 Xxdup)q5"/xxdup","sub(x," aN1
#define UC {wD1 d13,aC2(aE2 d13)LNG_ONLY(aE2 d13)"x" g5"/xxsqrdup","y*abs(x)*abs(x)"},
#define WC {mI1,q7 o43,aC2(aB2 o43)LNG_ONLY(aB2 o43)gN1"absnzge","sub" oL1" >= if" wF2"), " hY3 dF2"(if(1,1,0)-1))"},
#define YC {mI1,q7 o53,aC2(aB2 o53)LNG_ONLY(aB2 o53)gN1"absnzlt","sub" oL1" < if" wF2"), " hY3" < (if(1,1,0)-1))"},
#define SD {d51 gF3,aC2(aB2 gF3)LNG_ONLY(aB2 gF3)qR"addconstmul","5*(if" wF2")+x+" oS2
#define TD {d51 qK3,aC2(aB2 qK3)LNG_ONLY(aB2 qK3)qR"addmulconstmul","5*(if" wF2")*y+x)"},
#define UD {d51 g03,aC2(aB2 g03)LNG_ONLY(aB2 g03)qR"addnegmulneg","-5 + (if(1,5,0)*x*" oS2
#define WD {d51 g13,aC2(aB2 g13)LNG_ONLY(aB2 g13)qR"addnegmulpos","(if(1,-5,0)*y" o42" (if(1,5,0)*x)"},
#define YD g9 qS3,aC2(aB2 qS3)LNG_ONLY(aB2 qS3)qR"cmpeq_add_imm",qX1 q52
#define SE {hW mP2,aC2(aB2 mP2)LNG_ONLY(aB2 mP2)gN1"cmpeq_add_reduce",dS" = " h1},
#define TE g9 mQ2,aC2(aB2 mQ2)LNG_ONLY(aB2 mQ2)qR"cmpeq_addadd_imm",dY2" =" gX3
#define UE dQ g23,aC2(aB2 g23)LNG_ONLY(aB2 g23)qR"cmpeq_minma" dX3"= " g33
#define WE dQ mR2,aC2(aB2 mR2)LNG_ONLY(aB2 mR2)qR"cmpeq_minma" dY3"= " mS2
#define YE g9 m72,aC2(aB2 m72)LNG_ONLY(aB2 m72)qR"cmpeq_mul_imm_neg",hC1 q52
#define SF g9 m82,aC2(aB2 m82)LNG_ONLY(aB2 m82)qR"cmpeq_mul_imm_pos",dU1 q52
#define TF g9 aO2,aC2(aB2 aO2)LNG_ONLY(aB2 aO2)qR"cmpeq_mulmul_imm_neg",a31" =" gX3
#define UF g9 aP2,aC2(aB2 aP2)LNG_ONLY(aB2 aP2)qR"cmpeq_mulmul_imm_pos",d23"=" gX3
#define WF g9 qT3,aC2(aB2 qT3)LNG_ONLY(aB2 qT3)qR"cmpge_add_imm",qX1 a41
#define YF {hW mT2,aC2(aB2 mT2)LNG_ONLY(aB2 mT2)gN1"cmpge_add_reduce",dS dF2 h1},
#define SG g9 mU2,aC2(aB2 mU2)LNG_ONLY(aB2 mU2)qR"cmpge_addadd_imm",dY2 dF2 hX
#define TG dQ g43,aC2(aB2 g43)LNG_ONLY(aB2 g43)qR"cmpge_minma" dX3">= " g33
#define UG dQ mV2,aC2(aB2 mV2)LNG_ONLY(aB2 mV2)qR"cmpge_minma" dY3">= " mS2
#define WG g9 m92,aC2(aB2 m92)LNG_ONLY(aB2 m92)qR"cmpge_mul_imm_neg",hC1 a41
#define YG g9 mA2,aC2(aB2 mA2)LNG_ONLY(aB2 mA2)qR"cmpge_mul_imm_pos",dU1 a41
#define SH g9 aQ2,aC2(aB2 aQ2)LNG_ONLY(aB2 aQ2)qR"cmpge_mulmul_imm_neg",a31 dF2 hX
#define TH g9 aR2,aC2(aB2 aR2)LNG_ONLY(aB2 aR2)qR"cmpge_mulmul_imm_pos",wO"4)" dF2 hX
#define UH g9 qU3,aC2(aB2 qU3)LNG_ONLY(aB2 qU3)qR"cmpgt_add_imm",qX1 qC2
#define WH {hW mW2,aC2(aB2 mW2)LNG_ONLY(aB2 mW2)gN1"cmpgt_add_reduce",dS" > " h1},
#define YH g9 mX2,aC2(aB2 mX2)LNG_ONLY(aB2 mX2)qR"cmpgt_addadd_imm",dY2" >" gX3
#define SI dQ g53,aC2(aB2 g53)LNG_ONLY(aB2 g53)qR"cmpgt_minma" dX3"> " g33
#define TI dQ mY2,aC2(aB2 mY2)LNG_ONLY(aB2 mY2)qR"cmpgt_minma" dY3"> " mS2
#define UI g9 mB2,aC2(aB2 mB2)LNG_ONLY(aB2 mB2)qR"cmpgt_mul_imm_neg",hC1 qC2
#define WI g9 mC2,aC2(aB2 mC2)LNG_ONLY(aB2 mC2)qR"cmpgt_mul_imm_pos",dU1 qC2
#define YI g9 aS2,aC2(aB2 aS2)LNG_ONLY(aB2 aS2)qR"cmpgt_mulmul_imm_neg",a31" >" gX3
#define SJ g9 aT2,aC2(aB2 aT2)LNG_ONLY(aB2 aT2)qR"cmpgt_mulmul_imm_pos",d23">" gX3
#define TJ g9 qV3,aC2(aB2 qV3)LNG_ONLY(aB2 qV3)qR"cmple_add_imm",qX1 a51
#define UJ {hW mZ2,aC2(aB2 mZ2)LNG_ONLY(aB2 mZ2)gN1"cmple_add_reduce",dS oT3 h1},
#define WJ g9 q03,aC2(aB2 q03)LNG_ONLY(aB2 q03)qR"cmple_addadd_imm",dY2" " w13
#define YJ dQ g63,aC2(aB2 g63)LNG_ONLY(aB2 g63)qR"cmple_minma" dX3"<= " g33
#define SK dQ q13,aC2(aB2 q13)LNG_ONLY(aB2 q13)qR"cmple_minma" dY3"<= " mS2
#define TK g9 mD2,aC2(aB2 mD2)LNG_ONLY(aB2 mD2)qR"cmple_mul_imm_neg",hC1 a51
#define UK g9 mE2,aC2(aB2 mE2)LNG_ONLY(aB2 mE2)qR"cmple_mul_imm_pos",dU1 a51
#define WK g9 aU2,aC2(aB2 aU2)LNG_ONLY(aB2 aU2)qR"cmple_mulmul_imm_neg",a31" " w13
#define YK g9 aV2,aC2(aB2 aV2)LNG_ONLY(aB2 aV2)qR"cmple_mulmul_imm_pos",d23 w13
#define SL g9 qW3,aC2(aB2 qW3)LNG_ONLY(aB2 qW3)qR"cmplt_add_imm",qX1 a61},
#define TL {hW q23,aC2(aB2 q23)LNG_ONLY(aB2 q23)gN1"cmplt_add_reduce",dS oV3 h1},
#define UL g9 q33,aC2(aB2 q33)LNG_ONLY(aB2 q33)qR"cmplt_addadd_imm",dY2" " w23
#define WL dQ g73,aC2(aB2 g73)LNG_ONLY(aB2 g73)qR"cmplt_minma" dX3"< " g33
#define YL dQ q43,aC2(aB2 q43)LNG_ONLY(aB2 q43)qR"cmplt_minma" dY3"< " mS2
#define SM g9 mF2,aC2(aB2 mF2)LNG_ONLY(aB2 mF2)qR"cmplt_mul_imm_neg",hC1 a61},
#define TM g9 mG2,aC2(aB2 mG2)LNG_ONLY(aB2 mG2)qR"cmplt_mul_imm_pos",dU1 a61},
#define UM g9 aW2,aC2(aB2 aW2)LNG_ONLY(aB2 aW2)qR"cmplt_mulmul_imm_neg",a31" " w23
#define WM g9 aX2,aC2(aB2 aX2)LNG_ONLY(aB2 aX2)qR"cmplt_mulmul_imm_pos",d23 w23
#define YM g9 qX3,aC2(aB2 qX3)LNG_ONLY(aB2 qX3)qR"cmpne_add_imm",qX1 dV1},
#define SN {hW q53,aC2(aB2 q53)LNG_ONLY(aB2 q53)gN1"cmpne_add_reduce",dS dG2 h1},
#define TN g9 q63,aC2(aB2 q63)LNG_ONLY(aB2 q63)qR"cmpne_addadd_imm",dY2 dG2 hX
#define UN dQ g83,aC2(aB2 g83)LNG_ONLY(aB2 g83)qR"cmpne_minma" h12 gZ3 g33
#define WN dQ q73,aC2(aB2 q73)LNG_ONLY(aB2 q73)qR"cmpne_minma" h42 gZ3 mS2
#define YN g9 mH2,aC2(aB2 mH2)LNG_ONLY(aB2 mH2)qR"cmpne_mul_imm_neg",hC1 dV1},
#define SO g9 mI2,aC2(aB2 mI2)LNG_ONLY(aB2 mI2)qR"cmpne_mul_imm_pos",dU1 dV1},
#define TO g9 aY2,aC2(aB2 aY2)LNG_ONLY(aB2 aY2)qR"cmpne_mulmul_imm_neg",a31 dG2 hX
#define UO g9 aZ2,aC2(aB2 aZ2)LNG_ONLY(aB2 aZ2)qR"cmpne_mulmul_imm_pos",wO"4)" dG2 hX
#define WO g9 qY3,aC2(aB2 qY3)LNG_ONLY(aB2 qY3)qR"cmpzz_add_imm" dT h52 a61 aE h52 oZ1 h52 a71 qX1 a81 h52 dV1 d7 qX1 q52
#define YO {hW q83,aC2(aB2 q83)LNG_ONLY(aB2 q83)gN1"cmpzz_add_reduce" dT" " dS oV3 h1 aE" " dS oT3 h1 aG" " dS" > " h1 aC dS dF2 h1 hD1" " dS dG2 h1 d7 dS" = " h1},
#define SP g9 q93,aC2(aB2 q93)LNG_ONLY(aB2 q93)qR"cmpzz_addadd_imm" dT" " o6 q62" " o6 q92" " o6 qA2 dY2 dF2 dZ2" " dY2 oW1 dY2" =" gX3
#define TP dQ g93,aC2(aB2 g93)LNG_ONLY(aB2 g93)qR"cmpzz_minmax" dT d33"< " d43 aE d33"<= " d43 aG d33"> " d43 g1"0008 " h62" >= y,x,y" wI g11 gZ3"y,x,y" o42"  0x0020 " h62" = " g33
#define UP dQ qA3,aC2(aB2 qA3)LNG_ONLY(aB2 qA3)qR"cmpzz_minmax_rev" dT d33"< " gK3 aE d33"<= " gK3 aG d33"> " gK3 g1"0008 " h62" >= " gK3 hD1 g11 gZ3 gK3" +  0x0020 " h62" = " mS2
#define WP g9 mJ2,aC2(aB2 mJ2)LNG_ONLY(aB2 mJ2)qR"cmpzz_mul_imm_neg" dT mJ1 a61 aE mJ1 oZ1 mJ1 a71 hC1 a81 mJ1 dV1 d7 hC1 q52
#define YP g9 mK2,aC2(aB2 mK2)LNG_ONLY(aB2 mK2)qR"cmpzz_mul_imm_pos" dT mK1 a61 aE mK1 oZ1 mK1 a71 dU1 a81 mK1 dV1 d7 dU1 q52
#define SQ g9 m02,aC2(aB2 m02)LNG_ONLY(aB2 m02)qR"cmpzz_mulmul_imm_neg" dT qY1 q62 qY1 q92 qY1 qA2 a31 dF2 dZ2 qY1")" oW1 a31" =" gX3
#define TQ g9 m12,aC2(aB2 m12)LNG_ONLY(aB2 m12)qR"cmpzz_mulmul_imm_pos" dT qZ1 q62 qZ1 q92 qZ1 qA2 wO"4)" dF2 dZ2 qZ1")" oW1 d23"=" gX3
#define UQ dQ h73,aC2(aB2 h73)LNG_ONLY(aB2 h73)qR"ge_and_eq",o02 hX1
#define WQ dQ h83,aC2(aB2 h83)LNG_ONLY(aB2 h83)qR"ge_and_le",o02 g51},
#define YQ dQ h93,aC2(aB2 h93)LNG_ONLY(aB2 h93)qR"ge_and_ne",o02 hY1
#define SR dQ d53,aC2(aB2 d53)LNG_ONLY(aB2 d53)qR"ge_or_eq",o12 hX1
#define TR dQ d63,aC2(aB2 d63)LNG_ONLY(aB2 d63)qR"ge_or_le",o12 g51},
#define UR dQ d73,aC2(aB2 d73)LNG_ONLY(aB2 d73)qR"ge_or_ne",o12 hY1
#define WR dQ hA3,aC2(aB2 hA3)LNG_ONLY(aB2 hA3)qR"gt_and_eq" mL1 hX1
#define YR dQ hB3,aC2(aB2 hB3)LNG_ONLY(aB2 hB3)qR"gt_and_ge" mL1 mB},
#define SS dQ hC3,aC2(aB2 hC3)LNG_ONLY(aB2 hC3)qR"gt_and_le" mL1 g51},
#define TS dQ hD3,aC2(aB2 hD3)LNG_ONLY(aB2 hD3)qR"gt_and_ne" mL1 hY1
#define US dQ d83,aC2(aB2 d83)LNG_ONLY(aB2 d83)qR"gt_or_eq" mM1 hX1
#define WS dQ d93,aC2(aB2 d93)LNG_ONLY(aB2 d93)qR"gt_or_ge" mM1 mB},
#define YS dQ dA3,aC2(aB2 dA3)LNG_ONLY(aB2 dA3)qR"gt_or_le" mM1 g51},
#define ST dQ dB3,aC2(aB2 dB3)LNG_ONLY(aB2 dB3)qR"gt_or_ne" mM1 hY1
#define TT g91 If10,aC2(aB2 If10)LNG_ONLY(aB2 If10)gN1"if10",o1",1,0" o42" 10*" o1",0,1)" o13" + 100*" o1">0,1,0" o42" 1000*" o1">0,0,1" gO2
#define UT {wP qL3,aC2(aB2 qL3)LNG_ONLY(aB2 qL3)gQ2"tract_abs",dZ3"abs(x+2), abs(y+5))"},
#define WT {wP qM3,aC2(aB2 qM3)LNG_ONLY(aB2 qM3)gQ2"tract_add" aX1"+2, y+" q12
#define YT {wP qE3,aC2(aB2 qE3)LNG_ONLY(aB2 qE3)gQ2"tract_add1" aX1"+2, y" gO2
#define SU {wP qF3,aC2(aB2 qF3)LNG_ONLY(aB2 qF3)gQ2"tract_add2",dZ3"y, y+2" gO2
#define TU {qN1 mL2,aC2(aB2 mL2)LNG_ONLY(aB2 mL2)mN1"tract_and1_l" aX1"&z, y<1" gO2
#define UU {qN1 m32,aC2(aB2 m32)LNG_ONLY(aB2 m32)mN1"tract_and1_nl" aX1"&z, z" gO2
#define WU {qN1 mM2,aC2(aB2 mM2)LNG_ONLY(aB2 mM2)mN1"tract_and2_l",dZ3"y<1, y&z" gO2
#define YU {qN1 m42,aC2(aB2 m42)LNG_ONLY(aB2 m42)mN1"tract_and2_nl",dZ3"z, y&z" gO2
#define SV {wP If_extract_div,aI2(aB2 If_extract_div)gQ2"tract_div" aX1"/x, y/2" gO2
#define TV {wP qN3,aC2(aB2 qN3)LNG_ONLY(aB2 qN3)gQ2"tract_min",dZ3"min(y,2), min(y,5))"},
#define UV {wP qO3,aC2(aB2 qO3)LNG_ONLY(aB2 qO3)gQ2"tract_mul" aX1"*2, y*" q12
#define WV {wP qG3,aC2(aB2 qG3)LNG_ONLY(aB2 qG3)gQ2"tract_mul1" aX1"*2, y" gO2
#define YV {wP qH3,aC2(aB2 qH3)LNG_ONLY(aB2 qH3)gQ2"tract_mul2",dZ3"y, y*2" gO2
#define SW {qN1 qB3,aC2(aB2 qB3)LNG_ONLY(aB2 qB3)mN1"tract_or1_l",dZ3"y|z, y<1" gO2
#define TW {qN1 mN2,aC2(aB2 mN2)LNG_ONLY(aB2 mN2)mN1"tract_or1_nl",dZ3"y|z, z" gO2
#define UW {qN1 qC3,aC2(aB2 qC3)LNG_ONLY(aB2 qC3)mN1"tract_or2_l",dZ3"y<1, y|z" gO2
#define WW {qN1 mO2,aC2(aB2 mO2)LNG_ONLY(aB2 mO2)mN1"tract_or2_nl",dZ3"z, y|z" gO2
#define YW {1,3,5,1,q7 gA3,aC2(aB2 gA3)LNG_ONLY(aB2 gA3)gN1"if_join_add2","x + 10 +" g11"<4, 3,4" gO2
#define SX {1,3,5,1,q7 gB3,aC2(aB2 gB3)LNG_ONLY(aB2 gB3)gN1"if_join_mul2","x * 10 " h62"<4, 3,4" gO2
#define TX oA1 Ifabs,aC2(aB2 Ifabs)LNG_ONLY(aB2 Ifabs)gN1"ifabs","1" qO1"< 0,-x" qP3 o13"10" qO1"<=0,-x" qP3"  100" qO1"> 0,-x" qP3" 1000" qO1">=0,-x" qP3"10000" qO1"< 0,x" h82 aM2" 100000" qO1"<=0,x" h82 aM2"1000000" qO1"> 0,x" h82"  10000000" qO1">=0,x,-" dX2
#define UX {qD2 oA3,aC2(aB2 oA3)LNG_ONLY(aB2 oA3)"b,d," qR"ifmerge",o1 gJ2"y,x,b" oV2"y,x,d)) +  if(b,if(d,y,x)" gJ2"d,b," dX2
#define WX {qD2 dC3,aC2(aB2 dC3)LNG_ONLY(aB2 dC3)"a,b," qR"ifmerge2",o1 gJ2"y,a,b" oV2"b,a,b))"},
#define YX {qD2 hE3,aC2(aB2 hE3)LNG_ONLY(aB2 hE3)"a,b," qR"ifmerge2b",o1 gJ2"y,a,b" oV2"b,b,a))"},
#define SY dQ Ifnop,aC2(aB2 Ifnop)LNG_ONLY(aB2 Ifnop)qR"ifnop",o1",y,y" gO2
#define TY {d41 L_abs,aC2(aB2 L_abs)LNG_ONLY(aB2 L_abs)qR"l_abs","(x+2) & " hY3 hB1
#define UY {d41 dD3,aC2(aB2 dD3)LNG_ONLY(aB2 dD3)qR"l_mulabs","(x*abs(y))" hB1
#define WY {d41 dE3,aC2(aB2 dE3)LNG_ONLY(aB2 dE3)qR"l_mulneg","(x*y*-5)" hB1
#define YY {d41 dF3,aC2(aB2 dF3)LNG_ONLY(aB2 dF3)qR"l_notnot","(x+2) & !!x" hB1
#define SZ dQ hF3,aC2(aB2 hF3)LNG_ONLY(aB2 hF3)qR"le_and_eq",g51" & " hX1
#define TZ dQ hG3,aC2(aB2 hG3)LNG_ONLY(aB2 hG3)qR"le_and_ne",g51" & " hY1
#define UZ dQ dG3,aC2(aB2 dG3)LNG_ONLY(aB2 dG3)qR"le_or_eq",g51" | " hX1
#define WZ dQ dH3,aC2(aB2 dH3)LNG_ONLY(aB2 dH3)qR"le_or_ne",g51" | " hY1
#define YZ dQ hH3,aC2(aB2 hH3)LNG_ONLY(aB2 hH3)qR"lt_and_eq" qE2 hX1
#define Sa dQ hI3,aC2(aB2 hI3)LNG_ONLY(aB2 hI3)qR"lt_and_ge" qE2 mB},
#define Ta dQ hJ3,aC2(aB2 hJ3)LNG_ONLY(aB2 hJ3)qR"lt_and_gt" qE2"(x > y" gO2
#define Ua dQ hK3,aC2(aB2 hK3)LNG_ONLY(aB2 hK3)qR"lt_and_le" qE2 g51},
#define Wa dQ hL3,aC2(aB2 hL3)LNG_ONLY(aB2 hL3)qR"lt_and_ne" qE2 hY1
#define Ya dQ dI3,aC2(aB2 dI3)LNG_ONLY(aB2 dI3)qR"lt_or_eq" hM3 hX1
#define Sb dQ dJ3,aC2(aB2 dJ3)LNG_ONLY(aB2 dJ3)qR"lt_or_ge" hM3 mB},
#define Tb dQ dK3,aC2(aB2 dK3)LNG_ONLY(aB2 dK3)qR"lt_or_gt" hM3"(x > y" gO2
#define Ub dQ dL3,aC2(aB2 dL3)LNG_ONLY(aB2 dL3)qR"lt_or_le" hM3 g51},
#define Wb dQ dM3,aC2(aB2 dM3)LNG_ONLY(aB2 dM3)qR"lt_or_ne" hM3 hY1
#define Yb {qN1 gG3,aC2(aB2 gG3)LNG_ONLY(aB2 gG3)aP"mergemulabs","abs(x)*abs(y)*z"},
#define Sc {3,0,4,1,q7 gH3,aC2(aB2 gH3)LNG_ONLY(aB2 gH3)aP"mixedminmax","max(z,min(x,max(max(z,y),x)))" o33"10*min(z,max(x,min(y,x)))" o33"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Tc dQ Nand2,aC2(aB2 Nand2)LNG_ONLY(aB2 Nand2)qR"nand2",hN3},
#define Uc mO1 hO3,aC2(aB2 hO3)LNG_ONLY(aB2 hO3)aP"nand2plus",hN3" | z"},
#define Wc mO1 Nand3,aC2(aB2 Nand3)LNG_ONLY(aB2 Nand3)aP"nand3",hN3" | !z"},
#define Yc dQ Nor2,aC2(aB2 Nor2)LNG_ONLY(aB2 Nor2)qR"nor2",hP3},
#define Sd mO1 dN3,aC2(aB2 dN3)LNG_ONLY(aB2 dN3)aP"nor2plus",hP3" & z"},
#define Td mO1 Nor3,aC2(aB2 Nor3)LNG_ONLY(aB2 Nor3)aP"nor3",hP3" & !z"},
#define Ud dQ Not_eq,aC2(aB2 Not_eq)LNG_ONLY(aB2 Not_eq)qR"not_eq",o1" = " m22
#define Wd dQ Not_ge,aC2(aB2 Not_ge)LNG_ONLY(aB2 Not_ge)qR"not_ge",o1" >= " m22
#define Yd dQ Not_gt,aC2(aB2 Not_gt)LNG_ONLY(aB2 Not_gt)qR"not_gt",o1" > " m22
#define Se dQ Not_le,aC2(aB2 Not_le)LNG_ONLY(aB2 Not_le)qR"not_le",o1 oT3 m22
#define Te dQ Not_lt,aC2(aB2 Not_lt)LNG_ONLY(aB2 Not_lt)qR"not_lt",o1 oV3 m22
#define Ue dQ Not_ne,aC2(aB2 Not_ne)LNG_ONLY(aB2 Not_ne)qR"not_ne",o1 gZ3 m22
#define We {wP Notnot,aC2(aB2 Notnot)LNG_ONLY(aB2 Notnot)qR"notnot","!!x + if(y, 1,0" gO2
#define Ye {mI1,q7 o93,aC2(aB2 o93)LNG_ONLY(aB2 o93)"x" q8"/xaddnot","!(x+if(1,4,4))"},
#define Sf {mI1,q7 gT3,aC2(aB2 gT3)LNG_ONLY(aB2 gT3)"x" q8"/xaddnotnot","!!(x+if(1,4,4))"},
#define Tf {1,-a91 t1,aC2(aG2 t1)LNG_ONLY(aG2 t1)wE2"1","x+max(0, min(-2,0))"},
#define Uf {1,-a91 t2,aC2(aG2 t2)LNG_ONLY(aG2 t2)wE2"2","min(x,min(1," dX2
#define Wf {1 h92 t3,aC2(aG2 t3)LNG_ONLY(aG2 t3)wE2"3","sub(  (!x & !!x) ,  (!x | !!x)  " gO2
#define Yf {2 h92 t4,aC2(aG2 t4)LNG_ONLY(aG2 t4)"x,y",oK"4","sub(!(x-y), !!(x-y))"},
#define Sg {mI1,hI t6,aC2(aG2 t6)LNG_ONLY(aG2 t6)wE2"6","sub(!(x+4), !!(x+3))"},
#define Tg {1,-a91 t36,aC2(aG2 t36)LNG_ONLY(aG2 t36)wE2"36","-if(x<0, x, -x) + -if(x<5, 2, 3" gO2
#define Ug {2 h92 t60,aC2(aG2 t60)LNG_ONLY(aG2 t60)"x,y",oK"60","sqr(x) | sub(x,y) | value()"},
#define Wg {2,-20,20,h7 t16,aC2(aH2 t16)LNG_ONLY(aH2 t16)d61"16",o1"<0, if(y<0, x+y, x-y), if(y>0, x*y, x+2*y))"},
#define Yg {2,-20,20,h7 t17,aC2(aH2 t17)LNG_ONLY(aH2 t17)d61"17","sqr(x)+sub(x,y)+psqr(y)+psub(y+1,x-2)-1"},
#define Sh {2,-100,100,h7 t19,aC2(aH2 t19)LNG_ONLY(aH2 t19)d61"19","(x<y)+10" wE1"<=y)+100" wE1">y)+1000" wE1">=y)+10000" wE1"=y)+100000" wE1"!=y)+  (x&y)*2+(x|y)*20+(!x)*200+(!!x)*2000+4*!((x<y)&(x<3))+40*!!(!(x>y)|(x>3))"},
#define Th {2,-100,100,h7 t20,aC2(aH2 t20)LNG_ONLY(aH2 t20)d61"20","(!(x" gZ3"y) & !x) + !(!(!(!y)))"},
#define Uh {1,-hA2 t21,aC2(aH2 t21)LNG_ONLY(aH2 t21)"x",oZ"21","sqr(x)+value()-pvalue ( " gO2
#define Wh wJ2 h7 t24,aC2(aH2 t24)LNG_ONLY(aH2 t24)"x",oZ"24","(min(x, min(1," w01" min(x, 1))/2 + min(x, 1)*3 + max(0, min(-2,0))"},
#define Yh {2,-5,5,h7 t29,aC2(aH2 t29)LNG_ONLY(aH2 t29)d61"29","x-y*1"},
#define Si {4,-5,5,h7 t34,aC2(aH2 t34)LNG_ONLY(aH2 t34)"t,う,お,早",oZ"34","お+早*う-t"},
#define Ti {3,-hA2 t35,aC2(aH2 t35)LNG_ONLY(aH2 t35)"A_very_long_variable_name_1,A_very_long_variable_name_2,Yet_a_third_very_long_variable_name",oZ"35","A_very_long_variable_name_1-A_very_long_variable_name_2+  Yet_a_third_very_long_variable_name*A_very_long_variable_name_1"},
#define Ui {2,-hA2 t50,aC2(aH2 t50)LNG_ONLY(aH2 t50)d61"50","(x<y | y<x) +" o23"2" wE1"<y & y<x) +" o23"4" gU3"y<=x) +" o23"8" wE1"<y & " qF2 o23"16" wE1"<y | " qF2 o23"32" gU3"x>=y" gL3" 64" wE1"<=y | x>=y" gL3" 128" wE1"!=y & x=y" gL3" 256" wE1"!=y & " qF2"  512" gU3"x=y" gO2
#define Wi {2,-11,11,h7 t58,aC2(aH2 t58)LNG_ONLY(aH2 t58)d61"58","(-x < 3" o72"-1 > 5" o72"-3 < 10" o72"-3 < y*7" o42"  (x*4 < y*7" o72"6 < y*-3" o42" (-x < 11" o42" (5 < -y" gO2
#define Yi {3,-8,7,h7 I1,aI2(aH2 I1)mU1"i1","1+2+3-4*5*6/3+10/2-9%2 + (x+y - 11*x + z/10 + x/(z+31))"},
#define Sj {3,-7,7,h7 I2,aI2(aH2 I2)mU1"i2","if(abs(x*y) < 20 | x+y > 30 & z > 5, min(x,2*y), max(y,z*2))"},
#define Tj {3,1,7,h7 I3,aI2(aH2 I3)mU1"i3","(x+y" o42" 2" wE1"-z" o42" 3*(x*y" o42" 4*(y/z" o42" 5" wE1"%z" gL3"6" wE1"<y" o42" 7" wE1"<=z" o42" 8" wE1">2" o32" 9*(y>=3" o32" 10*(x+y!=z" o42"  11*(100+x) + 12*(101-y" o42" 13*(102" o32" 14*(103/x)"},
#define Uj {2,qP1 Add_d,aC2(aF2 Add_d)wQ"add_d","x+y"},
#define Wj {3,qP1 Addsub_d,aC2(aF2 Addsub_d)qG2 g7"addsub_d","x+y+x+x-z+x"},
#define Yj h9 And_d,aC2(aF2 And_d)wQ"and_d","x&y"},
#define Sk h9 Cmpeq_d,aC2(aF2 Cmpeq_d)wQ"cmpeq_d","x=y"},
#define Tk h9 Cmpge_d,aC2(aF2 Cmpge_d)wQ"cmpge_d","x>=y"},
#define Uk h9 Cmpgt_d,aC2(aF2 Cmpgt_d)wQ"cmpgt_d","x>y"},
#define Wk h9 Cmple_d,aC2(aF2 Cmple_d)wQ"cmple_d","x<=y"},
#define Yk h9 Cmplt_d,aC2(aF2 Cmplt_d)wQ"cmplt_d","x<y"},
#define Sl h9 Cmpne_d,aC2(aF2 Cmpne_d)wQ"cmpne_d","x!=y"},
#define Tl {2,a4 Div_d,aC2(aF2 Div_d)wQ"div_d","(x-0.25)/y"},
#define Ul {3,a4 Divmul_d,aC2(aF2 Divmul_d)qG2 g7"divmul_d","x*y*x*x/z" wE1"-0.25" gO2
#define Wl {1,-7,6,N(0.6),qM Inv_d,aC2(aF2 Inv_d)qA,g7"inv_d","1/x"},
#define Yl {2,a4 Mul_d,aC2(aF2 Mul_d)wQ"mul_d","x*y"},
#define Sm {1,qP1 Neg_d,aC2(aF2 Neg_d)qA,g7"neg_d","-x"},
#define Tm {1,aH,qM Not_d,aC2(aF2 Not_d)qA,g7"not_d","!x"},
#define Um {1,aH,qM Notnot_d,aC2(aF2 Notnot_d)qA,g7"notnot_d","!!x"},
#define Wm h9 Or_d,aC2(aF2 Or_d)wQ"or_d","x|y"},
#define Ym {2,qP1 Sub_d,aC2(aF2 Sub_d)wQ"sub_d","x-y"},
#define Sn {1,-400,400,N(0.5)dP Abs_d,aC2(aJ2 Abs_d)qO"/abs_d",hY3},
#define Tn {3,aH dP If_d,aC2(aJ2 If_d)qG2"02unit_functions/if_d",o1",y,z" gO2
#define Un {1,-4000,dL1 Int,aC2(aJ2 Int)qO"/int","int(x)"},
#define Wn wR Absneverneg,aC2(aE2 Absneverneg)qZ"absneverneg" mA1 gE3
#define Yn wR Absnot2,aC2(aE2 Absnot2)qZ"absnot2","!acos(x)"},
#define So {2 dN N(0.25)qL Absnot3,aC2(aE2 Absnot3)dI2"absnot3","!(!(x&y))"},
#define To wR Absnot4,aC2(aE2 Absnot4)qZ"absnot4","!(!acos" hF1
#define Uo {1,1,3,N(0.1)qL Acoshcosh,aC2(aE2 Acoshcosh)qZ"acoshcosh","cosh(" oB2 hF1
#define Wo {1,N(1.7),N(3.7),N(0.28)qL Acoshsinh,aC2(aE2 Acoshsinh)qZ oB2 gK2,gK2"(" oB2 hF1
#define Yo {1,-3,-3,N(0.7)qL Addexp,aC2(aE2 Addexp)qZ"addexp","exp(x+4" gO2
#define Sp {1,-3,-3,N(0.7)qL Addexp2,aC2(aE2 Addexp2)qZ"addexp2","exp2(x+4" gO2
#define Tp gD Asinhcosh,aC2(aE2 Asinhcosh)qZ"asinhcosh","cosh(a" gK2 hF1
#define Up {1,q61 Asinhsinh,aC2(aE2 Asinhsinh)qZ a92 gK2,gK2"(a" gK2 hF1
#define Wp {oB3 N(0.11)qL Atan2tan,aC2(aE2 Atan2tan)dI2"atan2tan","tan(" hT2"(x,y))"},
#define Yp {1 mC Ceilneg,aC2(aE2 Ceilneg)qZ"ceilneg","ceil" wM1
#define Sq {2,-qQ1 Deg,aC2(aE2 Deg)dI2"deg","(" hB2")*y + x*(" hB2 o42" (y*(" hB2"))*4"},
#define Tq {1 dN N(0.5),d62 Degxmul,aC2(aE2 Degxmul)qZ"degxmul","acos(x)*2"},
#define Uq {1,-3,3,1 qL Dupaddmulh,aC2(aE2 Dupaddmulh)qZ"dupaddmulh","(x+x)*0.5"},
#define Wq {oB3 1 qL Dupaddmulmul7,aC2(aE2 Dupaddmulmul7)dI2"dupaddmulmul7","y*(x+x)*7"},
#define Yq {oB3 1 qL Dupaddmulmulh,aC2(aE2 Dupaddmulmulh)dI2"dupaddmulmulh","y*(x+x)*0.5"},
#define Sr hR1 Dupxpowmul,aC2(aE2 Dupxpowmul)qZ"dupxpowmul","x*(x^3" gO2
#define Tr a32 Exp2div,aC2(aE2 Exp2div)dI2"exp2div","x/exp2(" oS2
#define Ur {1,q61 Exp2log2,aC2(aE2 Exp2log2)qZ"exp2log2","log2(exp2" hF1
#define Wr a32 Expdiv,aC2(aE2 Expdiv)dI2"expdiv","x/" dJ2 oS2
#define Yr {1,q61 Explog,aC2(aE2 Explog)qZ"explog","log(ex" oC2
#define Ss {1,q61 Explog2,aC2(aE2 Explog2)qZ"explog2","log2(ex" oC2
#define Ts {1,q61 Explog10,aC2(aE2 Explog10)qZ"explog10","log10(ex" oC2
#define Us {1 mC Floorneg,aC2(aE2 Floorneg)qZ"floorneg","floor" wM1
#define Ws {1,N(-1.5),N(1.5)mR1 qL Int,aC2(aE2 Int)qZ"int","x+" aA1 aA1"sub(int(1.1), int(1.6" dW1"1.5" dW1"-1.1" dW1"-1.6" dW1"-1.5))"},
#define Ys {1 mC Intceil,aC2(aE2 Intceil)qZ"intceil","ceil" wF1
#define St {1 mC Intfloor,aC2(aE2 Intfloor)qZ"intfloor","floor" wF1
#define Tt {1 mC Intint,aC2(aE2 Intint)qZ"intint","int" wF1
#define Ut {1 mC Inttrunc,aC2(aE2 Inttrunc)qZ"inttrunc","trunc" wF1
#define Wt a32 Invdiv,aC2(aE2 Invdiv)dI2"invdiv","y/(1/x)"},
#define Yt {1,hE1 Invinv,aC2(aE2 Invinv)qZ"invinv","1/(1/x)"},
#define Su {1 mC Negceil,aC2(aE2 Negceil)qZ"negceil","-ceil(x)"},
#define Tu {1 mC Negfloor,aC2(aE2 Negfloor)qZ"negfloor","-floor(x)"},
#define Uu a32 Powdiv,aC2(aE2 Powdiv)dH2"/powdiv","x/pow(x,y" gO2
#define Wu gT1 Powhalf,aC2(aE2 Powhalf)w6"half",qH2",0.5" gO2
#define Yu a32 Powinv,aC2(aE2 Powinv)dH2"/powinv","1/pow(x,y" gO2
#define Sv gT1 Powminushalf,aC2(aE2 Powminushalf)w6"minushalf",qH2",-0.5" gO2
#define Tv {1,1,5,1 qL Powminusone,aC2(aE2 Powminusone)w6"minusone",qH2",-1.0" gO2
#define Uv gT1 Powminusthird,aC2(aE2 Powminusthird)w6"minusthird",qH2",(-1.0/3.0))"},
#define Wv gT1 Powthird,aC2(aE2 Powthird)w6"third",qH2"," mY1"/3.0))"},
#define Yv {2,-qQ1 Rad,aC2(aE2 Rad)dI2"rad","(" mW1")*y + x*(" mW1 o42" (x*(" mW1"))*4"},
#define Sw {1 mG1 N(0.8)qL Radxmul,aC2(aE2 Radxmul)qZ"radxmul","cos" wO mW1")*4" gO2
#define Tw {1,-qQ1 Sqrlog,aC2(aE2 Sqrlog)qZ"sqrlog","log" qI2
#define Uw {1,-qQ1 Sqrlog2,aC2(aE2 Sqrlog2)qZ"sqrlog2","log2" qI2
#define Ww {1,-qQ1 Sqrlog10,aC2(aE2 Sqrlog10)qZ"sqrlog10","log10" qI2
#define Yw {1 mG1 N(0.8),d62 Xmulrad,aC2(aE2 Xmulrad)a2"mulrad","cos" qT2
#define Sx {dM Xxfdup,aC2(aE2 Xxfdup)LNG_ONLY(0)q5"/xxfdup","sub(sin(x),sin(x))"},
#define Tx oA1 Abscos,aC2(aB2 Abscos)gR"abscos","cos(sqrt(" dX1"))) + sqrt(" dX1"))"},
#define Ux oA1 Abscosh,aC2(aB2 Abscosh)gR"abscosh","cosh(sqrt(" dX1"))) + sqrt(" dX1"))"},
#define Wx {1 dN N(0.1),q7 Acoscos,aC2(aB2 Acoscos)gR"acoscos","cos(acos" hF1
#define Yx {1,N(1.7),N(3.7),N(0.28),q7 Acoshsinh,aC2(aB2 Acoshsinh)gR oB2 gK2,gK2"(if(1,acosh(x),0))"},
#define Sy {2 mR1,mQ1 q7 Addlog,aC2(aB2 Addlog)aI"addlog","log(x)+log(" oS2
#define Ty mX1 Addsin2cos2,aC2(aB2 Addsin2cos2)gR"addsin2cos2",wQ1"^2 + cos(x)^2"},
#define Uy {1,N(-0.7),N(0.7),N(0.28),q7 Asinhcosh,aC2(aB2 Asinhcosh)gR"asinhcosh","cosh(if(1,a" gK2"(x),0))"},
#define Wy {1 dN N(0.1),q7 Asinsin,aC2(aB2 Asinsin)gR"asinsin","sin(asin(x))"},
#define Yy dC Cmpeq_pow_imm_negneg,aC2(aB2 Cmpeq_pow_imm_negneg)gR o11 hV" = " aK2
#define Sz dC Cmpeq_pow_imm_negpos,aC2(aB2 Cmpeq_pow_imm_negpos)gR o11 hY" = " aN2
#define Tz {hW Cmpeq_pow_imm_posneg,aC2(aB2 Cmpeq_pow_imm_posneg)gR o11 d2" = " m52
#define Uz {hW Cmpeq_pow_imm_pospos,aC2(aB2 Cmpeq_pow_imm_pospos)gR o11 d3" = " qQ3
#define Wz {hW Cmpeq_pow_imm_pospos_base,aC2(aB2 Cmpeq_pow_imm_pospos_base)gR o11 m62"= " wT
#define Yz g9 Cmpeq_powpow_imm_base,aC2(aB2 Cmpeq_powpow_imm_base)aI o11 hH" = " a7
#define S_ dC Cmpge_pow_imm_negneg,aC2(aB2 Cmpge_pow_imm_negneg)dY1 hV" >= " aK2
#define T_ dC Cmpge_pow_imm_negpos,aC2(aB2 Cmpge_pow_imm_negpos)dY1 hY" >= " aN2
#define U_ {hW Cmpge_pow_imm_posneg,aC2(aB2 Cmpge_pow_imm_posneg)dY1 d2" >= " m52
#define W_ {hW Cmpge_pow_imm_pospos,aC2(aB2 Cmpge_pow_imm_pospos)dY1 d3" >= " qQ3
#define Y_ {hW Cmpge_pow_imm_pospos_base,aC2(aB2 Cmpge_pow_imm_pospos_base)dY1 m62">= " wT
#define S01 g9 Cmpge_powpow_imm_base,aC2(aB2 Cmpge_powpow_imm_base)aI"cmpge_" hH dF2 a7
#define T01 dC Cmpgt_pow_imm_negneg,aC2(aB2 Cmpgt_pow_imm_negneg)hO1 hV" > " aK2
#define U01 dC Cmpgt_pow_imm_negpos,aC2(aB2 Cmpgt_pow_imm_negpos)hO1 hY" > " aN2
#define W01 {hW Cmpgt_pow_imm_posneg,aC2(aB2 Cmpgt_pow_imm_posneg)hO1 d2" > " m52
#define Y01 {hW Cmpgt_pow_imm_pospos,aC2(aB2 Cmpgt_pow_imm_pospos)hO1 d3" > " qQ3
#define S11 {hW Cmpgt_pow_imm_pospos_base,aC2(aB2 Cmpgt_pow_imm_pospos_base)hO1 m62"> " wT
#define T11 g9 Cmpgt_powpow_imm_base,aC2(aB2 Cmpgt_powpow_imm_base)aI"cmpgt_" hH" > " a7
#define U11 dC Cmple_pow_imm_negneg,aC2(aB2 Cmple_pow_imm_negneg)hP1 hV oT3 aK2
#define W11 dC Cmple_pow_imm_negpos,aC2(aB2 Cmple_pow_imm_negpos)hP1 hY oT3 aN2
#define Y11 {hW Cmple_pow_imm_posneg,aC2(aB2 Cmple_pow_imm_posneg)hP1 d2 oT3 m52
#define S21 {hW Cmple_pow_imm_pospos,aC2(aB2 Cmple_pow_imm_pospos)hP1 d3 oT3 qQ3
#define T21 {hW Cmple_pow_imm_pospos_base,aC2(aB2 Cmple_pow_imm_pospos_base)hP1 m62"<= " wT
#define U21 g9 Cmple_powpow_imm_base,aC2(aB2 Cmple_powpow_imm_base)aI"cmple_" hH oT3 a7
#define W21 dC Cmplt_pow_imm_negneg,aC2(aB2 Cmplt_pow_imm_negneg)dZ1 hV oV3 aK2
#define Y21 dC Cmplt_pow_imm_negpos,aC2(aB2 Cmplt_pow_imm_negpos)dZ1 hY oV3 aN2
#define S31 {hW Cmplt_pow_imm_posneg,aC2(aB2 Cmplt_pow_imm_posneg)dZ1 d2 oV3 m52
#define T31 {hW Cmplt_pow_imm_pospos,aC2(aB2 Cmplt_pow_imm_pospos)dZ1 d3 oV3 qQ3
#define U31 {hW Cmplt_pow_imm_pospos_base,aC2(aB2 Cmplt_pow_imm_pospos_base)dZ1 m62"< " wT
#define W31 g9 Cmplt_powpow_imm_base,aC2(aB2 Cmplt_powpow_imm_base)aI"cmplt_" hH oV3 a7
#define Y31 dC Cmpne_pow_imm_negneg,aC2(aB2 Cmpne_pow_imm_negneg)o01 hV gZ3 aK2
#define S41 dC Cmpne_pow_imm_negpos,aC2(aB2 Cmpne_pow_imm_negpos)o01 hY gZ3 aN2
#define T41 {hW Cmpne_pow_imm_posneg,aC2(aB2 Cmpne_pow_imm_posneg)o01 d2 gZ3 m52
#define U41 {hW Cmpne_pow_imm_pospos,aC2(aB2 Cmpne_pow_imm_pospos)o01 d3 gZ3 qQ3
#define W41 {hW Cmpne_pow_imm_pospos_base,aC2(aB2 Cmpne_pow_imm_pospos_base)o01 m62"!= " wT
#define Y41 g9 Cmpne_powpow_imm_base,aC2(aB2 Cmpne_powpow_imm_base)aI"cmpne_" hH dG2 a7
#define S51 dC Cmpzz_pow_imm_negneg,aC2(aB2 Cmpzz_pow_imm_negneg)q01"_imm_negneg" dT h11 oV3 gC3 aE h11 oT3 gC3 aG h11" > " gC3 aC gL",-3) >= -0.015625" wI h11 gZ3"-0.015625" wZ1",-3) = " aK2
#define T51 dC Cmpzz_pow_imm_negpos,aC2(aB2 Cmpzz_pow_imm_negpos)q01"_imm_negpos" dT h21 oV3 hQ3 aE h21 oT3 hQ3 aG h21" > " hQ3 aC gL",-2) >= 0.0625" wI h21 gZ3"0.0625" wZ1",-2) = " aN2
#define U51 {hW Cmpzz_pow_imm_posneg,aC2(aB2 Cmpzz_pow_imm_posneg)q01"_imm_posneg" dT d71 oV3 oD3 aE d71 oT3 oD3 aG d71" > " oD3 aC gL",3) >= -125" wI d71 gZ3"-125" wZ1",3) = " m52
#define W51 {hW Cmpzz_pow_imm_pospos,aC2(aB2 Cmpzz_pow_imm_pospos)q01"_imm_pospos" dT d81" < 25)" aE d81" <= 25)" aG d81" > 25)" aC gL",2) >= 25" wI d81 gZ3"25" wZ1",2) = " qQ3
#define Y51 {hW Cmpzz_pow_imm_pospos_base,aC2(aB2 Cmpzz_pow_imm_pospos_base)q01"_imm_pospos_base" dT oU3"< " mW aE oU3"<= " mW aG oU3"> " mW aC qD3">= " mW hD1 oU3"!= " mW d7 qD3"= " wT
#define S61 g9 Cmpzz_powpow_imm_base,aC2(aB2 Cmpzz_powpow_imm_base)aI"cmpzz_powpow_imm_base" dT wZ2 oV3 qS1 aE wZ2 oT3 qS1 aG wZ2" > " qS1 aC qB1 dF2 qS1 hD1 wZ2 dG2 qS1 d7 qB1" = " a7
#define T61 {2 mG1 hS Expexp_a,aC2(aB2 Expexp_a)aI oD2"p_a","exp(x*2 + y*3" gO2
#define U61 {3 mG1 hS Expexp_b,aC2(aB2 Expexp_b)aJ oD2"p_b",aR" * exp(y+z" gO2
#define W61 {3 mG1 hS Expexp_c,aC2(aB2 Expexp_c)aJ oD2"p_c","exp(x + y*z" gO2
#define Y61 {2,-4,4,hS If_extract_sin,aC2(aB2 If_extract_sin)aI dE1"tract_sin",dZ3"sin(y), " qR3
#define S71 mT1 If_join_add,aC2(aB2 If_join_add)aI"if_join_add",hV2"+" o21
#define T71 mT1 If_join_and,aC2(aB2 If_join_and)aI"if_join_and",hV2"&" o21
#define U71 mT1 If_join_max,aC2(aB2 If_join_max)aI"if_join_max","max(" o1 dE", " dO3")))"},
#define W71 mT1 If_join_min,aC2(aB2 If_join_min)aI"if_join_min","min(" o1 dE", " dO3")))"},
#define Y71 mT1 If_join_mul,aC2(aB2 If_join_mul)aI"if_join_mul",hV2"*" o21
#define S81 mT1 If_join_or,aC2(aB2 If_join_or)aI"if_join_or",o1 dE" | " dO3"))"},
#define T81 wP1 Ifabsnot,aC2(aB2 Ifabsnot)aJ"ifabsnot","if(!(sin(x)+1.2), y,z" gO2
#define U81 wP1 Ifconst,aC2(aB2 Ifconst)aJ"ifconst","if(1, x,y" o42" if(0,z,y" gO2
#define W81 {4 mP1 Ififconst,aC2(aB2 Ififconst)LNG_ONLY(0)"w," aP"ififconst","if(" o1",1,y),z,w" o42" if(if(w,z,0)," h22
#define Y81 mO1 Ifnot,aC2(aB2 Ifnot)aJ"ifnot","if(!x, y,z" gO2
#define S91 {oE3 Muland2,aC2(aB2 Muland2)aI"muland2",hR3},
#define T91 wP1 Muland2plus,aC2(aB2 Muland2plus)aJ"muland2plus",hR3" * z"},
#define U91 wP1 Muland3,aC2(aB2 Muland3)aJ"muland3",hR3" * !!z"},
#define W91 {oE3 Mulandlt,aC2(aB2 Mulandlt)aI"mulandlt",hC2" (y<0" gO2
#define Y91 {2 mR1,mQ1 q7 Mulimmlog,aC2(aB2 Mulimmlog)aI"mulimmlog","log(if(1,5,0)*x*" oS2
#define SA1 {oE3 Mulnor2,aC2(aB2 Mulnor2)aI"mulnor2",hS3},
#define TA1 wP1 Mulnor2plus,aC2(aB2 Mulnor2plus)aJ"mulnor2plus",hS3" * z"},
#define UA1 wP1 Mulnor3,aC2(aB2 Mulnor3)aJ"mulnor3",hS3" * !z"},
#define WA1 oA1 Negceil,aC2(aB2 Negceil)gR"negceil","ceil(x*(abs(x)-abs(x)-1))"},
#define YA1 oA1 Negcos,aC2(aB2 Negcos)gR"negcos","cos" qC1
#define SB1 oA1 Negcosh,aC2(aB2 Negcosh)gR"negcosh","cosh" qC1
#define TB1 oA1 Negfloor,aC2(aB2 Negfloor)gR"negfloor","floor(x*(abs(x)-abs(x)-1))"},
#define UB1 oA1 Negsin,aC2(aB2 Negsin)gR"negsin","sin(x*if(1,-1,0))"},
#define WB1 oA1 Negsinh,aC2(aB2 Negsinh)gR"neg" gK2,gK2 qC1
#define YB1 mX1 Posnot,aC2(aB2 Posnot)gR"posnot","!(sin(x) + 1.2" gO2
#define SC1 mX1 Posnotnot,aC2(aB2 Posnotnot)gR"posnotnot","!!(sin(x) + 1.2" gO2
#define TC1 {mQ1 mQ1 q7 Powimmaddimmlog,aC2(aB2 Powimmaddimmlog)w11"immaddimmlog","pow(5, log(x)+1" gO2
#define UC1 {mQ1 2 mR1,q7 Powimmlog,aC2(aB2 Powimmlog)w11"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define WC1 {d51 Powmulimm_fnen,aC2(aB2 Powmulimm_fnen)qA g61"mulimm_fnen" h51"^(-8" gO2
#define YC1 {2,qJ2 Powmulimm_fnep,aC2(aB2 Powmulimm_fnep)qA g61"mulimm_fnep" h51"^(4" gO2
#define SD1 {1,-3,-1,hS Powmulimm_fnfn,aC2(aB2 Powmulimm_fnfn)w11"mulimm_fnfn","((-5.1)*x)^(-7.1" gO2
#define TD1 {2,qJ2 Powmulimm_fnfp,aC2(aB2 Powmulimm_fnfp)qA g61"mulimm_fnfp" h51"^7.1"},
#define UD1 {2,qJ2 Powmulimm_fpfp,aC2(aB2 Powmulimm_fpfp)qA g61"mulimm_fpfp","(5.1*x*y)^7.1"},
#define WD1 mX1 Sub1cos2,aC2(aB2 Sub1cos2)gR"sub1cos2","1-cos(x)^2"},
#define YD1 mX1 Sub1sin2,aC2(aB2 Sub1sin2)gR"sub1sin2","1-" wQ1"^2"},
#define SE1 {1,N(-9.42477796076937971538793014983850865259),N(9.42477796076937971538793014983850865259),N(0.785398163397448309615660845819875721049292349),q7 Trig_modulo,aC2(aB2 Trig_modulo)gR"trig_modulo","cos(x+pi" q81"2/3" q81"5/2" q81"6/2" q81 hD2 o13" " hH1")" hW2"2/3)" hW2"5/2)" hW2"6/2)" hW2 hD2 o13" cos(x-pi)" g41"2/3)" g41"5/2)" g41"6/2)" g41 hD2"  sin(x-pi)" h61"2/3)" h61"5/2)" h61"6/2)" h61"7/2" gO2
#define TE1 {1,-3,3 mR1,q7 Trunc_from_if,aC2(aB2 Trunc_from_if)gR"trunc_from_if",o1">0,  " gI3 qM2">=0, " gI3 qM2"<0,  " gD3 qM2"<=0, " gD3 w21">0,  " gD3 w21">=0, " gD3 w21"<0,  " gI3" 10*" o1"<=0, floor(x),ceil" hF1
#define UE1 {1,N(-0.7),N(0.7),N(0.28),hI t5,aC2(aG2 t5)qA,oK"5","sub(sin(x)+csc(x),cos" hF1
#define WE1 {oB3 N(.25),hI t42,aC2(aG2 t42)qA",y",oK"42","sqrt(x*x) + 1.5*((y*y)^.25" o42" hypot(x,y" gO2
#define YE1 {1,-100,-1,N(.5),hI t51,aC2(aG2 t51)qA,oK"51","log" wM1
#define SF1 {1,N(.05),1,N(.01),hI t57,aC2(aG2 t57)qA,oK"57","cosh(a" gK2 hF1
#define TF1 {2 mG1 N(1.2),hI t59,aC2(aG2 t59)qA",y",oK"59","cosh(x^2" o42" tanh(y^2" gO2
#define UF1 wJ2 N(.25)h8 t1,aC2(aH2 t1)oF2"1","x*4/2 + (1+(2+3)) + x*x+x+1+2+3*4+5*6*\n7-8*9"},
#define WF1 wJ2 hE2 t2,aC2(aH2 t2)oF2"2","2 * x+ sin ( x ) / .5 + 2-sin(x)*sin(x)"},
#define YF1 {3,-7,7,oJ2 t3,aC2(aH2 t3)wN2"3","(x=y & y=x)+  1+2-3.1*4e2/.5 + x*x+y*y+z*z  + (x&x) + (y|y" gO2
#define SG1 {2,-10,10,oJ2 t4,aC2(aH2 t4)gP2"4","( ((( ( x-y) -( ((y) *2) -3)) )* 4))+sin(x)*cos(y)-cos(x)*sin(" oS2
#define TG1 wT2 8,hG2 t5,aC2(aH2 t5)LNG_ONLY(0)"__A5_x08,o__5_0AB_",oZ"5","__A5_x08^o__5_0AB_"},
#define UG1 wU2 N(.01)h8 t7,aC2(aH2 t7)oF2"7","cos(x)*sin(1-x)*(1-cos(x/2)*sin(x*5))"},
#define WG1 {2,-8,8,oE2 t8,aC2(aH2 t8)gP2"8",hT2"(x,y)+max(x,y" gO2
#define YG1 {3,1,15,N(.7)h8 t9,aC2(aH2 t9)wN2"9","1.5+x*y-2+4/8+z+z+z+z+x/(y*z" gO2
#define SH1 {3,1,4,N(.3)h8 t10,aC2(aH2 t10)wN2"10","1+sin(cos(max(1+2+3+4+5, x+y+z)))+2"},
#define TH1 {3,1,19,N(.8)h8 t11,aC2(aH2 t11)wN2"11","-(-(-(-(-x))-x))+y*1+log(1.1^z" gO2
#define UH1 {1,1,2000,oJ2 t12,aC2(aH2 t12)oF2"12","1/log(10^((3-2)/log(x)))"},
#define WH1 {2,-30,30,oJ2 t13,aC2(aH2 t13)gP2"13","x^3 * x^4 + y^3 * y^5"},
#define YH1 {1,-50,50,hE2 t14,aC2(aH2 t14)oF2"14","x*pi + sin(2*pi" o42" CONST"},
#define SI1 {2,N(1.1),6,N(.07)h8 t15,aC2(aH2 t15)gP2"15","x^y/log(y" o42" log(x)/log(y" o42" log(x^y" gO2
#define TI1 {2,1,17,oE2 t18,aC2(aH2 t18)gP2"18","- ( - ( - ( - 5 ) ) ) * -x^ -y^-2"},
#define UI1 {2,-4,4,hE2 t22,aC2(aH2 t22)gP2"22","3.5doubled + 10*x tripled - sin(y)doubled" o33"100" wE1" doubled-y tripled)doubled + 5/2doubled + 1.1^x doubled +  1.1doubled^x doubled"},
#define WI1 wJ2 hE2 t23,aC2(aH2 t23)oF2"23","(x/(2*acos(0)))*180"},
#define YI1 {3,1,3,oE2 t25,aC2(aH2 t25)LNG_ONLY(0)"a,b,c",oZ"25","a^b^c + a^-2 * (-b^2" o42" (-b^-c" gO2
#define SJ1 {1,-100,100,N(.1),true,aH2 t26_deg,aC2(aH2 t26_deg)oF2"26_deg",oL2" cos(x*1.5" o42" asin(x/110" o42" acos(x/120" gO2
#define TJ1 wT2 N(.9),N(.025)h8 t27,aC2(aH2 t27)gP2"27","abs(x)+acos(x)+asin(x)+atan(x)+" hT2"(x,y)+ceil(x)+cos(x)+cosh(x)+cot(x)+csc" qS2" " qH2",y" gO2
#define UJ1 wT2 N(.9),N(.025)h8 t28,aC2(aH2 t28)gP2"28","exp(x)+floor(x)+int(x)+log(x)+log10(x)+max(x,y)+min(x,y)+sec(x)+sin(x)+sinh(x)+sqrt(x)+tan(x)+tanh(x)+ceil(y)+trunc(" oS2
#define WJ1 {2,3,10,h7 t30,aC2(aH2 t30)gP2"30","x - y*1 + (x%y" o42" x / (y^1.1" o42" 2^3 + 5%3 + x^(y^0" o42" x^0.5"},
#define YJ1 {3,N(.1),4,N(.35)h8 t31,aC2(aH2 t31)wN2"31","x - (y*(y*(y*-1))*1" o42" log(x*exp" mY1")^y) - log(x^y" gL3"exp" mY1")^log(x+6" o42" 10^" qN2"6" mZ1"y+6)*log(z+6" mZ1"10)) -" o13" exp" mY1")^" qN2"6)*y) - 5^" qN2"7" mZ1"5)) + " aB1"^3 * " aB1"^2 /  " aB1"^4"},
#define SK1 {3,1,2,N(.05)h8 t32,aC2(aH2 t32)wN2"32","x" mO"+y/y-min(3,4)-x-max(4,3)+max(3,4)-min(4,3)+0+(z*1)" mO"+(x-2+2)+(x*0.5*2)+y*0" o23"+min(min(min(4.0,x),1.0),min(x,min(min(y,4.0),z)))" mO"+max(max(max(4.0,x),1.0)" w31"x(max(y,4.0),z)))" mO"+(abs(1)+acos" mY1")+asin(1.0)+atan" mY1")+ceil(1.1)+cos(0.0)" aM2"+cosh(0.0)+floor(1.1)+log" mY1")+sin(0.0)+sinh(0.0)+tan" mY1")" aM2"+tanh" mY1")+" hT2"(1.0,1.0))" mO"+(x-(y-z))" mO"+(x+y" o72"y" gR2"max(x" w31"x(x,max(x,x))))*-1.0" o23"+(z-z" gR2"1/sin(x/" oI2" 1/cos(y/" oI2" 1/tan(z/5" gR2"log10(cot(z/" oI2" csc(y/" oI2" sec(x/5))" mO"+log(30+x)*log(40+y" mZ1"50+z)" mO"+sin(x/57.295779513082320877" gR2"asin(x/10)*57.295779513082320877" o23"+floor(-x) + 1/ceil(x)" mO"+sqrt(5 * 0.2) +(-" hF2 hF2"x+-" aN1
#define TK1 {2 mG1 hE2 t33,aC2(aH2 t33)gP2"33","sin(sqrt(10-x*x+y*y))+cos(sqrt(15-x*x-y*y))+sin(x*x+y*" oS2
#define UK1 wU2 hE2 t37,aC2(aH2 t37)oF2"37","5 + 7.5*8 / 3 - 2^4*2 + 7%2+4 + x"},
#define WK1 {3,N(-.9),N(.9),hE2 t38,aC2(aH2 t38)wN2"38",a92 qS2" 1.5*" oB2"(y+3" o42" 2.5*atanh(z" gO2
#define YK1 {3,N(-1.3),N(1.3),hG2 t39,aC2(aH2 t39)wN2"39","sin(x+cos(y*1.5))-cos(x+sin(y*1.5))+z*z*z*sin(z*z*z-x*x-y*y)-" o13" cos(y*1.5)*sin(x+cos(y*1.5))+x*y*z+x*y*2.5+x*y*z*cos(x)+x*y*cos(x)+x*z*cos(x)+  y*z*2.5+(x*y*z*cos(x)-x*y*z-y*cos(x)-x*z*y+x*y+x*z-cos(x)*x)"},
#define SL1 {3,N(-1.3),N(1.3),N(.075)h8 t40,aC2(aH2 t40)wN2"40","(x+x+x+x+x+x+x+x+x+x+x+" gO1")*" o13" (x+x+x+x+x+x+x+x+x+x+x+" gO1")+" oK2"*(x+x+x+x+x+x+x+x+x+x+x+" gO1")-" o13" x*y*(x+x+x+x+x+x+x+x+x+x+x+" gO1")+  x*(x+x+x+x+x+x+x+x+x+x+x+" gO1 gO2
#define TL1 {3 mG1 hG2 t41,aC2(aH2 t41)wN2"41","x*3+x*y+x*z+x*sin(y*z) -" o13" " hH2"4" o33 q91"))*x" o33 hH2"y +  " hH2"z"},
#define UL1 {1,-100,100,N(.03)h8 t43,aC2(aH2 t43)oF2"43","log(x*x)+abs(" dJ2"abs(x)+1))"},
#define WL1 {1,0,100,N(.125)h8 t44,aC2(aH2 t44)oF2"44","(x^2" aC1"8" gL3"1.1" wE1"^3" aC1"7" gL3"1.2" wE1"^4" aC1"6" gL3"1.3" wE1"^5" aC1 oI2 o13" 1.4" wE1"^6" aC1"6" gL3"1.5" wE1"^7" aC1"4" gL3"1.6" wE1"^8" aC1"3" gL3"1.7" wE1"^9" aC1"2" o42"  1.8*(sqrt(abs(-sqrt(x))^3))"},
#define YL1 wU2 N(.025)h8 t45,aC2(aH2 t45)oF2"45","(x^2" aC1"7" o42" 1.1" wE1"^4" aC1 oI2" 1.2" wE1"^6" aC1"3" gO2
#define SM1 {2,N(-.9),N(.9),hG2 t46,aC2(aH2 t46)gP2"46" mA1"floor(acos(x)+4)) + 1.1*abs(floor(acos(y)+1.5)) +  " oN1" < (acos(y)-10)) + 1.2*max(-4, acos(x)) + 1.3*min(9, acos(x)-9" gO2
#define TM1 {oB3 hE2 t47,aC2(aH2 t47)gP2"47","1.25*(exp(x)+" dJ2"-" w01" 1.5*(" dJ2"y)-exp(-y)) +  1.75*((" dJ2"-x)+exp(x))/2" o42" 2.0*((" dJ2"-x)-exp(x))/2" o42" 2.25*(cosh(y)+sinh(y))"},
#define UM1 {1,2,N(1e9),N(1.2e7)h8 t48,aC2(aH2 t48)oF2"48",gK2"((log(x)/5+1)*" oI2" 1.2*cosh((log(x)/log(2)+1)*log" wL" !(x | !(x/4))"},
#define WM1 {1,-100,100,N(.05)h8 t49,aC2(aH2 t49)oF2"49",hT2"(0, x) + (-4" wE1"-100))^3.3"},
#define YM1 wU2 oJ2 t52,aC2(aH2 t52)oF2"52","x + " mY1"+2.0+3.0+4.0-5.0-6.0-7.0-8.0)/3.0" o33"4.0*(1.0+sin(2.0)+cos(4.0*5.0+6.0)/2.0" o42" cos(0.5)*tan(0.6+0.2) -  1.1/log(2.1)*sqrt(3.3" o42" 2^3"},
#define SN1 {2,0,10,N(0.5)h8 t53,aC2(aH2 t53)gP2"53","(x&y" o42" 4*(int(x/10)|int(y/10)) + 8*((-!-!-x)+(!-!-!y)) + 16*(-------x + !!!!!!!y" gO2
#define TN1 {2,-10,100,oJ2 t54,aC2(aH2 t54)gP2"54","(x<y" dO2"<=y" dO2">y" dO2">=y)+" o13" (x=y" dO2"!=y)+(x&y" dO2"|y)+" o13" (!x)+(!!x)+" o13" !((x<y)&(x<3))+  !!(!(x>y)|(x>3))"},
#define UN1 {2,1,100,oJ2 t55,aC2(aH2 t55)gP2"55","(x^1.2 < 0" o42" (y^2.5 < 0" o42" 2*(x*x<0" o42" 3*(y^3<0" o42" 4" wE1"^4<0" gO2
#define WN1 {1,N(.25),100,N(.25)h8 t56,aC2(aH2 t56)oF2"56","1.75e21%x"},
#define YN1 {1,-3,3,N(0.2)h8 t59,aC2(aH2 t59)oF2"59","(cos(x) < sin(x))" o33"(cos(x)-sin(x))" o33"sub(sinh(x)-cosh(x), " gK2"(x)/cosh(x)) +  sqrt(cos(x)^2+sin(x)^2" gO2
#define SO1 {1,N(1e-6),dL1 Log,aC2(aJ2 Log)qO"/log",aH1
#define TO1 gD Abscos,aC2(aE2 Abscos)qZ"abscos","cos(abs" hF1
#define UO1 gD Abscosh,aC2(aE2 Abscosh)qZ"abscosh","cosh(abs" hF1
#define WO1 a62 Abseq0,aC2(aE2 Abseq0)LNG_ONLY(aE2 Abseq0)dT1"abseq0",oL1"=0" o42" (0=abs" hF1
#define YO1 {1,N(0.001),N(0.9),N(0.01)qL Absevenconstpow,aC2(aE2 Absevenconstpow)qZ"absevenconstpow",hY3" ^ 1506"},
#define SP1 {2,N(0.001),N(0.9),N(0.01)qL Absmulevenconstpow,aC2(aE2 Absmulevenconstpow)dI2"absmulevenconstpow","(abs(x)*y) ^ 1506"},
#define TP1 a62 oF3,aC2(aE2 oF3)LNG_ONLY(aE2 oF3)dT1"absneq0",oL1"=0" o42" (0=abs" hF1
#define UP1 a62 Add,aC2(aE2 Add)LNG_ONLY(aE2 Add)dT1"add","5+3+x"},
#define WP1 a62 Add0,aC2(aE2 Add0)LNG_ONLY(aE2 Add0)dT1"add0","x+0+x"},
#define YP1 a62 And,aC2(aE2 And)LNG_ONLY(aE2 And)dT1"and","(5&3" qP2"5&0)+(0&5)+(0&0" gO2
#define SQ1 wR Cmp_acos,aC2(aE2 Cmp_acos)qZ"cmp_acos","1" o7"=acos" dP2 oK2 o7"<acos" dP2 a02 o7"<=acos" dP2 d31 o7">acos" dP2 d21 o7">=acos" dP2"  32" o7"!=acos(0.75))"},
#define TQ1 wR Cmp_acos_outrange,aC2(aE2 Cmp_acos_outrange)qZ"cmp_acos_outrange","1" o7"=2" o42 oK2 o7"<2" o42 a02 o7"<=2" o42 d31 o7">2" o42 d21 o7">=2" o42"  32" o7"!=2" gO2
#define UQ1 hR1 oG3,aC2(aE2 oG3)LNG_ONLY(aE2 oG3)dT1"cmp_add","1" aQ o41 aQ wM2 aQ hL1 aQ o51 aQ mE aQ d91
#define WQ1 wR Cmp_asin,aC2(aE2 Cmp_asin)qZ"cmp_asin","1" oN"=a" dM1 oK2 oN"<a" dM1 a02 oN"<=a" dM1 d31 oN">a" dM1 d21 oN">=a" dM1"  32" oN"!=asin(0.75))"},
#define YQ1 wR Cmp_asin_outrange,aC2(aE2 Cmp_asin_outrange)qZ"cmp_asin_outrange","1" oN"=2" o9"a" wQ1"<2" o42 a02 oN"<=2" o42 d31 oN">2" o42 d21 oN">=2" o42"  32" oN"!=2" gO2
#define SR1 mG Cmp_atan,aC2(aE2 Cmp_atan)qZ"cmp_atan","1" qD1"=atan" hI1 qD1"<atan" hJ1 qD1"<=atan" hI2 qD1">atan" hK2 qD1">=atan" hL2 qD1"!=atan" d11
#define TR1 mG Cmp_exp,aC2(aE2 Cmp_exp)qZ q02"p","1" gU1"=e" o03"2" gU1"<e" o03"4" gU1"<=e" o03" 8" gU1">e" o03"16" gU1">=e" o03"32" gU1"!=exp" d11
#define UR1 mG Cmp_exp2,aC2(aE2 Cmp_exp2)qZ q02"p2","1" q72"=exp2" wL" 2" q72"<exp2" wL" 4" q72"<=exp2" wL"  8" q72">exp2" wL" 16" q72">=exp2" wL" 32" q72"!=exp2" d11
#define WR1 mG Cmp_exp2_neg,aC2(aE2 Cmp_exp2_neg)qZ q02"p2_neg","1" q72"=-4" o42" 2" q72"<-4" o42" 4" q72"<=-4" g81 aS">-4" o42" 16" q72">=-4" hO2 q72"!=-4" gO2
#define YR1 mG Cmp_exp_neg,aC2(aE2 Cmp_exp_neg)qZ q02"p_neg","1" gU1"=-4" o42" 2" gU1"<-4" o42" 4" gU1"<=-4" g81 aR">-4" o42" 16" gU1">=-4" hO2 gU1"!=-4" gO2
#define SS1 qE1 Cmp_log2_nn,aC2(aE2 Cmp_log2_nn)qZ"cmp_log2_nn","1" q82 wG1 wU aT q82 a8 q82 a9 q82 aX q82 hK1
#define TS1 qE1 Cmp_log2_np,aC2(aE2 Cmp_log2_np)qZ"cmp_log2_np","1" q82"=log2" hI1 q82"<log2" hJ1 q82"<=log2" hI2 q82">log2" hK2 q82">=log2" hL2 q82"!=log2" d11
#define US1 mG Cmp_log2_pn,aC2(aE2 Cmp_log2_pn)qZ"cmp_log2_pn","1" wA wG1"log2(" hG1 aT wA a8 wA a9 wA aX wA hK1
#define WS1 mG Cmp_log2_pp,aC2(aE2 Cmp_log2_pp)qZ"cmp_log2_pp","1" wA"=log2" hI1 wA"<log2" hJ1 wA"<=log2" hI2 wA">log2" hK2 wA">=log2" hL2 wA"!=log2" d11
#define YS1 qE1 Cmp_log10_nn,aC2(aE2 Cmp_log10_nn)qZ"cmp_log10_nn","1*(" w0 wG1 w0 aT wL2 a8 wL2 a9 wL2 aX wL2 hK1
#define ST1 qE1 Cmp_log10_np,aC2(aE2 Cmp_log10_np)qZ"cmp_log10_np","1*(" w0"=log10" hI1 wL2"<log10" hJ1 wL2"<=log10" hI2 wL2">log10" hK2 wL2">=log10" hL2 wL2"!=log10" d11
#define TT1 mG Cmp_log10_pn,aC2(aE2 Cmp_log10_pn)qZ"cmp_log10_pn","1" dI"=-2" o42 oK2 dI aT dI a8 dI a9 dI aX dI hK1
#define UT1 mG Cmp_log10_pp,aC2(aE2 Cmp_log10_pp)qZ"cmp_log10_pp","1" dI"=log10(1)) +" oK2 dI"<log10(1))" o33"4" dI"<=log10(1)) +" d31 dI">log10(1)) +" d21 dI">=log10(1)) +  32" dI"!=log10(1))"},
#define WT1 qE1 Cmp_log_nn,aC2(aE2 Cmp_log_nn)qZ"cmp_log_nn","1" hZ1 wG1"log(x)" aT hZ1 a8 hZ1 a9 hZ1 aX hZ1 hK1
#define YT1 qE1 Cmp_log_np,aC2(aE2 Cmp_log_np)qZ"cmp_log_np","1" hZ1"=log" hI1 hZ1"<log" hJ1 hZ1"<=log" hI2 hZ1">log" hK2 hZ1">=log" hL2 hZ1"!=log" d11
#define SU1 mG Cmp_log_pn,aC2(aE2 Cmp_log_pn)qZ"cmp_log_pn","1" d01 wG1"log(" hG1 aT d01 a8 d01 a9 d01 aX d01 hK1
#define TU1 mG Cmp_log_pp,aC2(aE2 Cmp_log_pp)qZ"cmp_log_pp","1" d01"=log" hI1 d01"<log" hJ1 d01"<=log" hI2 d01">log" hK2 d01">=log" hL2 d01"!=log" d11
#define UU1 hR1 gV3,aC2(aE2 gV3)LNG_ONLY(aE2 gV3)dT1"cmp_mulneg","1" hM2 o41 hM2 wM2 hM2 hL1 hM2 o51 hM2 mE hM2 d91
#define WU1 hR1 gW3,aC2(aE2 gW3)LNG_ONLY(aE2 gW3)dT1"cmp_mulpos","1" hN2 o41 hN2 wM2 hN2 hL1 hN2 o51 hN2 mE hN2 d91
#define YU1 hR1 oH3,aC2(aE2 oH3)LNG_ONLY(aE2 oH3)dT1"cmp_neg","1" o61"=4" o42" 2" o61"<4" o42" 4" o61"<=4" o42"  8" o61">4" o42" 16" o61 mE o61 d91
#define SV1 hS1 Cmp_powx_n_n,aC2(aE2 Cmp_powx_n_n)h31"_n_n","1" g4"=" oT aU g4"<" oT aV g4"<=" oT aW g4">" oT mD g4">=" oT wI1 g4"!=" oT},
#define TV1 hS1 Cmp_powx_n_p,aC2(aE2 Cmp_powx_n_p)h31"_n_p","1" g4"=" oU aU g4"<" oU aV g4"<=" oU aW g4">" oU mD g4">=" oU wI1 g4"!=" oU},
#define UV1 h41 Cmp_powx_nn,aC2(aE2 Cmp_powx_nn)h31"_nn","1" g4 wJ1 g4 wK1 g4 o71 g4 wL1 g4">=-4" hO2 g4"!=-4" gO2
#define WV1 h41 Cmp_powx_np,aC2(aE2 Cmp_powx_np)h31"_np","1" g4 o41 g4 wM2 g4 hL1 g4 o51 g4 mE g4 d91
#define YV1 hS1 Cmp_powx_p_n,aC2(aE2 Cmp_powx_p_n)h31"_p_n","1" w1"=" oT aU w1"<" oT aV w1"<=" oT aW w1">" oT mD w1">=" oT wI1 w1"!=" oT},
#define SW1 hS1 Cmp_powx_p_p,aC2(aE2 Cmp_powx_p_p)h31"_p_p","1" w1"=" oU aU w1"<" oU aV w1"<=" oU aW w1">" oU mD w1">=" oU wI1 w1"!=" oU},
#define TW1 h41 Cmp_powx_pn,aC2(aE2 Cmp_powx_pn)h31"_pn","1" wN1 wJ1 wN1 wK1 wN1 o71 wN1 wL1 wN1">=-4" hO2 wN1"!=-4" gO2
#define UW1 h41 Cmp_powx_pp,aC2(aE2 Cmp_powx_pp)h31"_pp","1" wN1 o41 wN1 wM2 wN1 hL1 wN1 o51 wN1 mE wN1 d91
#define WW1 hJ Cmp_powy_n_n,aC2(aE2 Cmp_powy_n_n)o81"y_n_n","1" o91"=" gY3"2" o91"<" gY3"4" o91"<=" gY3"8" o91">" dW wV o91">=" dW" 32" o91"!=(x^-6.1))"},
#define YW1 hJ Cmp_powy_n_p,aC2(aE2 Cmp_powy_n_p)o81"y_n_p","1" o91"=(x" h03"2" o91"<(x" h03"4" o91"<=(x" h03"8" o91">(x" a1 wV o91">=(x" a1" 32" o91"!=(x^6.1))"},
#define SX1 hJ Cmp_powy_nn,aC2(aE2 Cmp_powy_nn)o81"y_nn","1" o91 wJ1 o91 wK1 o91 o71 o91 wL1 o91">=-4" hO2 o91"!=-4" gO2
#define TX1 hJ Cmp_powy_np,aC2(aE2 Cmp_powy_np)o81"y_np","1" o91 o41 o91 wM2 o91 hL1 o91 o51 o91 mE o91 d91
#define UX1 hJ Cmp_powy_p_n,aC2(aE2 Cmp_powy_p_n)o81"y_p_n","1" h4"=" gY3"2" h4"<" gY3"4" h4"<=" gY3"8" h4">" dW wV h4">=" dW" 32" h4"!=(x^-6.1))"},
#define WX1 hJ Cmp_powy_p_p,aC2(aE2 Cmp_powy_p_p)o81"y_p_p","1" h4"=(x" h03"2" h4"<(x" h03"4" h4"<=(x" h03"8" h4">(x" a1 wV h4">=(x" a1" 32" h4"!=(x^6.1))"},
#define YX1 hJ Cmp_powy_pn,aC2(aE2 Cmp_powy_pn)o81"y_pn","1" h4 wJ1 h4 wK1 h4 o71 h4 wL1 h4">=-4" hO2 h4"!=-4" gO2
#define SY1 hJ Cmp_powy_pp,aC2(aE2 Cmp_powy_pp)o81"y_pp","1" h4 o41 h4 wM2 h4 hL1 h4 o51 h4 mE h4 d91
#define TY1 mG Cmp_sinh,aC2(aE2 Cmp_sinh)oS gK2,"1" qF1"=" gK2 hI1 qF1"<" gK2 hJ1 qF1"<=" gK2 hI2 qF1">" gK2 hK2 qF1">=" gK2 hL2 qF1"!=" gK2 d11
#define UY1 hR1 oI3,aC2(aE2 oI3)LNG_ONLY(aE2 oI3)dT1"cmp_sqr","1" wW"=16" o42" 2" wW"<16" o42" 4" wW"<=16" o42"  8" wW">16" o42" 16" wW">=16" hO2 wW"!=16" gO2
#define WY1 hR1 gJ3,aC2(aE2 gJ3)LNG_ONLY(aE2 gJ3)dT1"cmp_sqr_neg","1" wW"=-16" o42" 2" wW"<-16" o42" 4" wW"<=-16" o42"  8" wW">-16" o42" -16" wW">=-16" hO2 wW"!=-16" gO2
#define YY1 {1,-4,4 mR1 qL Cmp_tanh,aC2(aE2 Cmp_tanh)qZ"cmp_tanh","1" oP"=tanh" dP2 oK2 oP"<tanh" dP2 a02 oP"<=tanh" dP2 d31 oP">tanh" dP2 d21 oP">=tanh" dP2"  32" oP"!=tanh(0.75))"},
#define SZ1 {1,-4,4 mR1 qL Cmp_tanh_outrange,aC2(aE2 Cmp_tanh_outrange)qZ"cmp_tanh_outrange","1" oP"=2" o9"tanh(x)<2" o42 a02 oP"<=2" o42 d31 oP">2" o42 d21 oP">=2" o42"  32" oP"!=2" gO2
#define TZ1 a62 Cmpeq,aC2(aE2 Cmpeq)LNG_ONLY(aE2 Cmpeq)dT1"cmpeq","(5=3" qP2"4=4" gO2
#define UZ1 a62 Cmpge,aC2(aE2 Cmpge)LNG_ONLY(aE2 Cmpge)dT1"cmpge","(5>=3" qP2"4>=8" gO2
#define WZ1 a62 Cmpgt,aC2(aE2 Cmpgt)LNG_ONLY(aE2 Cmpgt)dT1"cmpgt","(5>3" qP2"4>8" gO2
#define YZ1 a62 Cmple,aC2(aE2 Cmple)LNG_ONLY(aE2 Cmple)dT1"cmple","(5<3" qP2"4<8" gO2
#define Sa1 a62 Cmplt,aC2(aE2 Cmplt)LNG_ONLY(aE2 Cmplt)dT1"cmplt","(5<3)+x"},
#define Ta1 a62 Cmpne,aC2(aE2 Cmpne)LNG_ONLY(aE2 Cmpne)dT1"cmpne","(5!=3" qP2"4!=4" gO2
#define Ua1 a62 Div,aC2(aE2 Div)LNG_ONLY(aE2 Div)dT1"div","(5/4)+x"},
#define Wa1 a62 Div1,aC2(aE2 Div1)LNG_ONLY(aE2 Div1)dT1"div1","x/1+x"},
#define Ya1 a62 Divxx,aC2(aE2 Divxx)LNG_ONLY(aE2 Divxx)dT1"divxx","x+x/x+x"},
#define Sb1 a62 Eq0,aC2(aE2 Eq0)LNG_ONLY(aE2 Eq0)dT1"eq0","(x=0" o42" (0=" aN1
#define Tb1 a62 Eq1,aC2(aE2 Eq1)LNG_ONLY(aE2 Eq1)dT1"eq1","(!x=1" gO2
#define Ub1 {dM oJ3,aC2(aE2 oJ3)LNG_ONLY(aE2 oJ3)dT1"ge0_abs",oL1 h13 gM3 h23 gN3
#define Wb1 wR Ge0_neg,aC2(aE2 Ge0_neg)qZ"ge0_neg" w51 h13 w2 h23 qR3
#define Yb1 wR Ge0_pos,aC2(aE2 Ge0_pos)qZ"ge0_pos",oN1 h13 qI3 h23 gE3
#define Sc1 {dM oK3,aC2(aE2 oK3)LNG_ONLY(aE2 oK3)dT1"ge1_abs",oL1 h33 gM3 h43 gN3
#define Tc1 wR Ge1_neg,aC2(aE2 Ge1_neg)qZ"ge1_neg" w51 h33 w2 h43 qR3
#define Uc1 wR Ge1_pos,aC2(aE2 Ge1_pos)qZ"ge1_pos",oN1 h33 qI3 h43 gE3
#define Wc1 wR Gehalf,aC2(aE2 Gehalf)qZ"gehalf","x>=0.5"},
#define Yc1 {dM oL3,aC2(aE2 oL3)LNG_ONLY(aE2 oL3)dT1"gt0_abs",oL1 hT3 gM3 hU3 gN3
#define Sd1 wR Gt0_neg,aC2(aE2 Gt0_neg)qZ"gt0_neg" w51 hT3 w2 hU3 qR3
#define Td1 wR Gt0_pos,aC2(aE2 Gt0_pos)qZ"gt0_pos",oN1 hT3 qI3 hU3 gE3
#define Ud1 {dM oM3,aC2(aE2 oM3)LNG_ONLY(aE2 oM3)dT1"gt1_abs",oL1 hV3 gM3 hW3 gN3
#define Wd1 wR Gt1_neg,aC2(aE2 Gt1_neg)qZ"gt1_neg" w51 hV3 w2 hW3 qR3
#define Yd1 wR Gt1_pos,aC2(aE2 Gt1_pos)qZ"gt1_pos",oN1 hV3 qI3 hW3 gE3
#define Se1 wR Gtminushalf,aC2(aE2 Gtminushalf)qZ"gtminushalf","x>-0.5"},
#define Te1 {1,wV2 Immsub,aC2(aE2 Immsub)LNG_ONLY(aE2 Immsub)dT1"immsub","x-5"},
#define Ue1 wR Leminushalf,aC2(aE2 Leminushalf)qZ"leminushalf","x<=-0.5"},
#define We1 {1,0 o8 Log2exp1,aC2(aE2 Log2exp1)qZ"log2exp1",dJ2"log2" hF1
#define Ye1 {1,-1,N(0.75)mR1 qL Log2exp2,aC2(aE2 Log2exp2)qZ"log2exp2","exp2(log2(acos(x)))"},
#define Sf1 {1,0 o8 Logexp1,aC2(aE2 Logexp1)qZ"logexp1",dJ2"log" hF1
#define Tf1 {1,-1,N(0.75)mR1 qL Logexp2,aC2(aE2 Logexp2)qZ"logexp2",dJ2"log(acos(x)))"},
#define Uf1 {1,-dG1 Logmul,aC2(aE2 Logmul)qZ"logmul","log(" hM1
#define Wf1 {1,-dG1 Logmul2,aC2(aE2 Logmul2)qZ"logmul2","log2(" hM1
#define Yf1 {1,-dG1 Logmul10,aC2(aE2 Logmul10)qZ"logmul10","log10(" hM1
#define Sg1 {dM Lt0,aC2(aE2 Lt0)LNG_ONLY(aE2 Lt0)dT1"lt0","sub" oL1"<0, x<0" gO2
#define Tg1 wR Lthalf,aC2(aE2 Lthalf)qZ"lthalf","x<0.5"},
#define Ug1 a62 Mod,aC2(aE2 Mod)LNG_ONLY(aE2 Mod)dT1"mod","(5%4)+x"},
#define Wg1 a62 Mul,aC2(aE2 Mul)LNG_ONLY(aE2 Mul)dT1"mul","(5*4)+x"},
#define Yg1 a62 Mul1,aC2(aE2 Mul1)LNG_ONLY(aE2 Mul1)dT1"mul1","x*1+x"},
#define Sh1 a62 Mul1b,aC2(aE2 Mul1b)qZ"mul1b",wO"0.2)*5)+x"},
#define Th1 {2,N(0.1),10,N(0.1)qL Mul_zero,aC2(aE2 Mul_zero)dI2"mul_zero","(x*y+1)+(sin(x)+sin(y))*log(x)*y*x*0"},
#define Uh1 a62 Mulneg,aC2(aE2 Mulneg)LNG_ONLY(aE2 Mulneg)dT1"mulneg","-" qT2
#define Wh1 a62 dP3,aC2(aE2 dP3)LNG_ONLY(aE2 dP3)dT1"multodiv","x/4+x"},
#define Yh1 {2,wV2 Negadd,aC2(aE2 Negadd)LNG_ONLY(aE2 Negadd)gI1"negadd","x+(-y" gO2
#define Si1 gD Negcos,aC2(aE2 Negcos)qZ"negcos","cos" wM1
#define Ti1 gD Negcosh,aC2(aE2 Negcosh)qZ"negcosh","cosh" wM1
#define Ui1 a62 Negmul,aC2(aE2 Negmul)LNG_ONLY(aE2 Negmul)dT1"negmul","(-x)*" gV2
#define Wi1 gD Negsin,aC2(aE2 Negsin)qZ"negsin","sin(-" aN1
#define Yi1 gD Negsinh,aC2(aE2 Negsinh)qZ"neg" gK2,gK2 wM1
#define Sj1 {2,wV2 Negsub,aC2(aE2 Negsub)LNG_ONLY(aE2 Negsub)gI1"negsub","x-(-y" gO2
#define Tj1 gD Negtan,aC2(aE2 Negtan)qZ"negtan","tan" wM1
#define Uj1 gD Negtanh,aC2(aE2 Negtanh)qZ"negtanh","tanh" wM1
#define Wj1 a62 Neq0,aC2(aE2 Neq0)LNG_ONLY(aE2 Neq0)dT1"neq0","(x!=0" o42" (0!=" aN1
#define Yj1 a62 Neq1,aC2(aE2 Neq1)LNG_ONLY(aE2 Neq1)dT1"neq1","(!x!=1" gO2
#define Sk1 a62 Not,aC2(aE2 Not)LNG_ONLY(aE2 Not)dT1"not","(!(3))+x"},
#define Tk1 a62 Or,aC2(aE2 Or)LNG_ONLY(aE2 Or)dT1"or","(5|3" qP2"5|0)+(0|5)+(0|0" gO2
#define Uk1 gD Sincos_cci,aC2(aE2 Sincos_cci)hP"cos_cci","cos" qS2" sec(x)"},
#define Wk1 gD Sincos_cic,aC2(aE2 Sincos_cic)hP"cos_cic","sec" qS2 w71
#define Yk1 gD Sincos_sc,aC2(aE2 Sincos_sc)hP"cos_sc",oL2 w71
#define Sl1 gD Sincos_sci,aC2(aE2 Sincos_sci)hP"cos_sci",oL2" sec(x)"},
#define Tl1 gD Sincos_sis,aC2(aE2 Sincos_sis)hP"cos_sis","csc" qS2" " wQ1},
#define Ul1 gD Sincos_ssi,aC2(aE2 Sincos_ssi)hP"cos_ssi",oL2" csc(x)"},
#define Wl1 gD Sincos_tan,aC2(aE2 Sincos_tan)hP"cos_tan",wQ1" /" w71
#define Yl1 gD Sincos_tit,aC2(aE2 Sincos_tit)hP"cos_tit","cot" qS2" tan(x)"},
#define Sm1 gD Sincos_tti,aC2(aE2 Sincos_tti)hP"cos_tti","tan" qS2" cot(x)"},
#define Tm1 a62 Sqreq0,aC2(aE2 Sqreq0)LNG_ONLY(aE2 Sqreq0)dT1"sqreq0","(x*x=0" o42" (0=x*x)"},
#define Um1 a62 oN3,aC2(aE2 oN3)LNG_ONLY(aE2 oN3)dT1"sqrneq0","(x*x=0" o42" (0=x*x)"},
#define Wm1 {1,0 o8 Sqrtsqr1,aC2(aE2 Sqrtsqr1)qZ"sqrtsqr1","sqrt(x)^2"},
#define Ym1 {1 mC Sqrtsqr2,aC2(aE2 Sqrtsqr2)qZ"sqrtsqr2","sqrt(acos(x))^2"},
#define Sn1 a62 Sub,aC2(aE2 Sub)LNG_ONLY(aE2 Sub)dT1"sub","5-3+x"},
#define Tn1 a62 Sub0,aC2(aE2 Sub0)LNG_ONLY(aE2 Sub0)dT1"sub0","x-0+x"},
#define Un1 {1,-3,3,1 qL Subxx,aC2(aE2 Subxx)LNG_ONLY(aE2 Subxx)dT1"subxx","x+(x-x)+x+(1-x+x)"},
#define Wn1 gD Xmulsinhneg,aC2(aE2 Xmulsinhneg)a2"mulsinhneg","-" gK2 qT2
#define Yn1 gD Xmulsinneg,aC2(aE2 Xmulsinneg)a2"mulsinneg","-sin(x*" q12
#define So1 gD Xmultanhneg,aC2(aE2 Xmultanhneg)a2"multanhneg","-tanh" qT2
#define To1 gD Xmultanneg,aC2(aE2 Xmultanneg)a2"multanneg","-tan" qT2
#define Uo1 {1,N(0.5),3,N(0.7)qL Xsqryfsqrhypot,aC2(aE2 Xsqryfsqrhypot)a2"sqryfsqrhypot","sqrt(log(x)^2+" wU"^2" gO2
#define Wo1 {2,N(0.5),3,N(0.7)qL Xsqrysqrhypot,aC2(aE2 Xsqrysqrhypot)dH2"/xsqrysqrhypot","sqrt(log(x)^2+y*" oS2
#define Yo1 {1 dH1 t1,aC2(aD2 t1)LNG_ONLY(aD2 t1)wQ2"1","(1/a" oN2
#define Sp1 {1 dH1 t2,aC2(aD2 t2)LNG_ONLY(aD2 t2)wQ2"2","5*a"},
#define Tp1 {1 dH1 t3,aC2(aD2 t3)LNG_ONLY(aD2 t3)wQ2"3","5/a"},
#define Up1 {2 dH1 t4,aC2(aD2 t4)LNG_ONLY(aD2 t4)hD"4","(a*5)*b"},
#define Wp1 {2 dH1 t5,aC2(aD2 t5)LNG_ONLY(aD2 t5)hD"5","(a*5)/b"},
#define Yp1 {2 dH1 t6,aC2(aD2 t6)LNG_ONLY(aD2 t6)hD"6","(1/a)*b"},
#define Sq1 {2 dH1 t7,aC2(aD2 t7)LNG_ONLY(aD2 t7)hD"7","(1/a)/b"},
#define Tq1 {2 dH1 t8,aC2(aD2 t8)LNG_ONLY(aD2 t8)hD"8" mA1"a)*(" hP2")*" q12
#define Uq1 {2 dH1 t9,aC2(aD2 t9)LNG_ONLY(aD2 t9)hD"9" mA1"a)/(" hP2")*" q12
#define Wq1 g6 t10,aC2(aD2 t10)LNG_ONLY(aD2 t10)hD"10" mA1"b)*(5/a" gO2
#define Yq1 g6 t11,aC2(aD2 t11)LNG_ONLY(aD2 t11)hD"11" mA1"b)/(50/a" gO2
#define Sr1 mH t12,aC2(aD2 t12)LNG_ONLY(aD2 t12)wQ2"12","(-a)+" gV2
#define Tr1 g6 t13,aC2(aD2 t13)LNG_ONLY(aD2 t13)hD"13","5+(a*b" gO2
#define Ur1 g6 t14,aC2(aD2 t14)LNG_ONLY(aD2 t14)hD"14","5-(a*b" gO2
#define Wr1 g6 t15,aC2(aD2 t15)LNG_ONLY(aD2 t15)hD"15","(a+5)+" hP2 gO2
#define Yr1 g6 t16,aC2(aD2 t16)LNG_ONLY(aD2 t16)hD"16","(a+5)-abs(b" gO2
#define Ss1 g6 t17,aC2(aD2 t17)LNG_ONLY(aD2 t17)hD"17","(-a)+" hP2 gO2
#define Ts1 g6 t18,aC2(aD2 t18)LNG_ONLY(aD2 t18)hD"18","(-a)-abs(b" gO2
#define Us1 g6 t19,aC2(aD2 t19)LNG_ONLY(aD2 t19)hD"19","b+(" oR2")+" q12
#define Ws1 g6 t20,aC2(aD2 t20)LNG_ONLY(aD2 t20)hD"20","b-(" oR2")+" q12
#define Ys1 g6 t21,aC2(aD2 t21)LNG_ONLY(aD2 t21)hD"21" mA1"b)+(5-a" gO2
#define St1 g6 t22,aC2(aD2 t22)LNG_ONLY(aD2 t22)hD"22" mA1"b)-(5-a" gO2
#define Tt1 g6 t23,aC2(aD2 t23)LNG_ONLY(aD2 t23)hD"23" qG1"b" oQ2
#define Ut1 g6 t24,aC2(aD2 t24)LNG_ONLY(aD2 t24)hD"24" qG1"5" oQ2
#define Wt1 g6 t25,aC2(aD2 t25)LNG_ONLY(aD2 t25)hD"25" qG1"5" oM2
#define Yt1 g6 t26,aC2(aD2 t26)LNG_ONLY(aD2 t26)hD"26","(" o13"abs(a)/b" oQ2
#define Su1 g6 t27,aC2(aD2 t27)LNG_ONLY(aD2 t27)hD"27","(" o13"abs(a)/b" oM2
#define Tu1 g6 t28,aC2(aD2 t28)LNG_ONLY(aD2 t28)hD"28","((-a)/b" oN2
#define Uu1 g6 t29,aC2(aD2 t29)LNG_ONLY(aD2 t29)hD"29","(5/b" oM2
#define Wu1 mH t30,aC2(aD2 t30)LNG_ONLY(aD2 t30)"b",qE"30","(7/b" oN2
#define Yu1 g6 t31,aC2(aD2 t31)LNG_ONLY(aD2 t31)hD"31","b*(7/-a" gO2
#define Sv1 g6 t32,aC2(aD2 t32)LNG_ONLY(aD2 t32)hD"32","(5-b)-a"},
#define Tv1 g6 t33,aC2(aD2 t33)LNG_ONLY(aD2 t33)hD"33","(5-b)+a"},
#define Uv1 g6 t34,aC2(aD2 t34)LNG_ONLY(aD2 t34)hD"34","((a+7)-b)+" gV2
#define Wv1 g6 t35,aC2(aD2 t35)LNG_ONLY(aD2 t35)hD"35","((-a)-b)+" gV2
#define Yv1 mH t36,aC2(aD2 t36)LNG_ONLY(aD2 t36)wQ2"36","(7-abs(a))+" gV2
#define Sw1 g6 t37,aC2(aD2 t37)LNG_ONLY(aD2 t37)hD"37","((7-b)+a)+" gV2
#define Tw1 g6 t38,aC2(aD2 t38)LNG_ONLY(aD2 t38)hD"38","((5*b+" oR2"))<0)*1 + ((" hP2"))<0)*2"},
#define Uw1 mH t39,aC2(aD2 t39)LNG_ONLY(aD2 t39)wQ2"39","(a+7" oN2
#define Ww1 g6 t40,aC2(aD2 t40)LNG_ONLY(aD2 t40)hD"40","(b+(a*7))*" gV2
#define Yw1 g6 t41,aC2(aD2 t41)LNG_ONLY(aD2 t41)hD"41","(b-(a*7))*" gV2
#define Sx1 mH t42,aC2(aD2 t42)LNG_ONLY(aD2 t42)wQ2"42","(a+7)+" gV2
#define Tx1 mH t43,aC2(aD2 t43)LNG_ONLY(aD2 t43)wQ2"43","(a*7" oN2
#define Ux1 g91 Abseq0,aC2(aB2 Abseq0)LNG_ONLY(aB2 Abseq0)gN1"abseq0",oL1"=if" wD2")) + (if" wD2")=abs" hF1
#define Wx1 g91 oF3,aC2(aB2 oF3)LNG_ONLY(aB2 oF3)gN1"absneq0",oL1"=if" wD2")) + (if" wD2")=abs" hF1
#define Yx1 g91 Eq0,aC2(aB2 Eq0)LNG_ONLY(aB2 Eq0)gN1"eq0","(x=if(" hQ2" + (if(" hR2"=" aN1
#define Sy1 g91 Eq1,aC2(aB2 Eq1)LNG_ONLY(aB2 Eq1)gN1"eq1","(!x=if(" hS2},
#define Ty1 oA1 oJ3,aC2(aB2 oJ3)LNG_ONLY(aB2 oJ3)gN1"ge0_abs",oL1" >= if(" hQ2 qT1 hR2 oT3 qJ3"<= if(" gC1 gD1 hR2" >= " gN3
#define Uy1 oA1 oK3,aC2(aB2 oK3)LNG_ONLY(aB2 oK3)gN1"ge1_abs",oL1" >= if(" hS2 qT1 dQ3"<= " qJ3"<= if(" hN1 gD1 dQ3">= " gN3
#define Wy1 {1 dN N(0.25),q7 Gehalf,aC2(aB2 Gehalf)gR"gehalf","x>=if(1,0.5,0" gO2
#define Yy1 oA1 oL3,aC2(aB2 oL3)LNG_ONLY(aB2 oL3)gN1"gt0_abs",oL1" > if(" hQ2 qT1 hR2 oV3 qJ3"< if(" gC1 gD1 hR2" > " gN3
#define Sz1 oA1 oM3,aC2(aB2 oM3)LNG_ONLY(aB2 oM3)gN1"gt1_abs",oL1" > if(" hS2 qT1 dQ3"< " qJ3"< if(" hN1 gD1 dQ3"> " gN3
#define Tz1 {1 dN N(0.25),q7 Lthalf,aC2(aB2 Lthalf)gR"lthalf","x<if(1,0.5,0" gO2
#define Uz1 g91 Neq0,aC2(aB2 Neq0)LNG_ONLY(aB2 Neq0)gN1"neq0","(x!=if(" hQ2" + (if(" hR2"!=" aN1
#define Wz1 g91 Neq1,aC2(aB2 Neq1)LNG_ONLY(aB2 Neq1)gN1"neq1","(!x!=if(" hS2},
#define Yz1 {1,-9,9,1,hI t7,aC2(aG2 t7)LNG_ONLY(aG2 t7)wE2"7","x>7 & x<2"},
#define S_1 {2,-9,9,1,hI t8,aC2(aG2 t8)qA",y",oK"8",hT2"(-x,-y" o42" 10" oO2"(-x,y" o42" 20" oO2"(x,-y" o42" 30" oO2"(x,y" gO2
#define T_1 {1 oO3 t9a,aC2(aG2 t9a)LNG_ONLY(aG2 t9a)wE2"9a","a:=x;a*0"},
#define U_1 {2 oO3 t9b,aC2(aG2 t9b)LNG_ONLY(aG2 t9b)hU2"9b","sub(a,b" oP2
#define W_1 {2 oO3 t9c,aC2(aG2 t9c)LNG_ONLY(aG2 t9c)hU2"9c","psub(a,b" oP2
#define Y_1 {2 oO3 t9d,aC2(aG2 t9d)LNG_ONLY(aG2 t9d)hU2"9d","if(a,b*0,a*0" oP2
#define S02 {1,1,10,1,hI t10,aC2(aG2 t10)qA,oK"10","1/abs(x)<1"},
#define T02 {1,N(1e25),N(10e25),N(1e25),hI t11,aC2(aG2 t11)qA,oK"11","exp(x/5e+25" gO2
#define U02 {3,-3,3,2,hI t61,aC2(aG2 t61)LNG_ONLY(aG2 t61)gZ2 oK"61","5*x*y + -5*z"},
#define W02 {2,gN Add_cd,hA wQ"add_cd","x+y"},
#define Y02 {2,hJ2 Add_d,aC2(aF2 Add_d)wQ"add_d","x+y"},
#define S12 {3,gN Addsub_cd,hA qG2 g7"addsub_cd","x+y+x+x-z+x"},
#define T12 {3,hJ2 Addsub_d,aC2(aF2 Addsub_d)qG2 g7"addsub_d","x+y+x+x-z+x"},
#define U12 {2,gI And_d,aC2(aF2 And_d)wQ"and_d","x&y"},
#define W12 {2,gN Cmpeq_cd,hA wQ"cmpeq_cd","x=y"},
#define Y12 {2,gI Cmpeq_d,aC2(aF2 Cmpeq_d)wQ"cmpeq_d","x=y"},
#define S22 {2,gI Cmpge_d,aC2(aF2 Cmpge_d)wQ"cmpge_d","x>=y"},
#define T22 {2,gI Cmpgt_d,aC2(aF2 Cmpgt_d)wQ"cmpgt_d","x>y"},
#define U22 {2,gI Cmple_d,aC2(aF2 Cmple_d)wQ"cmple_d","x<=y"},
#define W22 {2,gI Cmplt_d,aC2(aF2 Cmplt_d)wQ"cmplt_d","x<y"},
#define Y22 {2,gN Cmpne_cd,hA wQ"cmpne_cd","x!=y"},
#define S32 {2,gI Cmpne_d,aC2(aF2 Cmpne_d)wQ"cmpne_d","x!=y"},
#define T32 {2,dL Div_d,aC2(aF2 Div_d)wQ"div_d","(x-0.25)/y"},
#define U32 {3,dL Divmul_d,aC2(aF2 Divmul_d)qG2 g7"divmul_d","x*y*x*x/z" wE1"-0.25" gO2
#define W32 {1,N(-7.0,0.0),N(6.0,0.0),N(0.6,0.0),qM Inv_d,aC2(aF2 Inv_d)qA,g7"inv_d","1/x"},
#define Y32 {2,N(-7.25,+3.625),N(7.25,-3.625),N(0.5,-0.25),qM Mul_cd,hA wQ"mul_cd","x*y"},
#define S42 {2,dL Mul_d,aC2(aF2 Mul_d)wQ"mul_d","x*y"},
#define T42 {1,gN Neg_cd,hA qA,g7"neg_cd","-x"},
#define U42 {1,hJ2 Neg_d,aC2(aF2 Neg_d)qA,g7"neg_d","-x"},
#define W42 {1,N(-1.25,0.0),N(1.25,0.0),N(0.25,0.0),qM Not_d,aC2(aF2 Not_d)qA,g7"not_d","!x"},
#define Y42 {1,N(-1.25,0.0),N(1.25,0.0),N(0.25,0.0),qM Notnot_d,aC2(aF2 Notnot_d)qA,g7"notnot_d","!!x"},
#define S52 {2,gI Or_d,aC2(aF2 Or_d)wQ"or_d","x|y"},
#define T52 {2,gN Sub_cd,hA wQ"sub_cd","x-y"},
#define U52 {2,hJ2 Sub_d,aC2(aF2 Sub_d)wQ"sub_d","x-y"},
#define W52 {1,N(-400.0,+200.0),N(400.0,-200.0),N(0.5,-0.25)dP Abs_cd qF"/abs_cd",hY3},
#define Y52 {1,gV Arg qF"/arg",aH1
#define S62 {1,gV Conj qF"/conj","conj(x)"},
#define T62 {1,gV Imag qF"/imag","imag(x)"},
#define U62 {1,gV Log,aC2(aJ2 Log)qO"/log",aH1
#define W62 {1,N(-4000.0,-0.5),N(4000.0,+0.5),N(0.3,+3.75e-05)dP Log_cd qF"/log_cd",aH1
#define Y62 {2,N(-4.0,0.0),aI1 qJ false qI Max,aC2(aJ2 Max)LNG_ONLY(aJ2 Max)"x" oJ"/max","max(x,y" gO2
#define S72 {2,N(-4.0,0.0),aI1 qJ false qI Min,aC2(aJ2 Min)LNG_ONLY(aJ2 Min)"x" oJ"/min","min(x,y" gO2
#define T72 {2,N(0.01,0.0),aI1,N(0.05,0.0)dP Polar,d82"/polar","polar(x,y" gO2
#define U72 {1,gV Real qF"/real","real(x)"},
#define W72 {1,N(-100000.0,0.0),N(100000.0,0.0),N(1000.0,0.0)dP Sqrt_cd qF"/sqrt_cd","sqrt(x)"},
#define Y72 {1,gX t1,aC2(aD2 t1)LNG_ONLY(aD2 t1)wQ2"1","(1/a" oN2
#define S82 {1,gX t2,aC2(aD2 t2)LNG_ONLY(aD2 t2)wQ2"2","5*a"},
#define T82 {1,gX t3,aC2(aD2 t3)LNG_ONLY(aD2 t3)wQ2"3","5/a"},
#define U82 {2,gX t4,aC2(aD2 t4)LNG_ONLY(aD2 t4)hD"4","(a*5)*b"},
#define W82 {2,gX t5,aC2(aD2 t5)LNG_ONLY(aD2 t5)hD"5","(a*5)/b"},
#define Y82 {2,gX t6,aC2(aD2 t6)LNG_ONLY(aD2 t6)hD"6","(1/a)*b"},
#define S92 {2,gX t7,aC2(aD2 t7)LNG_ONLY(aD2 t7)hD"7","(1/a)/b"},
#define T92 {2,gX t8,aC2(aD2 t8)LNG_ONLY(aD2 t8)hD"8" mA1"a)*(" hP2")*" q12
#define U92 {2,gX t9,aC2(aD2 t9)LNG_ONLY(aD2 t9)hD"9" mA1"a)/(" hP2")*" q12
#define W92 mK t10,aC2(aD2 t10)LNG_ONLY(aD2 t10)hD"10" mA1"b)*(5/a" gO2
#define Y92 mK t11,aC2(aD2 t11)LNG_ONLY(aD2 t11)hD"11" mA1"b)/(50/a" gO2
#define SA2 {1,qD t12,aC2(aD2 t12)LNG_ONLY(aD2 t12)wQ2"12","(-a)+" gV2
#define TA2 mK t13,aC2(aD2 t13)LNG_ONLY(aD2 t13)hD"13","5+(a*b" gO2
#define UA2 mK t14,aC2(aD2 t14)LNG_ONLY(aD2 t14)hD"14","5-(a*b" gO2
#define WA2 mK t15,aC2(aD2 t15)LNG_ONLY(aD2 t15)hD"15","(a+5)+" hP2 gO2
#define YA2 mK t16,aC2(aD2 t16)LNG_ONLY(aD2 t16)hD"16","(a+5)-abs(b" gO2
#define SB2 mK t17,aC2(aD2 t17)LNG_ONLY(aD2 t17)hD"17","(-a)+" hP2 gO2
#define TB2 mK t18,aC2(aD2 t18)LNG_ONLY(aD2 t18)hD"18","(-a)-abs(b" gO2
#define UB2 mK t19,aC2(aD2 t19)LNG_ONLY(aD2 t19)hD"19","b+(" oR2")+" q12
#define WB2 mK t20,aC2(aD2 t20)LNG_ONLY(aD2 t20)hD"20","b-(" oR2")+" q12
#define YB2 mK t21,aC2(aD2 t21)LNG_ONLY(aD2 t21)hD"21" mA1"b)+(5-a" gO2
#define SC2 mK t22,aC2(aD2 t22)LNG_ONLY(aD2 t22)hD"22" mA1"b)-(5-a" gO2
#define TC2 mK t23,aC2(aD2 t23)LNG_ONLY(aD2 t23)hD"23" qG1"b" oQ2
#define UC2 mK t24,aC2(aD2 t24)LNG_ONLY(aD2 t24)hD"24" qG1"5" oQ2
#define WC2 mK t25,aC2(aD2 t25)LNG_ONLY(aD2 t25)hD"25" qG1"5" oM2
#define YC2 mK t26,aC2(aD2 t26)LNG_ONLY(aD2 t26)hD"26","(" o13"abs(a)/b" oQ2
#define SD2 mK t27,aC2(aD2 t27)LNG_ONLY(aD2 t27)hD"27","(" o13"abs(a)/b" oM2
#define TD2 mK t28,aC2(aD2 t28)LNG_ONLY(aD2 t28)hD"28","((-a)/b" oN2
#define UD2 mK t29,aC2(aD2 t29)LNG_ONLY(aD2 t29)hD"29","(5/b" oM2
#define WD2 {1,qD t30,aC2(aD2 t30)LNG_ONLY(aD2 t30)"b",qE"30","(7/b" oN2
#define YD2 mK t31,aC2(aD2 t31)LNG_ONLY(aD2 t31)hD"31","b*(7/-a" gO2
#define SE2 mK t32,aC2(aD2 t32)LNG_ONLY(aD2 t32)hD"32","(5-b)-a"},
#define TE2 mK t33,aC2(aD2 t33)LNG_ONLY(aD2 t33)hD"33","(5-b)+a"},
#define UE2 mK t34,aC2(aD2 t34)LNG_ONLY(aD2 t34)hD"34","((a+7)-b)+" gV2
#define WE2 mK t35,aC2(aD2 t35)LNG_ONLY(aD2 t35)hD"35","((-a)-b)+" gV2
#define YE2 {1,qD t36,aC2(aD2 t36)LNG_ONLY(aD2 t36)wQ2"36","(7-abs(a))+" gV2
#define SF2 mK t37,aC2(aD2 t37)LNG_ONLY(aD2 t37)hD"37","((7-b)+a)+" gV2
#define TF2 mK t38,aC2(aD2 t38)LNG_ONLY(aD2 t38)hD"38","((5*b+" oR2"))<0)*1 + ((" hP2"))<0)*2"},
#define UF2 {1,qD t39,aC2(aD2 t39)LNG_ONLY(aD2 t39)wQ2"39","(a+7" oN2
#define WF2 mK t40,aC2(aD2 t40)LNG_ONLY(aD2 t40)hD"40","(b+(a*7))*" gV2
#define YF2 mK t41,aC2(aD2 t41)LNG_ONLY(aD2 t41)hD"41","(b-(a*7))*" gV2
#define SG2 {1,qD t42,aC2(aD2 t42)LNG_ONLY(aD2 t42)wQ2"42","(a+7)+" gV2
#define TG2 {1,qD t43,aC2(aD2 t43)LNG_ONLY(aD2 t43)wQ2"43","(a*7" oN2
#define UG2 dB Abscos,aC2(aB2 Abscos)gR"abscos","cos(sqrt(" dX1"))) + sqrt(" dX1"))"},
#define WG2 dB Abscosh,aC2(aB2 Abscosh)gR"abscosh","cosh(sqrt(" dX1"))) + sqrt(" dX1"))"},
#define YG2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 Abseq0,aC2(aB2 Abseq0)LNG_ONLY(aB2 Abseq0)gN1"abseq0",oL1"=if" wD2")) + (if" wD2")=abs" hF1
#define SH2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 oF3,aC2(aB2 oF3)LNG_ONLY(aB2 oF3)gN1"absneq0",oL1"=if" wD2")) + (if" wD2")=abs" hF1
#define TH2 {1,N(-5.0,0.0),N(5.0,0.0)qJ q7 o43,aC2(aB2 o43)LNG_ONLY(aB2 o43)gN1"absnzge","sub" oL1" >= if" wF2"), " hY3 dF2"(if(1,1,0)-1))"},
#define UH2 {1,N(-5.0,0.0),N(5.0,0.0)qJ q7 o53,aC2(aB2 o53)LNG_ONLY(aB2 o53)gN1"absnzlt","sub" oL1" < if" wF2"), " hY3" < (if(1,1,0)-1))"},
#define WH2 {1,N(-1.0,0.0)qJ N(0.1,0.0),q7 Acoscos,aC2(aB2 Acoscos)gR"acoscos","cos(acos" hF1
#define YH2 {1,N(1.7,0.0),N(3.7,0.0),N(0.28,0.0),q7 Acoshsinh,aC2(aB2 Acoshsinh)gR oB2 gK2,gK2"(if(1,acosh(x),0))"},
#define SI2 {hT gF3,aC2(aB2 gF3)LNG_ONLY(aB2 gF3)qR"addconstmul","5*(if" wF2")+x+" oS2
#define TI2 {2,N(0.25,0.0)qJ N(0.25,0.0),q7 Addlog,aC2(aB2 Addlog)aI"addlog","log(x)+log(" oS2
#define UI2 {hT qK3,aC2(aB2 qK3)LNG_ONLY(aB2 qK3)qR"addmulconstmul","5*(if" wF2")*y+x)"},
#define WI2 {hT g03,aC2(aB2 g03)LNG_ONLY(aB2 g03)qR"addnegmulneg","-5 + (if(1,5,0)*x*" oS2
#define YI2 {hT g13,aC2(aB2 g13)LNG_ONLY(aB2 g13)qR"addnegmulpos","(if(1,-5,0)*y" o42" (if(1,5,0)*x)"},
#define SJ2 {1 hN Addsin2cos2,aC2(aB2 Addsin2cos2)gR"addsin2cos2",wQ1"^2 + cos(x)^2"},
#define TJ2 {1,N(-0.7,0.0),N(0.7,0.0),N(0.28,0.0),q7 Asinhcosh,aC2(aB2 Asinhcosh)gR"asinhcosh","cosh(if(1,a" gK2"(x),0))"},
#define UJ2 {1,N(-1.0,0.0)qJ N(0.1,0.0),q7 Asinsin,aC2(aB2 Asinsin)gR"asinsin","sin(asin(x))"},
#define WJ2 dB1 qS3,aC2(aB2 qS3)LNG_ONLY(aB2 qS3)qR"cmpeq_add_imm",qX1 q52
#define YJ2 h32 mP2,aC2(aB2 mP2)LNG_ONLY(aB2 mP2)gN1"cmpeq_add_reduce",dS" = " h1},
#define SK2 dB1 mQ2,aC2(aB2 mQ2)LNG_ONLY(aB2 mQ2)qR"cmpeq_addadd_imm",dY2" =" gX3
#define TK2 {gS g23,aC2(aB2 g23)LNG_ONLY(aB2 g23)qR"cmpeq_minma" dX3"= " g33
#define UK2 {gS mR2,aC2(aB2 mR2)LNG_ONLY(aB2 mR2)qR"cmpeq_minma" dY3"= " mS2
#define WK2 dB1 m72,aC2(aB2 m72)LNG_ONLY(aB2 m72)qR"cmpeq_mul_imm_neg",hC1 q52
#define YK2 dB1 m82,aC2(aB2 m82)LNG_ONLY(aB2 m82)qR"cmpeq_mul_imm_pos",dU1 q52
#define SL2 dB1 aO2,aC2(aB2 aO2)LNG_ONLY(aB2 aO2)qR"cmpeq_mulmul_imm_neg",a31" =" gX3
#define TL2 dB1 aP2,aC2(aB2 aP2)LNG_ONLY(aB2 aP2)qR"cmpeq_mulmul_imm_pos",d23"=" gX3
#define UL2 {g21 Cmpeq_pow_imm_negneg,aC2(aB2 Cmpeq_pow_imm_negneg)gR o11 hV" = " aK2
#define WL2 {g21 Cmpeq_pow_imm_negpos,aC2(aB2 Cmpeq_pow_imm_negpos)gR o11 hY" = " aN2
#define YL2 h32 Cmpeq_pow_imm_posneg,aC2(aB2 Cmpeq_pow_imm_posneg)gR o11 d2" = " m52
#define SM2 h32 Cmpeq_pow_imm_pospos,aC2(aB2 Cmpeq_pow_imm_pospos)gR o11 d3" = " qQ3
#define TM2 h32 Cmpeq_pow_imm_pospos_base,aC2(aB2 Cmpeq_pow_imm_pospos_base)gR o11 m62"= " wT
#define UM2 dB1 Cmpeq_powpow_imm_base,aC2(aB2 Cmpeq_powpow_imm_base)aI o11 hH" = " a7
#define WM2 dB1 qT3,aC2(aB2 qT3)LNG_ONLY(aB2 qT3)qR"cmpge_add_imm",qX1 a41
#define YM2 h32 mT2,aC2(aB2 mT2)LNG_ONLY(aB2 mT2)gN1"cmpge_add_reduce",dS dF2 h1},
#define SN2 dB1 mU2,aC2(aB2 mU2)LNG_ONLY(aB2 mU2)qR"cmpge_addadd_imm",dY2 dF2 hX
#define TN2 {gS g43,aC2(aB2 g43)LNG_ONLY(aB2 g43)qR"cmpge_minma" dX3">= " g33
#define UN2 {gS mV2,aC2(aB2 mV2)LNG_ONLY(aB2 mV2)qR"cmpge_minma" dY3">= " mS2
#define WN2 dB1 m92,aC2(aB2 m92)LNG_ONLY(aB2 m92)qR"cmpge_mul_imm_neg",hC1 a41
#define YN2 dB1 mA2,aC2(aB2 mA2)LNG_ONLY(aB2 mA2)qR"cmpge_mul_imm_pos",dU1 a41
#define SO2 dB1 aQ2,aC2(aB2 aQ2)LNG_ONLY(aB2 aQ2)qR"cmpge_mulmul_imm_neg",a31 dF2 hX
#define TO2 dB1 aR2,aC2(aB2 aR2)LNG_ONLY(aB2 aR2)qR"cmpge_mulmul_imm_pos",wO"4)" dF2 hX
#define UO2 {g21 Cmpge_pow_imm_negneg,aC2(aB2 Cmpge_pow_imm_negneg)dY1 hV" >= " aK2
#define WO2 {g21 Cmpge_pow_imm_negpos,aC2(aB2 Cmpge_pow_imm_negpos)dY1 hY" >= " aN2
#define YO2 h32 Cmpge_pow_imm_posneg,aC2(aB2 Cmpge_pow_imm_posneg)dY1 d2" >= " m52
#define SP2 h32 Cmpge_pow_imm_pospos,aC2(aB2 Cmpge_pow_imm_pospos)dY1 d3" >= " qQ3
#define TP2 h32 Cmpge_pow_imm_pospos_base,aC2(aB2 Cmpge_pow_imm_pospos_base)dY1 m62">= " wT
#define UP2 dB1 Cmpge_powpow_imm_base,aC2(aB2 Cmpge_powpow_imm_base)aI"cmpge_" hH dF2 a7
#define WP2 dB1 qU3,aC2(aB2 qU3)LNG_ONLY(aB2 qU3)qR"cmpgt_add_imm",qX1 qC2
#define YP2 h32 mW2,aC2(aB2 mW2)LNG_ONLY(aB2 mW2)gN1"cmpgt_add_reduce",dS" > " h1},
#define SQ2 dB1 mX2,aC2(aB2 mX2)LNG_ONLY(aB2 mX2)qR"cmpgt_addadd_imm",dY2" >" gX3
#define TQ2 {gS g53,aC2(aB2 g53)LNG_ONLY(aB2 g53)qR"cmpgt_minma" dX3"> " g33
#define UQ2 {gS mY2,aC2(aB2 mY2)LNG_ONLY(aB2 mY2)qR"cmpgt_minma" dY3"> " mS2
#define WQ2 dB1 mB2,aC2(aB2 mB2)LNG_ONLY(aB2 mB2)qR"cmpgt_mul_imm_neg",hC1 qC2
#define YQ2 dB1 mC2,aC2(aB2 mC2)LNG_ONLY(aB2 mC2)qR"cmpgt_mul_imm_pos",dU1 qC2
#define SR2 dB1 aS2,aC2(aB2 aS2)LNG_ONLY(aB2 aS2)qR"cmpgt_mulmul_imm_neg",a31" >" gX3
#define TR2 dB1 aT2,aC2(aB2 aT2)LNG_ONLY(aB2 aT2)qR"cmpgt_mulmul_imm_pos",d23">" gX3
#define UR2 {g21 Cmpgt_pow_imm_negneg,aC2(aB2 Cmpgt_pow_imm_negneg)hO1 hV" > " aK2
#define WR2 {g21 Cmpgt_pow_imm_negpos,aC2(aB2 Cmpgt_pow_imm_negpos)hO1 hY" > " aN2
#define YR2 h32 Cmpgt_pow_imm_posneg,aC2(aB2 Cmpgt_pow_imm_posneg)hO1 d2" > " m52
#define SS2 h32 Cmpgt_pow_imm_pospos,aC2(aB2 Cmpgt_pow_imm_pospos)hO1 d3" > " qQ3
#define TS2 h32 Cmpgt_pow_imm_pospos_base,aC2(aB2 Cmpgt_pow_imm_pospos_base)hO1 m62"> " wT
#define US2 dB1 Cmpgt_powpow_imm_base,aC2(aB2 Cmpgt_powpow_imm_base)aI"cmpgt_" hH" > " a7
#define WS2 dB1 qV3,aC2(aB2 qV3)LNG_ONLY(aB2 qV3)qR"cmple_add_imm",qX1 a51
#define YS2 h32 mZ2,aC2(aB2 mZ2)LNG_ONLY(aB2 mZ2)gN1"cmple_add_reduce",dS oT3 h1},
#define ST2 dB1 q03,aC2(aB2 q03)LNG_ONLY(aB2 q03)qR"cmple_addadd_imm",dY2" " w13
#define TT2 {gS g63,aC2(aB2 g63)LNG_ONLY(aB2 g63)qR"cmple_minma" dX3"<= " g33
#define UT2 {gS q13,aC2(aB2 q13)LNG_ONLY(aB2 q13)qR"cmple_minma" dY3"<= " mS2
#define WT2 dB1 mD2,aC2(aB2 mD2)LNG_ONLY(aB2 mD2)qR"cmple_mul_imm_neg",hC1 a51
#define YT2 dB1 mE2,aC2(aB2 mE2)LNG_ONLY(aB2 mE2)qR"cmple_mul_imm_pos",dU1 a51
#define SU2 dB1 aU2,aC2(aB2 aU2)LNG_ONLY(aB2 aU2)qR"cmple_mulmul_imm_neg",a31" " w13
#define TU2 dB1 aV2,aC2(aB2 aV2)LNG_ONLY(aB2 aV2)qR"cmple_mulmul_imm_pos",d23 w13
#define UU2 {g21 Cmple_pow_imm_negneg,aC2(aB2 Cmple_pow_imm_negneg)hP1 hV oT3 aK2
#define WU2 {g21 Cmple_pow_imm_negpos,aC2(aB2 Cmple_pow_imm_negpos)hP1 hY oT3 aN2
#define YU2 h32 Cmple_pow_imm_posneg,aC2(aB2 Cmple_pow_imm_posneg)hP1 d2 oT3 m52
#define SV2 h32 Cmple_pow_imm_pospos,aC2(aB2 Cmple_pow_imm_pospos)hP1 d3 oT3 qQ3
#define TV2 h32 Cmple_pow_imm_pospos_base,aC2(aB2 Cmple_pow_imm_pospos_base)hP1 m62"<= " wT
#define UV2 dB1 Cmple_powpow_imm_base,aC2(aB2 Cmple_powpow_imm_base)aI"cmple_" hH oT3 a7
#define WV2 dB1 qW3,aC2(aB2 qW3)LNG_ONLY(aB2 qW3)qR"cmplt_add_imm",qX1 a61},
#define YV2 h32 q23,aC2(aB2 q23)LNG_ONLY(aB2 q23)gN1"cmplt_add_reduce",dS oV3 h1},
#define SW2 dB1 q33,aC2(aB2 q33)LNG_ONLY(aB2 q33)qR"cmplt_addadd_imm",dY2" " w23
#define TW2 {gS g73,aC2(aB2 g73)LNG_ONLY(aB2 g73)qR"cmplt_minma" dX3"< " g33
#define UW2 {gS q43,aC2(aB2 q43)LNG_ONLY(aB2 q43)qR"cmplt_minma" dY3"< " mS2
#define WW2 dB1 mF2,aC2(aB2 mF2)LNG_ONLY(aB2 mF2)qR"cmplt_mul_imm_neg",hC1 a61},
#define YW2 dB1 mG2,aC2(aB2 mG2)LNG_ONLY(aB2 mG2)qR"cmplt_mul_imm_pos",dU1 a61},
#define SX2 dB1 aW2,aC2(aB2 aW2)LNG_ONLY(aB2 aW2)qR"cmplt_mulmul_imm_neg",a31" " w23
#define TX2 dB1 aX2,aC2(aB2 aX2)LNG_ONLY(aB2 aX2)qR"cmplt_mulmul_imm_pos",d23 w23
#define UX2 {g21 Cmplt_pow_imm_negneg,aC2(aB2 Cmplt_pow_imm_negneg)dZ1 hV oV3 aK2
#define WX2 {g21 Cmplt_pow_imm_negpos,aC2(aB2 Cmplt_pow_imm_negpos)dZ1 hY oV3 aN2
#define YX2 h32 Cmplt_pow_imm_posneg,aC2(aB2 Cmplt_pow_imm_posneg)dZ1 d2 oV3 m52
#define SY2 h32 Cmplt_pow_imm_pospos,aC2(aB2 Cmplt_pow_imm_pospos)dZ1 d3 oV3 qQ3
#define TY2 h32 Cmplt_pow_imm_pospos_base,aC2(aB2 Cmplt_pow_imm_pospos_base)dZ1 m62"< " wT
#define UY2 dB1 Cmplt_powpow_imm_base,aC2(aB2 Cmplt_powpow_imm_base)aI"cmplt_" hH oV3 a7
#define WY2 dB1 qX3,aC2(aB2 qX3)LNG_ONLY(aB2 qX3)qR"cmpne_add_imm",qX1 dV1},
#define YY2 h32 q53,aC2(aB2 q53)LNG_ONLY(aB2 q53)gN1"cmpne_add_reduce",dS dG2 h1},
#define SZ2 dB1 q63,aC2(aB2 q63)LNG_ONLY(aB2 q63)qR"cmpne_addadd_imm",dY2 dG2 hX
#define TZ2 {gS g83,aC2(aB2 g83)LNG_ONLY(aB2 g83)qR"cmpne_minma" h12 gZ3 g33
#define UZ2 {gS q73,aC2(aB2 q73)LNG_ONLY(aB2 q73)qR"cmpne_minma" h42 gZ3 mS2
#define WZ2 dB1 mH2,aC2(aB2 mH2)LNG_ONLY(aB2 mH2)qR"cmpne_mul_imm_neg",hC1 dV1},
#define YZ2 dB1 mI2,aC2(aB2 mI2)LNG_ONLY(aB2 mI2)qR"cmpne_mul_imm_pos",dU1 dV1},
#define Sa2 dB1 aY2,aC2(aB2 aY2)LNG_ONLY(aB2 aY2)qR"cmpne_mulmul_imm_neg",a31 dG2 hX
#define Ta2 dB1 aZ2,aC2(aB2 aZ2)LNG_ONLY(aB2 aZ2)qR"cmpne_mulmul_imm_pos",wO"4)" dG2 hX
#define Ua2 {g21 Cmpne_pow_imm_negneg,aC2(aB2 Cmpne_pow_imm_negneg)o01 hV gZ3 aK2
#define Wa2 {g21 Cmpne_pow_imm_negpos,aC2(aB2 Cmpne_pow_imm_negpos)o01 hY gZ3 aN2
#define Ya2 h32 Cmpne_pow_imm_posneg,aC2(aB2 Cmpne_pow_imm_posneg)o01 d2 gZ3 m52
#define Sb2 h32 Cmpne_pow_imm_pospos,aC2(aB2 Cmpne_pow_imm_pospos)o01 d3 gZ3 qQ3
#define Tb2 h32 Cmpne_pow_imm_pospos_base,aC2(aB2 Cmpne_pow_imm_pospos_base)o01 m62"!= " wT
#define Ub2 dB1 Cmpne_powpow_imm_base,aC2(aB2 Cmpne_powpow_imm_base)aI"cmpne_" hH dG2 a7
#define Wb2 dB1 qY3,aC2(aB2 qY3)LNG_ONLY(aB2 qY3)qR"cmpzz_add_imm" dT h52 a61 aE h52 oZ1 h52 a71 qX1 a81 h52 dV1 d7 qX1 q52
#define Yb2 h32 q83,aC2(aB2 q83)LNG_ONLY(aB2 q83)gN1"cmpzz_add_reduce" dT" " dS oV3 h1 aE" " dS oT3 h1 aG" " dS" > " h1 aC dS dF2 h1 hD1" " dS dG2 h1 d7 dS" = " h1},
#define Sc2 dB1 q93,aC2(aB2 q93)LNG_ONLY(aB2 q93)qR"cmpzz_addadd_imm" dT" " o6 q62" " o6 q92" " o6 qA2 dY2 dF2 dZ2" " dY2 oW1 dY2" =" gX3
#define Tc2 {gS g93,aC2(aB2 g93)LNG_ONLY(aB2 g93)qR"cmpzz_minmax" dT d33"< " d43 aE d33"<= " d43 aG d33"> " d43 g1"0008 " h62" >= y,x,y" wI g11 gZ3"y,x,y" o42"  0x0020 " h62" = " g33
#define Uc2 {gS qA3,aC2(aB2 qA3)LNG_ONLY(aB2 qA3)qR"cmpzz_minmax_rev" dT d33"< " gK3 aE d33"<= " gK3 aG d33"> " gK3 g1"0008 " h62" >= " gK3 hD1 g11 gZ3 gK3" +  0x0020 " h62" = " mS2
#define Wc2 dB1 mJ2,aC2(aB2 mJ2)LNG_ONLY(aB2 mJ2)qR"cmpzz_mul_imm_neg" dT mJ1 a61 aE mJ1 oZ1 mJ1 a71 hC1 a81 mJ1 dV1 d7 hC1 q52
#define Yc2 dB1 mK2,aC2(aB2 mK2)LNG_ONLY(aB2 mK2)qR"cmpzz_mul_imm_pos" dT mK1 a61 aE mK1 oZ1 mK1 a71 dU1 a81 mK1 dV1 d7 dU1 q52
#define Sd2 dB1 m02,aC2(aB2 m02)LNG_ONLY(aB2 m02)qR"cmpzz_mulmul_imm_neg" dT qY1 q62 qY1 q92 qY1 qA2 a31 dF2 dZ2 qY1")" oW1 a31" =" gX3
#define Td2 dB1 m12,aC2(aB2 m12)LNG_ONLY(aB2 m12)qR"cmpzz_mulmul_imm_pos" dT qZ1 q62 qZ1 q92 qZ1 qA2 wO"4)" dF2 dZ2 qZ1")" oW1 d23"=" gX3
#define Ud2 {g21 Cmpzz_pow_imm_negneg,aC2(aB2 Cmpzz_pow_imm_negneg)q01"_imm_negneg" dT h11 oV3 gC3 aE h11 oT3 gC3 aG h11" > " gC3 aC gL",-3) >= -0.015625" wI h11 gZ3"-0.015625" wZ1",-3) = " aK2
#define Wd2 {g21 Cmpzz_pow_imm_negpos,aC2(aB2 Cmpzz_pow_imm_negpos)q01"_imm_negpos" dT h21 oV3 hQ3 aE h21 oT3 hQ3 aG h21" > " hQ3 aC gL",-2) >= 0.0625" wI h21 gZ3"0.0625" wZ1",-2) = " aN2
#define Yd2 h32 Cmpzz_pow_imm_posneg,aC2(aB2 Cmpzz_pow_imm_posneg)q01"_imm_posneg" dT d71 oV3 oD3 aE d71 oT3 oD3 aG d71" > " oD3 aC gL",3) >= -125" wI d71 gZ3"-125" wZ1",3) = " m52
#define Se2 h32 Cmpzz_pow_imm_pospos,aC2(aB2 Cmpzz_pow_imm_pospos)q01"_imm_pospos" dT d81" < 25)" aE d81" <= 25)" aG d81" > 25)" aC gL",2) >= 25" wI d81 gZ3"25" wZ1",2) = " qQ3
#define Te2 h32 Cmpzz_pow_imm_pospos_base,aC2(aB2 Cmpzz_pow_imm_pospos_base)q01"_imm_pospos_base" dT oU3"< " mW aE oU3"<= " mW aG oU3"> " mW aC qD3">= " mW hD1 oU3"!= " mW d7 qD3"= " wT
#define Ue2 dB1 Cmpzz_powpow_imm_base,aC2(aB2 Cmpzz_powpow_imm_base)aI"cmpzz_powpow_imm_base" dT wZ2 oV3 qS1 aE wZ2 oT3 qS1 aG wZ2" > " qS1 aC qB1 dF2 qS1 hD1 wZ2 dG2 qS1 d7 qB1" = " a7
#define We2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 Eq0,aC2(aB2 Eq0)LNG_ONLY(aB2 Eq0)gN1"eq0","(x=if(" hQ2" + (if(" hR2"=" aN1
#define Ye2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 Eq1,aC2(aB2 Eq1)LNG_ONLY(aB2 Eq1)gN1"eq1","(!x=if(" hS2},
#define Sf2 {2,o4 Expexp_a,aC2(aB2 Expexp_a)aI oD2"p_a","exp(x*2 + y*3" gO2
#define Tf2 {3,o4 Expexp_b,aC2(aB2 Expexp_b)aJ oD2"p_b",aR" * exp(y+z" gO2
#define Uf2 {3,o4 Expexp_c,aC2(aB2 Expexp_c)aJ oD2"p_c","exp(x + y*z" gO2
#define Wf2 dB oJ3,aC2(aB2 oJ3)LNG_ONLY(aB2 oJ3)gN1"ge0_abs",oL1" >= if(" hQ2 qT1 hR2 oT3 qJ3"<= if(" gC1 gD1 hR2" >= " gN3
#define Yf2 dB oK3,aC2(aB2 oK3)LNG_ONLY(aB2 oK3)gN1"ge1_abs",oL1" >= if(" hS2 qT1 dQ3"<= " qJ3"<= if(" hN1 gD1 dQ3">= " gN3
#define Sg2 {gS h73,aC2(aB2 h73)LNG_ONLY(aB2 h73)qR"ge_and_eq",o02 hX1
#define Tg2 {gS h83,aC2(aB2 h83)LNG_ONLY(aB2 h83)qR"ge_and_le",o02 g51},
#define Ug2 {gS h93,aC2(aB2 h93)LNG_ONLY(aB2 h93)qR"ge_and_ne",o02 hY1
#define Wg2 {gS d53,aC2(aB2 d53)LNG_ONLY(aB2 d53)qR"ge_or_eq",o12 hX1
#define Yg2 {gS d63,aC2(aB2 d63)LNG_ONLY(aB2 d63)qR"ge_or_le",o12 g51},
#define Sh2 {gS d73,aC2(aB2 d73)LNG_ONLY(aB2 d73)qR"ge_or_ne",o12 hY1
#define Th2 {1,N(-1.0,0.0)qJ N(0.25,0.0),q7 Gehalf,aC2(aB2 Gehalf)gR"gehalf","x>=if(1,0.5,0" gO2
#define Uh2 dB oL3,aC2(aB2 oL3)LNG_ONLY(aB2 oL3)gN1"gt0_abs",oL1" > if(" hQ2 qT1 hR2 oV3 qJ3"< if(" gC1 gD1 hR2" > " gN3
#define Wh2 dB oM3,aC2(aB2 oM3)LNG_ONLY(aB2 oM3)gN1"gt1_abs",oL1" > if(" hS2 qT1 dQ3"< " qJ3"< if(" hN1 gD1 dQ3"> " gN3
#define Yh2 {gS hA3,aC2(aB2 hA3)LNG_ONLY(aB2 hA3)qR"gt_and_eq" mL1 hX1
#define Si2 {gS hB3,aC2(aB2 hB3)LNG_ONLY(aB2 hB3)qR"gt_and_ge" mL1 mB},
#define Ti2 {gS hC3,aC2(aB2 hC3)LNG_ONLY(aB2 hC3)qR"gt_and_le" mL1 g51},
#define Ui2 {gS hD3,aC2(aB2 hD3)LNG_ONLY(aB2 hD3)qR"gt_and_ne" mL1 hY1
#define Wi2 {gS d83,aC2(aB2 d83)LNG_ONLY(aB2 d83)qR"gt_or_eq" mM1 hX1
#define Yi2 {gS d93,aC2(aB2 d93)LNG_ONLY(aB2 d93)qR"gt_or_ge" mM1 mB},
#define Sj2 {gS dA3,aC2(aB2 dA3)LNG_ONLY(aB2 dA3)qR"gt_or_le" mM1 g51},
#define Tj2 {gS dB3,aC2(aB2 dB3)LNG_ONLY(aB2 dB3)qR"gt_or_ne" mM1 hY1
#define Uj2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 If10,aC2(aB2 If10)LNG_ONLY(aB2 If10)gN1"if10",o1",1,0" o42" 10*" o1",0,1)" o13" + 100*" o1">0,1,0" o42" 1000*" o1">0,0,1" gO2
#define Wj2 gT qL3,aC2(aB2 qL3)LNG_ONLY(aB2 qL3)gQ2"tract_abs",dZ3"abs(x+2), abs(y+5))"},
#define Yj2 gT qM3,aC2(aB2 qM3)LNG_ONLY(aB2 qM3)gQ2"tract_add" aX1"+2, y+" q12
#define Sk2 gT qE3,aC2(aB2 qE3)LNG_ONLY(aB2 qE3)gQ2"tract_add1" aX1"+2, y" gO2
#define Tk2 gT qF3,aC2(aB2 qF3)LNG_ONLY(aB2 qF3)gQ2"tract_add2",dZ3"y, y+2" gO2
#define Uk2 gU mL2,aC2(aB2 mL2)LNG_ONLY(aB2 mL2)mN1"tract_and1_l" aX1"&z, y<1" gO2
#define Wk2 gU m32,aC2(aB2 m32)LNG_ONLY(aB2 m32)mN1"tract_and1_nl" aX1"&z, z" gO2
#define Yk2 gU mM2,aC2(aB2 mM2)LNG_ONLY(aB2 mM2)mN1"tract_and2_l",dZ3"y<1, y&z" gO2
#define Sl2 gU m42,aC2(aB2 m42)LNG_ONLY(aB2 m42)mN1"tract_and2_nl",dZ3"z, y&z" gO2
#define Tl2 gT qN3,aC2(aB2 qN3)LNG_ONLY(aB2 qN3)gQ2"tract_min",dZ3"min(y,2), min(y,5))"},
#define Ul2 gT qO3,aC2(aB2 qO3)LNG_ONLY(aB2 qO3)gQ2"tract_mul" aX1"*2, y*" q12
#define Wl2 gT qG3,aC2(aB2 qG3)LNG_ONLY(aB2 qG3)gQ2"tract_mul1" aX1"*2, y" gO2
#define Yl2 gT qH3,aC2(aB2 qH3)LNG_ONLY(aB2 qH3)gQ2"tract_mul2",dZ3"y, y*2" gO2
#define Sm2 gU qB3,aC2(aB2 qB3)LNG_ONLY(aB2 qB3)mN1"tract_or1_l",dZ3"y|z, y<1" gO2
#define Tm2 gU mN2,aC2(aB2 mN2)LNG_ONLY(aB2 mN2)mN1"tract_or1_nl",dZ3"y|z, z" gO2
#define Um2 gU qC3,aC2(aB2 qC3)LNG_ONLY(aB2 qC3)mN1"tract_or2_l",dZ3"y<1, y|z" gO2
#define Wm2 gU mO2,aC2(aB2 mO2)LNG_ONLY(aB2 mO2)mN1"tract_or2_nl",dZ3"z, y|z" gO2
#define Ym2 {2,N(-4.0,0.0),aI1,wK2 q7 If_extract_sin,aC2(aB2 If_extract_sin)aI dE1"tract_sin",dZ3"sin(y), " qR3
#define Sn2 {2,h5 If_join_add,aC2(aB2 If_join_add)aI"if_join_add",hV2"+" o21
#define Tn2 {1,N(3.0,0.0),N(5.0,0.0)qJ q7 gA3,aC2(aB2 gA3)LNG_ONLY(aB2 gA3)gN1"if_join_add2","x + 10 +" g11"<4, 3,4" gO2
#define Un2 {2,h5 If_join_and,aC2(aB2 If_join_and)aI"if_join_and",hV2"&" o21
#define Wn2 {2,h5 If_join_max,aC2(aB2 If_join_max)aI"if_join_max","max(" o1 dE", " dO3")))"},
#define Yn2 {2,h5 If_join_min,aC2(aB2 If_join_min)aI"if_join_min","min(" o1 dE", " dO3")))"},
#define So2 {2,h5 If_join_mul,aC2(aB2 If_join_mul)aI"if_join_mul",hV2"*" o21
#define To2 {1,N(3.0,0.0),N(5.0,0.0)qJ q7 gB3,aC2(aB2 gB3)LNG_ONLY(aB2 gB3)gN1"if_join_mul2","x * 10 " h62"<4, 3,4" gO2
#define Uo2 {2,h5 If_join_or,aC2(aB2 If_join_or)aI"if_join_or",o1 dE" | " dO3"))"},
#define Wo2 dB Ifabs,aC2(aB2 Ifabs)LNG_ONLY(aB2 Ifabs)gN1"ifabs","1" qO1"< 0,-x" qP3 o13"10" qO1"<=0,-x" qP3"  100" qO1"> 0,-x" qP3" 1000" qO1">=0,-x" qP3"10000" qO1"< 0,x" h82 aM2" 100000" qO1"<=0,x" h82 aM2"1000000" qO1"> 0,x" h82"  10000000" qO1">=0,x,-" dX2
#define Yo2 {3 hN Ifabsnot,aC2(aB2 Ifabsnot)aJ"ifabsnot","if(!(sin(x)+1.2), y,z" gO2
#define Sp2 {3 hN Ifconst,aC2(aB2 Ifconst)aJ"ifconst","if(1, x,y" o42" if(0,z,y" gO2
#define Tp2 {4,N(0.0,0.0)qJ N(1.0,0.0),q7 Ififconst,aC2(aB2 Ififconst)LNG_ONLY(0)"w," aP"ififconst","if(" o1",1,y),z,w" o42" if(if(w,z,0)," h22
#define Up2 {4,wX oA3,aC2(aB2 oA3)LNG_ONLY(aB2 oA3)"b,d," qR"ifmerge",o1 gJ2"y,x,b" oV2"y,x,d)) +  if(b,if(d,y,x)" gJ2"d,b," dX2
#define Wp2 {4,wX dC3,aC2(aB2 dC3)LNG_ONLY(aB2 dC3)"a,b," qR"ifmerge2",o1 gJ2"y,a,b" oV2"b,a,b))"},
#define Yp2 {4,wX hE3,aC2(aB2 hE3)LNG_ONLY(aB2 hE3)"a,b," qR"ifmerge2b",o1 gJ2"y,a,b" oV2"b,b,a))"},
#define Sq2 {gS Ifnop,aC2(aB2 Ifnop)LNG_ONLY(aB2 Ifnop)qR"ifnop",o1",y,y" gO2
#define Tq2 wB Ifnot,aC2(aB2 Ifnot)aJ"ifnot","if(!x, y,z" gO2
#define Uq2 {dR L_abs,aC2(aB2 L_abs)LNG_ONLY(aB2 L_abs)qR"l_abs","(x+2) & " hY3 hB1
#define Wq2 {dR dD3,aC2(aB2 dD3)LNG_ONLY(aB2 dD3)qR"l_mulabs","(x*abs(y))" hB1
#define Yq2 {dR dE3,aC2(aB2 dE3)LNG_ONLY(aB2 dE3)qR"l_mulneg","(x*y*-5)" hB1
#define Sr2 {dR dF3,aC2(aB2 dF3)LNG_ONLY(aB2 dF3)qR"l_notnot","(x+2) & !!x" hB1
#define Tr2 {gS hF3,aC2(aB2 hF3)LNG_ONLY(aB2 hF3)qR"le_and_eq",g51" & " hX1
#define Ur2 {gS hG3,aC2(aB2 hG3)LNG_ONLY(aB2 hG3)qR"le_and_ne",g51" & " hY1
#define Wr2 {gS dG3,aC2(aB2 dG3)LNG_ONLY(aB2 dG3)qR"le_or_eq",g51" | " hX1
#define Yr2 {gS dH3,aC2(aB2 dH3)LNG_ONLY(aB2 dH3)qR"le_or_ne",g51" | " hY1
#define Ss2 {gS hH3,aC2(aB2 hH3)LNG_ONLY(aB2 hH3)qR"lt_and_eq" qE2 hX1
#define Ts2 {gS hI3,aC2(aB2 hI3)LNG_ONLY(aB2 hI3)qR"lt_and_ge" qE2 mB},
#define Us2 {gS hJ3,aC2(aB2 hJ3)LNG_ONLY(aB2 hJ3)qR"lt_and_gt" qE2"(x > y" gO2
#define Ws2 {gS hK3,aC2(aB2 hK3)LNG_ONLY(aB2 hK3)qR"lt_and_le" qE2 g51},
#define Ys2 {gS hL3,aC2(aB2 hL3)LNG_ONLY(aB2 hL3)qR"lt_and_ne" qE2 hY1
#define St2 {gS dI3,aC2(aB2 dI3)LNG_ONLY(aB2 dI3)qR"lt_or_eq" hM3 hX1
#define Tt2 {gS dJ3,aC2(aB2 dJ3)LNG_ONLY(aB2 dJ3)qR"lt_or_ge" hM3 mB},
#define Ut2 {gS dK3,aC2(aB2 dK3)LNG_ONLY(aB2 dK3)qR"lt_or_gt" hM3"(x > y" gO2
#define Wt2 {gS dL3,aC2(aB2 dL3)LNG_ONLY(aB2 dL3)qR"lt_or_le" hM3 g51},
#define Yt2 {gS dM3,aC2(aB2 dM3)LNG_ONLY(aB2 dM3)qR"lt_or_ne" hM3 hY1
#define Su2 {1,N(-1.0,0.0)qJ N(0.25,0.0),q7 Lthalf,aC2(aB2 Lthalf)gR"lthalf","x<if(1,0.5,0" gO2
#define Tu2 gU gG3,aC2(aB2 gG3)LNG_ONLY(aB2 gG3)aP"mergemulabs","abs(x)*abs(y)*z"},
#define Uu2 {3,N(0.0,0.0),aI1 qJ q7 gH3,aC2(aB2 gH3)LNG_ONLY(aB2 gH3)aP"mixedminmax","max(z,min(x,max(max(z,y),x)))" o33"10*min(z,max(x,min(y,x)))" o33"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Wu2 {2 hN Muland2,aC2(aB2 Muland2)aI"muland2",hR3},
#define Yu2 {3 hN Muland2plus,aC2(aB2 Muland2plus)aJ"muland2plus",hR3" * z"},
#define Sv2 {3 hN Muland3,aC2(aB2 Muland3)aJ"muland3",hR3" * !!z"},
#define Tv2 {2 hN Mulandlt,aC2(aB2 Mulandlt)aI"mulandlt",hC2" (y<0" gO2
#define Uv2 {2,N(0.25,0.0)qJ N(0.25,0.0),q7 Mulimmlog,aC2(aB2 Mulimmlog)aI"mulimmlog","log(if(1,5,0)*x*" oS2
#define Wv2 {2 hN Mulnor2,aC2(aB2 Mulnor2)aI"mulnor2",hS3},
#define Yv2 {3 hN Mulnor2plus,aC2(aB2 Mulnor2plus)aJ"mulnor2plus",hS3" * z"},
#define Sw2 {3 hN Mulnor3,aC2(aB2 Mulnor3)aJ"mulnor3",hS3" * !z"},
#define Tw2 {gS Nand2,aC2(aB2 Nand2)LNG_ONLY(aB2 Nand2)qR"nand2",hN3},
#define Uw2 wB hO3,aC2(aB2 hO3)LNG_ONLY(aB2 hO3)aP"nand2plus",hN3" | z"},
#define Ww2 wB Nand3,aC2(aB2 Nand3)LNG_ONLY(aB2 Nand3)aP"nand3",hN3" | !z"},
#define Yw2 dB Negceil,aC2(aB2 Negceil)gR"negceil","ceil(x*(abs(x)-abs(x)-1))"},
#define Sx2 dB Negcos,aC2(aB2 Negcos)gR"negcos","cos" qC1
#define Tx2 dB Negcosh,aC2(aB2 Negcosh)gR"negcosh","cosh" qC1
#define Ux2 dB Negfloor,aC2(aB2 Negfloor)gR"negfloor","floor(x*(abs(x)-abs(x)-1))"},
#define Wx2 dB Negsin,aC2(aB2 Negsin)gR"negsin","sin(x*if(1,-1,0))"},
#define Yx2 dB Negsinh,aC2(aB2 Negsinh)gR"neg" gK2,gK2 qC1
#define Sy2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 Neq0,aC2(aB2 Neq0)LNG_ONLY(aB2 Neq0)gN1"neq0","(x!=if(" hQ2" + (if(" hR2"!=" aN1
#define Ty2 {1,N(0.0,0.0)qJ N(1.0,0.0),q7 Neq1,aC2(aB2 Neq1)LNG_ONLY(aB2 Neq1)gN1"neq1","(!x!=if(" hS2},
#define Uy2 {gS Nor2,aC2(aB2 Nor2)LNG_ONLY(aB2 Nor2)qR"nor2",hP3},
#define Wy2 wB dN3,aC2(aB2 dN3)LNG_ONLY(aB2 dN3)aP"nor2plus",hP3" & z"},
#define Yy2 wB Nor3,aC2(aB2 Nor3)LNG_ONLY(aB2 Nor3)aP"nor3",hP3" & !z"},
#define Sz2 {gS Not_eq,aC2(aB2 Not_eq)LNG_ONLY(aB2 Not_eq)qR"not_eq",o1" = " m22
#define Tz2 {gS Not_ge,aC2(aB2 Not_ge)LNG_ONLY(aB2 Not_ge)qR"not_ge",o1" >= " m22
#define Uz2 {gS Not_gt,aC2(aB2 Not_gt)LNG_ONLY(aB2 Not_gt)qR"not_gt",o1" > " m22
#define Wz2 {gS Not_le,aC2(aB2 Not_le)LNG_ONLY(aB2 Not_le)qR"not_le",o1 oT3 m22
#define Yz2 {gS Not_lt,aC2(aB2 Not_lt)LNG_ONLY(aB2 Not_lt)qR"not_lt",o1 oV3 m22
#define S_2 {gS Not_ne,aC2(aB2 Not_ne)LNG_ONLY(aB2 Not_ne)qR"not_ne",o1 gZ3 m22
#define T_2 gT Notnot,aC2(aB2 Notnot)LNG_ONLY(aB2 Notnot)qR"notnot","!!x + if(y, 1,0" gO2
#define U_2 {1 hN Posnot,aC2(aB2 Posnot)gR"posnot","!(sin(x) + 1.2" gO2
#define W_2 {1 hN Posnotnot,aC2(aB2 Posnotnot)gR"posnotnot","!!(sin(x) + 1.2" gO2
#define Y_2 {1,N(0.25,0.0)qJ N(0.25,0.0),q7 Powimmaddimmlog,aC2(aB2 Powimmaddimmlog)w11"immaddimmlog","pow(5, log(x)+1" gO2
#define S03 {1,N(0.25,0.0),mH1,N(0.25,0.0),q7 Powimmlog,aC2(aB2 Powimmlog)w11"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define T03 {hT Powmulimm_fnen,aC2(aB2 Powmulimm_fnen)qA g61"mulimm_fnen" h51"^(-8" gO2
#define U03 {wC Powmulimm_fnep,aC2(aB2 Powmulimm_fnep)qA g61"mulimm_fnep" h51"^(4" gO2
#define W03 {1,N(-3.0,0.0),N(-1.0,0.0),wK2 q7 Powmulimm_fnfn,aC2(aB2 Powmulimm_fnfn)w11"mulimm_fnfn","((-5.1)*x)^(-7.1" gO2
#define Y03 {wC Powmulimm_fnfp,aC2(aB2 Powmulimm_fnfp)qA g61"mulimm_fnfp" h51"^7.1"},
#define S13 {wC Powmulimm_fpfp,aC2(aB2 Powmulimm_fpfp)qA g61"mulimm_fpfp","(5.1*x*y)^7.1"},
#define T13 {1 hN Sub1cos2,aC2(aB2 Sub1cos2)gR"sub1cos2","1-cos(x)^2"},
#define U13 {1 hN Sub1sin2,aC2(aB2 Sub1sin2)gR"sub1sin2","1-" wQ1"^2"},
#define W13 {1,N(-9.42477796076937971538793014983850865259,0.0),N(9.42477796076937971538793014983850865259,0.0),N(0.785398163397448309615660845819875721049292349,0.0),q7 Trig_modulo,aC2(aB2 Trig_modulo)gR"trig_modulo","cos(x+pi" q81"2/3" q81"5/2" q81"6/2" q81 hD2 o13" " hH1")" hW2"2/3)" hW2"5/2)" hW2"6/2)" hW2 hD2 o13" cos(x-pi)" g41"2/3)" g41"5/2)" g41"6/2)" g41 hD2"  sin(x-pi)" h61"2/3)" h61"5/2)" h61"6/2)" h61"7/2" gO2
#define Y13 {1,N(-3.0,0.0),N(3.0,0.0),N(0.25,0.0),q7 Trunc_from_if,aC2(aB2 Trunc_from_if)gR"trunc_from_if",o1">0,  " gI3 qM2">=0, " gI3 qM2"<0,  " gD3 qM2"<=0, " gD3 w21">0,  " gD3 w21">=0, " gD3 w21"<0,  " gI3" 10*" o1"<=0, floor(x),ceil" hF1
#define S23 {1,N(-5.0,0.0),N(5.0,0.0)qJ q7 o93,aC2(aB2 o93)LNG_ONLY(aB2 o93)"x" q8"/xaddnot","!(x+if(1,4,4))"},
#define T23 {1,N(-5.0,0.0),N(5.0,0.0)qJ q7 gT3,aC2(aB2 gT3)LNG_ONLY(aB2 gT3)"x" q8"/xaddnotnot","!!(x+if(1,4,4))"},
#define N(x) (x)
#define P(x) N(x##.0)
namespace
cpp_01unit_operators{using
namespace
FUNCTIONPARSERTYPES;q3
Add_cd(hX2
Add_d(hX2
Add_i(hX2
Addsub_cd
qI1
Addsub_d
qI1
Addsub_i
qI1
And_d(qH
oR1>=a01?fp_abs(y)>=a01:dR3
And_i(qH
x
gM
y!=aS1:d22
Cmpeq_cd(qH
x==oV1
Cmpeq_d(qH
x==oV1
Cmpeq_i(qH
x==oV1
Cmpge_d
g52
Cmpge_i
g52
Cmpgt_d(qH
x>oV1
Cmpgt_i(qH
x>oV1
Cmple_d(qH
x<=oV1
Cmple_i(qH
x<=oV1
Cmplt_d(qH
x<oV1
Cmplt_i(qH
x<oV1
Cmpne_cd(qH
x!=oV1
Cmpne_d(qH
x!=oV1
Cmpne_i(qH
x!=oV1
Div_d(qH(x-q0(0.25l))/oV1
Div_i(qH
x/(y+q0(3l
qQ
Divmul_d
hM
x*y*x*x/z*(x-q0(0.25l
qQ
Divmul_i
hM
x*y*x*x/(z+d52*(x+q51
Inv_d
aK1
x;}
q3
Inv_i
aK1
x;}
q3
Mod(qC,&z=vars[1
mE1
fmod(x,z);}
q3
Mod_i(qC,&z=vars[1
mE1
x%(z+q0(3l
qQ
Mul_cd(qH
x*oV1
Mul_d(qH
x*oV1
Mul_i(qH
x*(y+q51
Neg_cd(hY2
Neg_d(hY2
Neg_i(hY2
Not_d(qK
oR1<oE1
Not_i(qK
q0(x==dR3
Notnot_d(qK
oR1>=oE1
Notnot_i(qK
q0(x!=dR3
Or_d(qH
oR1<a01?fp_abs(y)>=a01:q0(1l
qQ
Or_i(qH
x==aS1?y!=aS1:aL1;}
q3
Sub_cd(qH
x-oV1
Sub_d(qH
x-oV1
Sub_i(qH
x-y;}
}
namespace
cpp_02unit_functions{using
namespace
FUNCTIONPARSERTYPES;q3
Abs_cd(qK
std::abs(m1
Abs_d(qK
x<aS1?-x:x;}
q3
Abs_i(qK
x<aS1?-x:x;}
q3
Acos(qK
acos(m1
Acos_deg(aY1
acos(x
qQ
Acosh(qK
qU1-1.0
qQ
Acosh_deg(aY1
qU1-1.0)qQ
Arg(qK
hQ
m1
Asin(qK
asin(m1
Asin_deg(aY1
asin(x
qQ
Asinh(qK
qU1+1.0
qQ
Asinh_deg(aY1
qU1+1.0)qQ
Atan(qK
atan(m1
Atan2(qH
atan2(x
oC3
Atan2_deg(qH
r2d(atan2(x,y
qQ
Atan_deg(aY1
atan(x
qQ
Atanh(qK
log((1.0+x)/(1.0-x))*0.5;}
q3
Cbrt(qK
x<0.0?-exp(log(-x)/3.0):(x>0.0?exp(log(x)/3.0):0.0);}
q3
Ceil(qK
ceil(m1
Conj(qK
fp_conj(m1
Cos(qK
cos(m1
Cos_deg(qK
cos(oC1
Cosh(qK
cosh(m1
Cosh_deg(qK
cosh(oC1
Exp(oW3
m1
Exp2(oW3
x*fp_const_log2<q0>(qQ
Floor(qK
floor(m1
Hypot(qH
sqrt(x*x+y*y);}
q3
If_d
hM
fp_abs(x)>=a01?y:z;}
q3
If_i
hM(x!=aS1)?y:z;}
q3
Imag(qK
fp_imag(m1
Int(qK
fp_floor(x+oE1
Log(qK
log(m1
Log2(qK
log(x)*1.4426950408889634073599246810018921374266;}
q3
Log10(qK
log(x)*0.43429448190325182765112891891660508229;}
q3
Log_cd(qK
std::log(m1
Max(qH
x>y?x:oV1
Min(qH
x<y?x:oV1
Polar(qH
fp_polar(x
oC3
Pow_neg(qH
pow(-x*0.25
oC3
Pow_pos(qH
pow(x
oC3
Real(qK
fp_real(m1
Sin(qK
sin(m1
Sin_deg(qK
sin(oC1
Sinh(qK
sinh(m1
Sinh_deg(qK
sinh(oC1
Sqrt(qK
sqrt(m1
Sqrt_cd(qK
std::sqrt(m1
Tan(qK
tan(m1
Tan_deg(qK
tan(oC1
Tanh(qK
tanh(m1
Tanh_deg(qK
tanh(oC1
Trunc(qK
x<0.0?ceil(x):floor(x);}
}
namespace
cpp_03unit_constants{using
namespace
FUNCTIONPARSERTYPES;q3
E_d(oW3
x*0.0+1.0);}
q3
L2_d(qK
log(x*0.0+2.0);}
q3
L10_d(qK
log(x*0.0+10.0);}
q3
Pi_d(qK
atan2(x*0.0,-1.0);}
}
namespace
cpp_10optimizer_bytecode{using
namespace
FUNCTIONPARSERTYPES;q3
Abs(qK(d52
h81
Abscos(qK
gX2
gP1
Abscosh(qK
hZ2
gP1
Abseq0
gF1(gQ1+fp_equal(aS1,gP1
Absevenconstpow(g12
fp_abs(gZ1
1506l
qQ
Absmulevenconstpow(qH
a42
fp_abs(x)*y,q0(1506l
qQ
oF3
gF1(gQ1+fp_equal(aS1,gP1
Absneverneg(qK
fp_acos(m1
Absnot(qB2
gP1
Absnot2(qB2
fp_acos(x
qQ
Absnot3(qH
fp_not(fp_not(wY2
x,y)qQ
Absnot4(qB2
fp_not
wX2
x)qQ
qZ3(qB2
fp_notNot((x*x)qQ
o43(qC;q0
b0[2
mE1
userDefFuncSub<q0>((b0[0]=(fp_greaterOrEq(fp_abs(x),wG),b0[1]=(fp_greaterOrEq(gQ1),b0
qQ
o53(qC;q0
b1[2
mE1
userDefFuncSub<q0>((b1[0]=(a22
fp_abs(x),wG),b1[1]=(a22
gQ1),b1
qQ
Abssqr
oG2
x;}
q3
Absyxpow_neg(g12
qP-4.0),1.5);}
q3
Absyxpow_pos(g12
qP
4.0),1.5);}
q3
Acos(qK
acos(0.7)h81
Acos_deg(aY1
acos(0.7))h81
Acosh(qK
mF
1.1-1.0))h81
Acosh_deg(aY1
mF
1.1-1.0)))h81
Acoshcosh(qK
hZ2
fp_acosh(x
qQ
Acoshsinh(qK
fp_sinh(fp_acosh(x
qQ
Add(qK
o82+q0(3l)h81
Add0(qK
x+aS1
h81
Addexp
aR1
x+q51
Addexp2(qK
gY2
x+q51
And(qK
oD1
gE1+oD1
5l),aS1)+oD1
0l),o82)+oD1
0l),dR3
Asin(qK
asin(0.7)h81
Asin_deg(aY1
asin(0.7))h81
Asinh(qK
mF
1.1+1.0))h81
Asinh_deg(aY1
mF
1.1+1.0)))h81
Asinhcosh(qK
hZ2
fp_asinh(x
qQ
Asinhsinh(qK
fp_sinh(fp_asinh(x
qQ
Atan(qK
atan(oT2
Atan2(qK
atan2(5.0,4.0)h81
Atan2_deg(aY1
atan2(5.0,4.0))h81
Atan2tan(qH
qZ2
wU1
x,y
qQ
Atan_deg(aY1
atan(1.1))h81
Atanh(qK
log((1.0+0.7)/(1.0-0.7))*0.5+x;}
q3
Cbrt(oW3
log(1.1)/3.0)h81
Ceil(qK
ceil(oT2
Ceilneg(qK
wR2-m1
Cmp_acos(oR
hK))qX
hK))qS
hK))qT
hK))qU
hK))qV
hK
qQ
Cmp_acos_outrange(oR
q11
qX
q11
qS
q11
qT
q11
qU
q11
qV
fp_acos(gZ1
2l
qQ
oG3(oR(wW2
qX(wW2
qS(wW2
qT(wW2
qU(wW2
qV(q0(dJ
qQ
Cmp_asin(oR
hL))qX
hL))qS
hL))qT
hL))qU
hL))qV
hL
qQ
Cmp_asin_outrange(oR
q21
qX
q21
qS
q21
qT
q21
qU
q21
qV
fp_asin(gZ1
2l
qQ
Cmp_atan(oR
dQ2
qX
dQ2
qS
dQ2
qT
dQ2
qU
dQ2
qV
oB
h91
Cmp_exp(oR
oW
qX
oW
qS
oW
qT
oW
qU
oW
qV
qJ1
fp_exp(h91
Cmp_exp2(oR
dR2
qX
dR2
qS
dR2
qT
dR2
qU
dR2
qV
oC
h91
Cmp_exp2_neg(oR
w3))qX
w3))qS
w3))qT
w3))qU
w3))qV
w3
qQ
Cmp_exp_neg(oR
qJ1-wG
qX
qJ1-wG
qS
qJ1-wG
qT
qJ1-wG
qU
qJ1-wG
qV
qJ1-q51
Cmp_log2_nn(oR
hB
hQ1
qX
hB
hQ1
qS
hB
hQ1
qT
hB
hQ1
qU
hB
hQ1
qV
hB
x),hT1
Cmp_log2_np(oR
hB
x),hB
gE)qX
hB
x),hB
gE)qS
hB
x),hB
gE)qT
hB
x),hB
gE)qU
hB
x),hB
gE)qV
hB
x),hB
h91
Cmp_log2_pn(oR
hB
qU2
qX
hB
qU2
qS
hB
qU2
qT
hB
qU2
qU
hB
qU2
qV
hB
gB
hT1
Cmp_log2_pp(oR
hB
gB
hB
gE)qX
hB
gB
hB
gE)qS
hB
gB
hB
gE)qT
hB
gB
hB
gE)qU
hB
gB
hB
gE)qV
hB
gB
hB
h91
Cmp_log10_nn(oR
gP
hQ1
qX
gP
hQ1
qS
gP
hQ1
qT
gP
hQ1
qU
gP
hQ1
qV
gP
x),hT1
Cmp_log10_np(oR
gP
x
oZ3)qX
gP
x
oZ3)qS
gP
x
oZ3)qT
gP
x
oZ3)qU
gP
x
oZ3)qV
gP
x),gP
h91
Cmp_log10_pn(oR
gP
qU2
qX
gP
qU2
qS
gP
qU2
qT
gP
qU2
qU
gP
qU2
qV
gP
gB
hT1
Cmp_log10_pp(oR
gP
gB
gP
wR1
qX
gP
gB
gP
wR1
qS
gP
gB
gP
wR1
qT
gP
gB
gP
wR1
qU
gP
gB
gP
wR1
qV
gP
gB
gP
aL1
qQ
Cmp_log_nn(oR
dS2
qX
dS2
qS
dS2
qT
dS2
qU
dS2
qV
dT2
hT1
Cmp_log_np(oR
dT2
dU2
qX
dT2
dU2
qS
dT2
dU2
qT
dT2
dU2
qU
dT2
dU2
qV
dT2
hQ
h91
Cmp_log_pn(oR
hQ
qU2
qX
hQ
qU2
qS
hQ
qU2
qT
hQ
qU2
qU
hQ
qU2
qV
hQ
gB
hT1
Cmp_log_pp(oR
hQ
gB
dU2
qX
hQ
gB
dU2
qS
hQ
gB
dU2
qT
hQ
gB
dU2
qU
hQ
gB
dU2
qV
hQ
gB
hQ
h91
gV3(oR(x
d8))qX(x
d8))qS(x
d8))qT(x
d8))qU(x
d8))qV(x
d8
qQ
gW3(oR(x
d9))qX(x
d9))qS(x
d9))qT(x
d9))qU(x
d9))qV(x
d9
qQ
oH3(oR(dW2
qX(dW2
qS(dW2
qT(dW2
qU(dW2
qV(-x),q51
Cmp_powx_n_n(oR
hU1
qX
hU1
qS
hU1
qT
hU1
qU
hU1
qV
oD
qN-hR
qQ
Cmp_powx_n_p(oR
oD
qN
hR
aZ
qX
oD
qN
hR
aZ
qS
oD
qN
hR
aZ
qT
oD
qN
hR
aZ
qU
oD
qN
hR
aZ
qV
oD
qN
hR/q0(3l)qQ
Cmp_powx_nn(oR
oD-wG
qX
oD-wG
qS
oD-wG
qT
oD-wG
qU
oD-wG
qV
oD-q51
Cmp_powx_np(oR
oD
wG
qX
oD
wG
qS
oD
wG
qT
oD
wG
qU
oD
wG
qV
oD
q51
Cmp_powx_p_n(oR
qN
qV2
qX
qN
qV2
qS
qN
qV2
qT
qN
qV2
qU
qN
qV2
qV
qN
oE-hR
qQ
Cmp_powx_p_p(oR
qN
oE
hR
aZ
qX
qN
oE
hR
aZ
qS
qN
oE
hR
aZ
qT
qN
oE
hR
aZ
qU
qN
oE
hR
aZ
qV
qN
oE
hR/q0(3l)qQ
Cmp_powx_pn(oR
qN
qX2
qX
qN
qX2
qS
qN
qX2
qT
qN
qX2
qU
qN
qX2
qV
qN
gC),-q51
Cmp_powx_pp(oR
qN
gC),wG
qX
qN
gC),wG
qS
qN
gC),wG
qT
qN
gC),wG
qU
qN
gC),wG
qV
qN
gC),q51
Cmp_powy_n_n(oR
qY2
qX
qY2
qS
qY2
qT
qY2
qU
qY2
qV
qP-hZ
qQ
Cmp_powy_n_p(oR
qP-d0
qX
qP-d0
qS
qP-d0
qT
qP-d0
qU
qP-d0
dS3
qP
q0(6.1l)qQ
Cmp_powy_nn(oR
qP-g2-wG
qX
qP-g2-wG
qS
qP-g2-wG
qT
qP-g2-wG
qU
qP-g2-wG
dS3-q51
Cmp_powy_np(oR
qP-g2
wG
qX
qP-g2
wG
qS
qP-g2
wG
qT
qP-g2
wG
qU
qP-g2
wG
dS3
q51
Cmp_powy_p_n(oR
qP
hZ))qX
qP
hZ))qS
qP
hZ))qT
qP
hZ))qU
qP
hZ))qV
qP
hZ
qQ
Cmp_powy_p_p(oR
qP
d0
qX
qP
d0
qS
qP
d0
qT
qP
d0
qU
qP
d0
qV
qP
g2
qP
q0(6.1l)qQ
Cmp_powy_pn(oR
qP
g2-wG
qX
qP
g2-wG
qS
qP
g2-wG
qT
qP
g2-wG
qU
qP
g2-wG
qV
qP
g2-q51
Cmp_powy_pp(oR
qP
g2
wG
qX
qP
g2
wG
qS
qP
g2
wG
qT
qP
g2
wG
qU
qP
g2
wG
qV
qP
g2
q51
Cmp_sinh(oR
oF
gE)qX
oF
gE)qS
oF
gE)qT
oF
gE)qU
oF
gE)qV
oF
h91
oI3(oR(q31
qX(q31
qS(q31
qT(q31
qU(q31
qV(x*gZ1
16l
qQ
gJ3(oR(x*x)dN1)qX(x*x)dN1)qS(x*x)dN1)qT(x*x)dN1)+-q0(16l)*fp_greaterOrEq((x*x)dN1)qV(x*x),-q0(16l
qQ
Cmp_tanh(oR
hO))qX
hO))qS
hO))qT
hO))qU
hO))qV
hO
qQ
Cmp_tanh_outrange(oR
q41
qX
q41
qS
q41
qT
q41
qU
q41
qV
fp_tanh(gZ1
2l
qQ
Cmpeq
gF1(q0(gE1+fp_equal(q0(4l),q51
Cmpge
gW1
q0(3l),o82)+x+dR1
q0(8l),q51
Cmpgt
oT1
q0(3l),o82)+x
g62
q0(8l),q51
Cmple
gW1
q0(gE1+dR1
q0(4l),q0(8l
qQ
Cmplt
oT1
q0(gE1;}
q3
Cmpne(oU1
q0(gE1+g32(q0(4l),q51
Cos(qK
cos(oT2
Cos_deg(qK
cos(d2r(1.1))h81
Cosh(qK
cosh(oT2
Cosh_deg(qK
cosh(d2r(1.1))h81
Deg(qH
r2d(y)+r2d(x)+r2d(y)*q0(4l);}
q3
Degxmul(aY1
fp_acos(x))*wW1;}
q3
Div(qK(o82/wG
h81
Div1(qK
x/aL1
h81
Divxx(qK
x+x/x
h81
gO3
oG2
q0(14l);}
q3
Dupaddmulh(qK
x;}
q3
Dupaddmulmul7(qH
y*x*q0(14l);}
q3
Dupaddmulmulh(qH
y*x;}
q3
h53(qC;q0
b2[2
mE1
userDefFuncSub<q0>((b2[0]=(fp_min(x,x)),b2[1]=(w42
x,x)),b2
qQ
gP3(qC;q0
b3[2
mE1
userDefFuncSub<q0>((b3[0]=(x
m51
x)),b3[1]=(x+w42
x,x)),b3
qQ
gQ3(qC,&y
q32;q0
b4[2
mE1
userDefFuncSub<q0>((b4[0]=(fp_min(y,x)),b4[1]=(w42
y,x)),b4
qQ
gR3(qK
x
d02
Dupxpowmul
a72
q51
Eq0
gF1(x,aS1)+fp_equal(aS1,m1
Eq1
gF1(fp_not(gZ1
1l
qQ
Exp(oW3
oT2
Exp2(oW3
1.1*0.693147180559945309417232121458176568075500134)h81
Exp2div(qH
x/gY2
y);}
q3
Exp2log2(qK
hB
gY2
x
qQ
Exp2xpow(g12
gY2
x),1506.0);}
q3
Expdiv(qH
x/fp_exp(y);}
q3
Explog(qK
hQ
fp_exp(x
qQ
Explog2(qK
x/fp_const_log2<q0>();}
q3
Explog10(qK
x/fp_const_log10<q0>();}
q3
Expxpow(g12
qJ1
1506.0);}
q3
Floor(qK
floor(oT2
Floorneg(qK
fp_floor(-m1
oJ3(wM
fp_abs(dV
fp_abs(x))qS
fp_abs(gZ1
0l
aJ1
gP1
Ge0_neg(wM
aD
dV
aD
x))qS
aD
gZ1
0l
aJ1
aD
x
qQ
Ge0_pos(wM
fp_acos(dV
fp_acos(x))qS
fp_acos(gZ1
0l
aJ1
fp_acos(x
qQ
oK3(wM
fp_abs(x
o5
fp_abs(x))qS
fp_abs(gZ1
dI1
gP1
Ge1_neg(wM
aD
x
o5
aD
x))qS
aD
gZ1
dI1
aD
x
qQ
Ge1_pos(wM
fp_acos(x
o5
fp_acos(x))qS
fp_acos(gZ1
dI1
fp_acos(x
qQ
Gehalf(qK
d1,oE1
oL3(mX
gQ1
aO1
fp_abs(x))wD
gQ1
aQ1
gP1
Gt0_neg(mX
aD
dT3
aO1
aD
x))wD
aD
dT3
aQ1
aD
x
qQ
Gt0_pos(mX
fp_acos(dT3
aO1
fp_acos(x))wD
fp_acos(dT3
aQ1
fp_acos(x
qQ
oM3(mX
fp_abs(oP3
fp_abs(x))wD
fp_abs(oQ3
gP1
Gt1_neg(mX
aD
oP3
aD
x))wD
aD
oQ3
aD
x
qQ
Gt1_pos(mX
fp_acos(oP3
fp_acos(x))wD
fp_acos(oQ3
fp_acos(x
qQ
Gtminushalf(qK
oL,-oE1
Hypot(qK
sqrt(5.0*5.0+4.0*4.0)h81
Immsub(qK
x-o82;}
q3
Int(qK
x+(((((gJ1
1.1l))-gJ1
1.6l)))-gJ1
1.5l)))-gJ1-1.1l)))-gJ1-1.6l)))-gJ1-1.5l)qQ
Intceil(qK
fp_ceil
oX1
Intfloor(qK
fp_floor
oX1
Intint(qK
fp_int
oX1
Inttrunc(qK
fp_trunc
oX1
Invdiv(qH
y/(aL1/m1
Invinv
aK1(aL1/m1
Invmul(qH
y*(aL1/m1
Leminushalf(qK
dX,-oE1
Log(aP1
h81
Log2(aP1*1.4426950408889634073599246810018921374266+x;}
q3
Log2exp1
aR1
hB
x
qQ
Log2exp2(qK
gY2
hB
fp_acos(x)qQ
Log10(aP1*0.43429448190325182765112891891660508229+x;}
q3
Logexp1
aR1
hQ
x
qQ
Logexp2
aR1
hQ
fp_acos(x)qQ
Logmul(qK
hQ
m9
Logmul2(qK
hB
m9
Logmul10(qK
gP
m9
Lt0
oT1
fp_abs(x),x-x)-m2,x-m1
Lthalf(qK
m2,oE1
Max(qK
o82
h81
Min(qK
q0(4l)h81
Mod(qK
fp_mod(o82,wG
h81
Mul(qK(g02
wG
h81
Mul1
oG2
aL1
h81
Mul1b(qK((x*q0(0.2l))mV))h81
Mul2(qK
x
h81
Mul4(qH
y*(x*gE*wW1+(y*gE*wW1;}
q3
Mul_zero(qH(x*y+aL1)+(aD
x)+aD
y))*hQ
x)*y*x*d22
Mulminus1
oG2-1.0;}
q3
Mulneg(qK-(x
mV
qQ
dP3(qK
x/q0(4l)h81
Neg(qK((-((5.0))))h81
Negabs(qK
fp_abs(-m1
Negadd(qH
x+(-y);}
q3
Negceil(qK-wR2
m1
Negcos(qK
gX2-m1
Negcosh(qK
hZ2-m1
Negdiv(qK(-x)/o82;}
q3
Negfloor(qK-fp_floor(m1
Negmul(qK(-x)d02
Negneg(qK-(-(-(-(-(-(x))))qQ
Negnot(qB2-m1
Negsin(qK
aD-m1
Negsinh(qK
fp_sinh(-m1
Negsqr
oG2
x;}
q3
Negsub(qH
x-(-y);}
q3
Negtan(qK
qZ2-m1
Negtanh(qK
fp_tanh(-m1
Neq0(qK(w8,aS1))+(g32(aS1,x
qQ
Neq1(oU1
fp_not(gZ1
1l
qQ
Not(qB2
d52
h81
Not_eq(qH
x!=oV1
Not_ge(qH
x<oV1
Not_gt(qH
x<=oV1
Not_le(qH
x>oV1
Not_lt
g52
Not_ne(qH
x==oV1
Notnot(qK
fp_notNot(m1
h63(qB2
m1
gS3(qB2
m1
Or(qK
wS1
gE1+wS1
5l),aS1)+wS1
0l),o82)+wS1
0l),dR3
Pow_neg(qK
pow(-0.25,4.0)h81
Pow_pos(qK
pow(1.1,7.1)h81
Powdiv(qH
x/qP
y);}
q3
Powhalf
a72
oE1
Powinv(qH
aL1/qP
y);}
q3
Powminushalf
a72-oE1
Powminusone
a72-q0(1.0l
qQ
Powminusthird
a72(q0(-1.0l)/q0(3.0l)qQ
Powthird
a72(m6/q0(3.0l)qQ
Powxpow(g12
qP
1.7),1506.0);}
q3
Rad(qH
d2r(y)+d2r(x)+d2r(x)*q0(4l);}
q3
Radxmul(qK
gX2
d2r(x+x+x+x
qQ
Rsqrt(qK
1.0/q22
m1
Sin(qK
sin(oT2
Sin_deg(qK
sin(d2r(1.1))h81
Sincos_cci(qK
mI)+aL1/gX2
m1
Sincos_cic
aK1
mI)+gX2
m1
Sincos_sc
dK2
gX2
m1
Sincos_sci
dK2
aL1/gX2
m1
Sincos_sis
aK1
aD
x)+aD
m1
Sincos_ssi
dK2
aL1/aD
m1
Sincos_tan(qK
qZ2
m1
Sincos_tit
aK1
qZ2
x)+qZ2
m1
Sincos_tti(qK
qZ2
x)+aL1/qZ2
m1
Sinh(qK
sinh(oT2
Sinh_deg(qK
sinh(d2r(1.1))h81
o63(qK(-x)*x;}
q3
o73
oG2(-m1
Sqr_xx
oG2
x;}
q3
hZ3(qH
y*-x*x;}
q3
d03(qH
y*x*-x;}
q3
o83(qH
y*x*x;}
q3
Sqreq0
gF1(x*x,aS1)+fp_equal(aS1,x*m1
Sqrlog(qK
hQ
x*m1
Sqrlog2(qK
hB
x*m1
Sqrlog10(qK
gP
x*m1
oN3
gF1(x*x,aS1)+fp_equal(aS1,x*m1
Sqrsqrt(qK
q22
x*m1
Sqrt(qK
sqrt(oT2
Sqrtsqr1(g12
q22
gZ1
2l
qQ
Sqrtsqr2(g12
q22
fp_acos(x)),q0(2l
qQ
Sqrxpow(qK
wE,2402.0);}
q3
Sqrxpow_nonint(qK
wE,3.5);}
q3
Sub(qK
o82-q0(3l)h81
Sub0(qK
x-aS1
h81
Subxx(qK
x+(x-x)+x+(aL1-x+m1
Tan(qK
tan(oT2
Tan_deg(qK
tan(d2r(1.1))h81
Tanh(qK
tanh(oT2
Tanh_deg(qK
tanh(d2r(1.1))h81
Trunc(qK
1.0+x;}
q3
o93(qB2
x+q51
gT3(qK
gR1+q51
Xmulrad(qK
gX2
d2r(x
g92
qQ
Xmulsinhneg(qK-fp_sinh(x
mV
qQ
Xmulsinneg(qK-aD
x
mV
qQ
Xmultanhneg(qK-fp_tanh(x
mV
qQ
Xmultanneg(qK-qZ2
x
mV
qQ
Xsqryfsqrhypot(qK
fp_hypot(dT2
hB
x
qQ
Xsqrysqrhypot(qH
fp_hypot(dT2
y);}
q3
Xxdup(qK
x-x;}
q3
Xxfdup(qK
x-x;}
q3
d13(qH
y*fp_abs(x)*fp_abs(m1
Ypowxpow(g12
qP
38.5),5.0);}
}
namespace
cpp_11optimizer_constaddmul{using
namespace
FUNCTIONPARSERTYPES;q3
t1
g8(aL1/a)d02
t2
g8
g02
a;}
q3
t3
g8
o82/a;}
q3
t4(hE(a
mV))*b;}
q3
t5(hE(a
mV))/b;}
q3
t6(hE(aL1/a)*b;}
q3
t7(hE(aL1/a)/b;}
q3
t8(hE
dO1*(mL
mV
qQ
t9(hE
dO1/(mL
mV
qQ
t10(hE
mL*(o82/a);}
q3
t11(hE
mL/(q0(50l)/a);}
q3
t12
g8(-a)dA1
t13(hE
o82+(a*b);}
q3
t14(hE
o82-(a*b);}
q3
t15(hE(a+o82)+mL;}
q3
t16(hE(a+o82)-mL;}
q3
t17(hE(-a)+mL;}
q3
t18(hE(-a)-mL;}
q3
t19(hE
b+(dO1+q0(5l
qQ
t20(hE
b-(dO1+q0(5l
qQ
t21(hE
mL+(o82
oR3
t22(hE
mL-(o82
oR3
t23(hV1*b
w03
t24(hV1
mV)w03
t25(hV1
mV))*a;}
q3
t26(hE(dO1/b
w03
t27(hE(dO1/b)*a;}
q3
t28(hE((-a)/b)d02
t29
g22/b)*a;}
q3
t30(w4
b=vars[0
mE1(aT1/b)d02
t31(hE
b*(aT1/oR3
t32
g22-b)-a;}
q3
t33
g22-b)+a;}
q3
t34(hE((a+aT1)-b)dA1
t35(hE((-a)-b)dA1
t36
g8(aT1-fp_abs(a
mY
5l);}
q3
t37(hE((aT1-b)+a)dA1
t38(hE
a22(g02
b+dO1),aS1)*aL1
g62(mL),aS1)*wW1;}
q3
t39
g8(a+aT1)d02
t40(hE(b+(a*aT1))d02
t41(hE(b-(a*aT1))d02
t42
g8(a+q0(7l
mY
5l);}
q3
t43
g8(a*aT1)mV);}
}
namespace
cpp_20optimizer_optimizations{using
namespace
FUNCTIONPARSERTYPES;q3
Abscos(qK
gX2
fp_abs(x))+fp_abs(m1
Abscosh(qK
hZ2
fp_abs(x))+fp_abs(m1
Abseq0
gF1(gQ1+fp_equal(aS1,gP1
oF3
gF1(gQ1+fp_equal(aS1,gP1
o43(qC;q0
b5[2
mE1
userDefFuncSub<q0>((b5[0]=(fp_greaterOrEq(fp_abs(x),wG),b5[1]=(fp_greaterOrEq(gQ1),b5
qQ
o53(qC;q0
b6[2
mE1
userDefFuncSub<q0>((b6[0]=(a22
fp_abs(x),wG),b6[1]=(a22
gQ1),b6
qQ
Acoscos(qK
gX2
fp_acos(x
qQ
Acoshsinh(qK
fp_sinh(fp_acosh(x
qQ
gF3(qH
g02(q0(4l)+x+y);}
q3
Addlog(qH
hQ
x)+hQ
y);}
q3
qK3(qH
g02(q0(4l)*y+m1
g03(qH-o82+(g02
x*y);}
q3
g13(qH-g02
y+(g02
m1
Addsin2cos2(g12
aD
x),gE+a42
mI),q0(2l
qQ
Asinhcosh(qK
hZ2
fp_asinh(x
qQ
Asinsin(qK
aD
fp_asin(x
qQ
qS3
gS2
mS
d5
mP2
gF1
gA
qQ
mQ2
gS2
dL2
g23(qH((gG1
mZ
mR2(qH((gG1
aU1
m72
gS2*-m0
m82
gS2*m0
aO2
gS2
o52
aP2
gS2*q0
h6
Cmpeq_pow_imm_negneg
gF1(d6
qQ
Cmpeq_pow_imm_negpos
gF1(oI
Cmpeq_pow_imm_posneg
gF1(x*mT
Cmpeq_pow_imm_pospos
gF1(x*x
gK1
Cmpeq_pow_imm_pospos_base
gF1(q0(dG
Cmpeq_powpow_imm_base(qH
fp_equal(dK
qT3(qH
d1
mS
d5
mT2(qK
fp_greaterOrEq
gA
qQ
mU2(qH
d1
dL2
g43(qH((d1
mZ
mV2(qH((d1
aU1
m92(qH
d1*-m0
mA2(qH
d1*m0
aQ2(qH
d1
o52
aR2(qH
d1*q0
h6
Cmpge_pow_imm_negneg(wM
d6
qQ
Cmpge_pow_imm_negpos(wM
oI
Cmpge_pow_imm_posneg(qK
d1*mT
Cmpge_pow_imm_pospos(qK
d1*x
gK1
Cmpge_pow_imm_pospos_base(wM
q0(dG
Cmpge_powpow_imm_base(qH
fp_greaterOrEq(dK
qU3
w52
mS
d5
mW2(qK
fp_greater
gA
qQ
mX2
w52
dL2
g53(qH((oL
mZ
mY2(qH((oL
aU1
mB2
w52*-m0
mC2
w52*m0
aS2
w52
o52
aT2
w52*q0
h6
Cmpgt_pow_imm_negneg(mX
d6
qQ
Cmpgt_pow_imm_negpos(mX
oI
Cmpgt_pow_imm_posneg(qK
oL*mT
Cmpgt_pow_imm_pospos(qK
oL*x
gK1
Cmpgt_pow_imm_pospos_base(mX
q0(dG
Cmpgt_powpow_imm_base(qH
fp_greater(dK
qV3(qH
dX
mS
d5
mZ2(qK
fp_lessOrEq
gA
qQ
q03(qH
dX
dL2
g63(qH((dX
mZ
q13(qH((dX
aU1
mD2(qH
dX*-m0
mE2(qH
dX*m0
aU2(qH
dX
o52
aV2(qH
dX*q0
h6
Cmple_pow_imm_negneg
gW1
d6
qQ
Cmple_pow_imm_negpos
gW1
oI
Cmple_pow_imm_posneg(qK
dX*mT
Cmple_pow_imm_pospos(qK
dX*x
gK1
Cmple_pow_imm_pospos_base
gW1
q0(dG
Cmple_powpow_imm_base(qH
dR1
dK
qW3(qH
m2
mS
d5
q23(qK
fp_less
gA
qQ
q33(qH
m2
dL2
g73(qH((m2
mZ
q43(qH((m2
aU1
mF2(qH
m2*-m0
mG2(qH
m2*m0
aW2(qH
m2
o52
aX2(qH
m2*q0
h6
Cmplt_pow_imm_negneg
oT1
d6
qQ
Cmplt_pow_imm_negpos
oT1
oI
Cmplt_pow_imm_posneg(qK
m2*mT
Cmplt_pow_imm_pospos(qK
m2*x
gK1
Cmplt_pow_imm_pospos_base
oT1
q0(dG
Cmplt_powpow_imm_base(qH
a22
dK
qX3(qH
w8
mS
d5
q53(qK
g32
gA
qQ
q63(qH
w8
dL2
g83(qH((w8
mZ
q73(qH((w8
aU1
mH2(qH
w8*-m0
mI2(qH
w8*m0
aY2(qH
w8
o52
aZ2(qH
w8*q0
h6
Cmpne_pow_imm_negneg(oU1
d6
qQ
Cmpne_pow_imm_negpos(oU1
oI
Cmpne_pow_imm_posneg(qK
w8*mT
Cmpne_pow_imm_pospos(qK
w8*x
gK1
Cmpne_pow_imm_pospos_base(oU1
q0(dG
Cmpne_powpow_imm_base(qH
g32(dK
qY3
oA2(hF
gX1
gO
gX1
gW
gX1
gH(x
mS
y,q0(6l))gZ
x
mS
y,q0(6l))h0(x
mS
d5
q83(qK
q0(hF
gA
mY
gO
gA
mY
gW
gA
mY
gH
gA
mY
g42
g32
gA))h0
gA
qQ
q93(aW1
x+q0
m01+q0
m11+q0
m31+q0
oW2+q0
oX2
dL2
g93
oA2(0x0001l)*((m2
aV1
0x0002l)*((dX
aV1
0x0004l)*((oL
aV1
0x0008l)*((d1
aV1
g42((w8
aV1
0x0020l)*((gG1
mZ
qA3
oA2(0x0001l)*((m2
gY1
0x0002l)*((dX
gY1
0x0004l)*((oL
gY1
0x0008l)*((d1
gY1
g42((w8
gY1
0x0020l)*((gG1
aU1
mJ2(aW1
oG1
gO(oG1
gW(oG1
gH(x*-q0(dZ
gZ
x*-q0(dZ
h0(x*-m0
mK2(aW1
x*q0(dZ
oS3
x*q0(dZ
dM2
x*q0(dZ
dN2
x*q0(dZ
gZ
x*q0(dZ
h0(x*m0
m02(aW1
x*-q0
m01*-q0
m11*-q0
m31*-q0
oW2*-q0
oX2
o52
m12(aW1
x*q0
m01*q0
m11*q0
m31*q0
oW2*q0
oX2*q0
h6
Cmpzz_pow_imm_negneg(dP1
d6
mY
gO(d6
mY
gW(d6
mY
gH(d6))gZ
d6))h0(d6
qQ
Cmpzz_pow_imm_negpos(dP1
wN
oS3
wN
dM2
wN
dN2
wN
gZ
wN
h0(oI
Cmpzz_pow_imm_posneg(dP1
x
m3
oS3
x
m3
dM2
x
m3
dN2
x
m3
gZ
x
m3
h0(x*mT
Cmpzz_pow_imm_pospos(dP1
x*x
m41
gO(x*x
m41
gW(x*x
m41
gH(x*x,q0(25l))gZ
x*x,q0(25l))h0(x*x
gK1
Cmpzz_pow_imm_pospos_base(dP1
q0(oM
oS3
q0(oM
dM2
q0(oM
dN2
q0(oM
gZ
q0(oM
h0(q0(dG
Cmpzz_powpow_imm_base(aW1
oX
oS3
oX
dM2
oX
dN2
oX
gZ
oX
h0(dK
Eq0
gF1(x,aS1)+fp_equal(aS1,m1
Eq1
gF1(fp_not(gZ1
1l
qQ
Expexp_a(qH
fp_exp(x*wW1+y*q0(3l
qQ
Expexp_b
hM
gH2*fp_exp(y+z);}
q3
Expexp_c
hM
fp_exp(x+y*z);}
q3
oJ3(wM
fp_abs(dV
fp_abs(x))qS
fp_abs(gZ1
0l
aJ1
gP1
oK3(wM
fp_abs(x
o5
fp_abs(x))qS
fp_abs(gZ1
dI1
gP1
h73(qH
x==oV1
h83(qH
x==oV1
h93(qH
x>oV1
d53
g52
d63
m21
d73
m21
Gehalf(qK
d1,oE1
oL3(mX
gQ1
aO1
fp_abs(x))wD
gQ1
aQ1
gP1
oM3(mX
fp_abs(oP3
fp_abs(x))wD
fp_abs(oQ3
gP1
hA3(oY
oY2
hB3(qH
x>oV1
hC3(oY
oY2
hD3(qH
x>oV1
d83
g52
d93
g52
dA3
m21
dB3(qH
x!=oV1
If10(qK
gR1)+mC1*fp_not(x)+q0(100l)*oL,q0(0l
mY
1000l)*dX,dR3
qL3(qH
fp_abs(o0(x+gE:(y+o82
qQ
qM3(qH
y+(o0
wW1:q0(5l
qQ
qE3(qH
o0(y+gE:oV1
qF3(qH
o0
y:(y+q0(2l
qQ
mL2(qY
dD1:qA1
qQ
m32(qY
dD1:z;}
q3
mM2(qY
qA1)):dD1;}
q3
m42(qY
z:dD1;}
q3
If_extract_div(qH
y/(o0
x:q0(2l
qQ
qN3(qH
fp_min(y,(o0
wW1:o82
qQ
qO3(qH
y*(o0
wW1:q0(5l
qQ
qG3(qH
o0(y*gE:oV1
qH3(qH
o0
y:(y*q0(2l
qQ
qB3(qY
oH1:qA1
qQ
mN2(qY
oH1:z;}
q3
qC3(qY
qA1)):oH1;}
q3
mO2(qY
z:oH1;}
q3
If_extract_sin(qH
aD
o0
y:m1
If_join_add(oV(aD
y)+qK1(gW2+aL1)+aD
y+aL1
qQ
gA3(qK
x+(m2,wG
gM
q0(13l):q0(14l
qQ
If_join_and(oV
fp_and
wO2
fp_and
dY
If_join_max(oV
w42
aD
y),qK1
fp_max
dY
If_join_min(oV
fp_min
wO2
fp_min
dY
If_join_mul(oV(aD
y)*qK1(gW2+aL1)*aD
y+aL1
qQ
gB3
oG2(m2,wG
gM
q0(30l):q0(40l
qQ
If_join_or(oV
fp_or
wO2
fp_or
dY
Ifabs(qK
q0(1l
mQ
m2
aF
10l
mQ
dX
aF
100l
mQ
oL
aF
1000l
mQ
d1
aF
10000l
mQ
m2
mM
100000l
mQ
dX
mM
1000000l
mQ
oL
mM
10000000l
mQ
d1,aS1)gM
x:-x
qQ
Ifabsnot
hM
fp_truth(aD
x)+q0(1.2l))gM
z:oV1
Ifconst
hM
x+y+z*d22
Ififconst(w4
w
oI1
x
q32,&y=vars[2],&z=vars[3
mE1
aL
o0
aL1:y)gM
z:w)+aL
fp_truth(w)gM
z:aS1)gM
x:y);}
q3
oA3(w4
b
oI1
d
q32
hG
x:b):aL
y)gM
x:d))+aL
b)gM
aL
d)gM
y:x):aL
d)gM
b:x
qQ
dC3(w4
a
oI1
b
q32
hG
a:b):aL
b)gM
a:b
qQ
hE3(w4
a
oI1
b
q32
hG
a:b):aL
b)gM
b:a
qQ
Ifnop(qH
x*aS1+oV1
Ifnot(qY
z:oV1
L_abs
wY1+wW1,wY2
fp_abs(x),y+h91
dD3
wY1*y*fp_abs(y),y+q0(2l
qQ
dE3
wY1*y*-o82,y+q0(2l
qQ
dF3
wY1+wW1,wY2
gR1),y+h91
hF3(qH
x==oV1
hG3(qH
x<oV1
dG3(qH
x<=oV1
dH3
m21
hH3(oY
oY2
hI3(oY
oY2
hJ3(oY
oY2
hK3(qH
x<oV1
hL3(qH
x<oV1
dI3(qH
x<=oV1
dJ3
m21
dK3(qH
x!=oV1
dL3(qH
x<=oV1
dM3(qH
x!=oV1
Lthalf(qK
m2,oE1
gG3
hM
fp_abs(x)*fp_abs(y)*z;}
q3
gH3
hM
w42
z
oZ2
x
w02
w42
z,y),x)mY
10l)*fp_min(z
w02
x
oZ2
y,x)mY
100l)*fp_min(w42
x,y)oZ2
y,z
mY
1000l)*w42
fp_min(x,y)w02
y,z
qQ
Muland2(qH
aA;}
q3
Muland2plus
hM
aA*z;}
q3
Muland3
hM
aA*fp_notNot(z);}
q3
Mulandlt(qH
gR1)*q0(a22
y,aS1
qQ
Mulimmlog(qH
hQ
g02
x*y);}
q3
Mulnor2(qH
q71;}
q3
Mulnor2plus
hM
q71*z;}
q3
Mulnor3
hM
q71*d12);}
q3
Nand2(qH
aM
qQ
hO3
hM
fp_or(aM)),z);}
q3
Nand3
hM
fp_or(aM)),d12
qQ
Negceil(qK
wR2-m1
Negcos(qK
gX2-m1
Negcosh(qK
hZ2-m1
Negfloor(qK
fp_floor(-m1
Negsin(qK
aD-m1
Negsinh(qK
fp_sinh(-m1
Neq0(qK(w8,aS1))+(g32(aS1,x
qQ
Neq1(oU1
fp_not(gZ1
1l
qQ
Nor2(qH
aB
qQ
dN3
hM
wY2
aB)),z);}
q3
Nor3
hM
wY2
aB)),d12
qQ
Not_eq(qH
x!=oV1
Not_ge(qH
x<oV1
Not_gt(qH
x<=oV1
Not_le(qH
x>oV1
Not_lt
g52
Not_ne(qH
x==oV1
Notnot(qH
fp_truth(x)+fp_truth(y);}
q3
Posnot(qB2
aD
x)+q0(1.2l
qQ
Posnotnot(qK
fp_notNot(aD
x)+q0(1.2l
qQ
Powimmaddimmlog(qK
qN
5l),hQ
x)+q0(1l
qQ
Powimmlog(qK
qN
3l),hQ
x))+qN
5l),hQ
x)*aD
x
qQ
Powmulimm_fnen
g72(q0(-8l)qQ
Powmulimm_fnep
g72(q0(4l)qQ
Powmulimm_fnfn(qK
a6,(q0(-7.1l)qQ
Powmulimm_fnfp
g72
q0(7.1l
qQ
Powmulimm_fpfp(qH
qN
5.1l)*x*y,q0(7.1l
qQ
Sub1cos2(qK
aL1-a42
mI),q0(2l
qQ
Sub1sin2(qK
aL1-a42
aD
gZ1
2l
qQ
Trig_modulo(qK
mI+gF)+mI+gF
w12
mI+gF
mV)/gE+mI+gF
w22
mI+gF*w62
aD
x+gF)g82
wW1
wT1
aD
x+gF
mV)/gE
g82
q0
dV2
g82
w62
mI-gF)+mI-gF
w12
mI-gF
mV)/gE+mI-gF
w22
mI-gF*w62
w32)+w32
w12
w32
mV)/gE+w32
w22
w32*aT1/q0(2l
qQ
Trunc_from_if(qK
fp_trunc(x)*q0(4l)+q0(40l)*(x>aS1?wR2
x):fp_floor(x
qQ
o93(qB2
x+q51
gT3(qK
gR1+wG;}
}
namespace
cpp_50regressions{using
namespace
FUNCTIONPARSERTYPES;q3
t1(qK
x+w42
aS1,m61-2l),aS1
qQ
t2(qK
fp_min(x
oZ2
aL1,x
qQ
t3(qC;q0
b7[2
mE1
userDefFuncSub<q0>((b7[0]=(wY2
fp_not(x),gR1))),b7[1]=(fp_or(fp_not(x),gR1))),b7
qQ
t4(qC,&y
q32;q0
b9[2
mE1
userDefFuncSub<q0>((b9[0]=(fp_not(x-y)),b9[1]=(gR1-y)),b9
qQ
t5(qC;q0
b11[2
mE1
userDefFuncSub<q0>((b11[0]=(aD
x)+aL1/aD
x)),b11[1]=(mI)),b11
qQ
t6(qC;q0
b13[2
mE1
userDefFuncSub<q0>((b13[0]=(fp_not(x+wG),b13[1]=(gR1+d52),b13
qQ
t7(qK
x-x;}
q3
t8(qH
wU1-x,-y)+mC1*wU1-x,y)+q0(20l)*wU1
x,-y)+q0(30l)*wU1
x
oC3
t9a
oG2
d22
t9b(hE(a-b)*d22
t9c(hE(a-b)*d22
t9d(hE
a*b*d22
t10
aK1
fp_abs(x)<aL1;}
q3
t11
aR1
x/q0(5e+25l
qQ
t36(qK-(x<aS1?x:-x)+-(x<o82?wW1:q0(3l
qQ
t42(qH
q22
x*x)+q0(1.5l)*(a42
y*y,q0(0.25l)))+fp_hypot(x
oC3
t51(qK
hQ-m1
t57(qK
hZ2
fp_asinh(x
qQ
t59(qH
hZ2
x*x)+fp_tanh(y*y);}
q3
t60(qC,&y
q32;q0
b14[1];q0
b15[2
mE1
fp_or(fp_or(wX1
b14[0]=(x),b14)),userDefFuncSub<q0>((b15[0]=(x),b15[1]=(y),b15))),userDefFuncValue<q0>((0)qQ
t61
hM
g02
x*y+-g02
z;}
}
namespace
cpp_99misc{using
namespace
FUNCTIONPARSERTYPES;q3
t1
oG2
q0(4l)/wW1+(aL1+(wW1+d52)+x*x+x+(m6+d42+q0(3.0l)*q0(4.0l)+q0(5.0l)*q0(6.0l)*q0(7.0l)-q0(8.0l)*q0(9.0l
qQ
t2(qK
wW1*x+aD
x)/q0(.5l)+wW1-aD
x)*aD
m1
t3
hM
wY2
gG1,y),fp_equal(y,x))+m6+d42-q0(3.1l)*q0(4e2l)/q0(.5l)+x*x+y*y+z*z+wY2
x,x)+fp_or(y
oC3
t4(qH(((((x-y)-(((y)*gE-d52))*wG)+aD
x)*gW2)-mI)*aD
y);}
q3
t5(w4
__A5_x08
oI1
o__5_0AB_=vars[1
mE1
a42
__A5_x08,o__5_0AB_);}
q3
t7(qK
mI)*aD
aL1-x)*(aL1-mI/gE*aD
x
mV)qQ
t8(qH
wU1
x,y)+(x>y?x:y);}
q3
t9
hM
q0(1.5l)+x*y-d42+q0(4.0l)/q0(8.0l)+z+z+z+z+x/(y*z);}
q3
t10
hM
aL1+aD
gX2
w42
aL1+wW1+q0(3l)mS
o82,x+y+z)mY
2l);}
q3
t11
hM(-x-x)+y+hQ
qN
1.1l),z
qQ
t12(qK
m6/hQ
qN
10.0l),m6/hQ
x)qQ
t13(qH
qP
d52*qP
wG+a42
y,d52*a42
y,q0(5l
qQ
t14
oG2
gF+aD
wW1*gF)+q0(CONST);}
q3
t15(qH
qP
y)/hQ
y)+hQ
x)/hQ
y)+hQ
qP
y
qQ
t16(qH
x<aS1?(y<aS1?x+y:x-y):(y>aS1?x*y:x+wW1*y);}
q3
t17(qC,&y
q32;q0
b18[1];q0
b19[2];q0
b20[1];q0
b21[2
mE1
wX1
b18[0]=(x),b18))+userDefFuncSub<q0>((b19[0]=(x),b19[1]=(y),b19))+wX1
b20[0]=(y),b20))+userDefFuncSub<q0>((b21[0]=(y+aL1),b21[1]=(x-gE,b21))-aL1;}
q3
t18(qH-(-(-(-o82)))*-qP-a42
y,-h91
t19(qH
m2,y)+mC1*dX,y)+q0(100l)*oL,y)+q0(1000l)*d1,y)+q0(10000l)*gG1,y)+q0(100000l)*w8,y)+wY2
x,y)*wW1+fp_or(x,y)*q0(20l)+fp_not(x)*q0(200l)+fp_truth(x)*q0(2000l)+q0(4l)*fp_not(wY2
m2,y),m2,d52
mY
40l)oX3
fp_not(oL,y)),oL,q0(3l)qQ
t20(qH
wY2
fp_not<q0>(x!=y),fp_not(x))+fp_truth(y);}
q3
t21(qC;q0
b26[1
mE1
wX1
b26[0]=(x),b26))+userDefFuncValue<q0>((0))-o82;}
q3
t22(qH(q0(3.5l)*gE+mC1*(x*d52-(aD
y)*gE+q0(100l)*((x*gE-(y*d52)*wW1+q0(5.0l)/(wW1*gE+qN
1.1l),x*gE+qN
1.1l)*wW1,x*q0(2l
qQ
t23(qK(x/(wW1*fp_acos(q0(0.0l))))*q0(180l);}
q3
t24(qK(fp_min(x
oZ2
aL1,x))m51
wR1/wW1
m51
aL1)*q0(3l)+w42
aS1,m61-2l),aS1
qQ
t25(w4
a
oI1
b
q32,&c=vars[2
mE1
a42
a,a42
b,c))+a42
a,-gE*(-a42
b,gE)+(-a42
b,-c
qQ
t26_deg(qK
aD
d2r(x))+gX2
d2r(x*q0(1.5l)))+r2d(fp_asin(x/q0(110.0l)))+r2d
wX2
x/q0(120.0l)qQ
t27(qH
fp_abs(x)+fp_acos(x)+fp_asin(x)+fp_atan(x)+wU1
x,y)+wR2
x)+mI)+hZ2
x)+m6/qZ2
x)+m6/aD
x)+qP
y);}
q3
t28(qH
gH2+fp_floor(x)+fp_int(x)+hQ
x)+gP
x)+w42
x,y)m51
y)+aL1/mI)+aD
x)+fp_sinh(x)+q22
x)+qZ2
x)+fp_tanh(x)+wR2
y)+fp_trunc(y);}
q3
t29(qH
x-y*aL1;}
q3
t30(qH
x-y*aL1+fp_mod(x,y)+x/a42
y,o92
qN
2l),d52+fp_mod(o82,d52+qP
a42
y,aS1))+qP
oE1
t31
hM
x-(y*(y*(y*-wR1*aL1)+hQ
x*m81),y))-hQ
qP
y))+m81
oF1)+qN
10.0l
oF1/hQ
y+q0(6l))*hQ
z+q0(6l))/hQ
q0(10.0l)))-m81
oF1*y)-qN
5.0l),hQ
x+aT1)/hQ
q0(5.0l)))+m91
d52*m91
gE/m91
q51
t32
hM
x+y/y-m61
3l),wG-x-m71
4l),d52+m71
3l),wG-m61
4l),q0(3l
mY
0l)+(z*aL1)+(x-wW1+gE+(x*a01*gE+y*aS1+fp_min(fp_min(m61
4.0l),x),m6)oZ2
x
oZ2
fp_min(y,q0(4.0l)),z)))+w42
w42
m71
4.0l),x),m6)wO1
w42
y,q0(4.0l)),z)))+(fp_abs(aL1)+fp_acos(m6)+fp_asin(m6)+fp_atan(m6)+wR2
o92
gX2
q0(d32
hZ2
q0(d32
fp_floor(o92
hQ
m6)+aD
q0(d32
fp_sinh(q0(d32
qZ2
m6)+fp_tanh(m6)+wU1
m6,m6))+(x-(y-z))+(x+y)+(x*y)+w42
x
wO1
x
w02
x,x))))*-m6+(z-z)+aL1/aD
x/h01
gW2/h01
qZ2
z/o82)+gP
aL1/qZ2
z/h01
aD
y/h01
mI/o82))+hQ
q0(30l)+x)*hQ
q0(40l)+y)/hQ
q0(50l)+z)+aD
x/q0(57.295779513082320877l))+fp_asin(x/mC1)*q0(57.295779513082320877l)+fp_floor(-x)+aL1/wR2
x)+w81
5l)*q0(0.2l))+(-x+-x+-x+-x+-x+-m1
t33(qH
aD
w81
10l)-x*x+y*y))+gX2
w81
15l)-x*x-y*y))+aD
x*x+y*y);}
q3
t34(w4
t
oI1
rvar0
q32,&rvar1=vars[2],&rvar2=vars[3
mE1
rvar1+rvar2*rvar0-t;}
q3
t35(w4
wY
oI1
A_very_long_variable_name_2
q32,&Yet_a_third_very_long_variable_name=vars[2
mE1
wY-A_very_long_variable_name_2+Yet_a_third_very_long_variable_name*wY;}
q3
t37(qK
o82+q0(7.5l)*q0(8l)/q0(3l)-qN
2l),wG*wW1+fp_mod(aT1,gE
mS
x;}
q3
t38
hM
fp_asinh(x)+q0(1.5l)*fp_acosh(y+q0(3l
mY
2.5l)*fp_atanh(z);}
q3
t39
hM
aD
x+aM1)-mI+aD
y*q0(1.5l)))+z*z*z*aD
z*z*z-x*x-y*y)-aM1*aD
x+aM1)+x*y*z+x*y*q0(2.5l)+x*y*z*mI)+x*y*mI)+x*z*mI)+y*z*q0(2.5l)+(x*y*z*mI)-x*y*z-y*mI)-x*z*y+x*y+x*z-mI)*m1
t40
hM(o2*(o2+wW1*(o2-x*y*(o2+x*(o2;}
q3
t41
hM
x*q0(3l)+x*y+x*z+x*aD
y*z)-qR1
q0(4l)+qR1
x+qR1
y+qR1
z;}
q3
t43(qK
hQ
x*x)+fp_abs(fp_exp(fp_abs(x)+aL1
qQ
t44(qK
wE
w9
8l
mY
1.1l)*wE*x
w9
7l
mY
1.2l
dU3
w9
6l
mY
1.3l
dU3*x
w9
5l
mY
1.4l)*wE
mU
w9
6l
mY
1.5l)oH2
w9
4l
mY
1.6l)oH2*x
w9
3l
mY
1.7l)oH2*x*x,aL1/gE+q0(1.8l)*(q22
a42
fp_abs(-q22
x)),d52
qQ
t45(qK
wE
w9
7l
mY
1.1l
dU3
w9
5l
mY
1.2l)*wE
mU
w9
3l
qQ
t46(qH
fp_abs(fp_floor
wX2
x)+wG)+q0(1.1l)*fp_abs(fp_floor
wX2
y)+q0(1.5l)))g62
fp_acos(x),wX2
y)-mC1
mY
1.2l)*m71-4l),fp_acos(x
mY
1.3l)*m61
9l),fp_acos(x)-q0(9l
qQ
t47
oA2(1.25l)*(gH2+fp_exp(-x
mY
1.5l)*(fp_exp(y)-fp_exp(-y
mY
1.75l)*((gI2+gH2)/gE+d42*((gI2-gH2)/gE+q0(2.25l)*(hZ2
y)+fp_sinh(y
qQ
t48(qK
fp_sinh((hQ
x)/o82+aL1)mV
mY
1.2l)*hZ2(hQ
x)/hQ
gE+aL1)*dU2+fp_not(fp_or
aL
x),fp_not(x/wG
qQ
t49(qK
wU1
aS1,x)+qN-4l)*(x-q0(100l)),q0(3.3l
qQ
t50(qH
fp_or(m2,y),a22
y,x
mY
2l)wV1
m2,y),a22
y,x
mY
4l
qW2
dR1
y,x
mY
8l)wV1
m2,mB1
16l)oX3
m2,mB1
32l
qW2
d1,y
mY
64l)oX3
dX,y),d1,y
mY
128l)wV1
w8,y),gG1,y
mY
256l)wV1
w8,mB1
512l
qW2
gG1,y
qQ
t52(qK
x+(m6+d42+q0(3.0l)+q0(4.0l)-q0(5.0l)-q0(6.0l)-q0(7.0l)-q0(8.0l))/q0(3.0l)+q0(4.0l)*(m6+aD
d42)+gX2
q0(4.0l)*q0(5.0l)+q0(6.0l))/d42)+gX2
a01)*qZ2
q0(0.6l)+q0(0.2l))-q0(1.1l)/hQ
q0(2.1l))*w81
3.3l))+qN
2l),q0(3l
qQ
t53
wY1,y)+q0(4l)oX3
fp_int(x/mC1),fp_int(y/mC1
mY
8l)*((-gV1-x)))+(gV1-fp_not(y)))mY
16l)*(-x+fp_not(y
qQ
t54(qH
m2,y)+dX,y)+oL,y)+d1,y)+gG1,y)+w8,y)+wY2
x,y)+fp_or(x,y)+fp_not(x)+fp_truth(x)+fp_not(wY2
m2,y),m2,d52))+fp_or(fp_not(oL,y)),oL,q0(3l)qQ
t55(qH
a22
qP
q0(1.2l)),aS1)g62
a42
y,q0(2.5l)),aS1)qX
x*x,q0(0l
mY
3l)*a22
a42
y,d52,aS1)wD
qP
wG,dR3
t56(qK
fp_mod(q0(1.75e21l),m1
t58(qH
a22-x,d52+oL*-aL1,o82)+m2*-q0(3l),mC1)+m2*-q0(3l),y*aT1)+m2*q0(4l),y*aT1)+m2*q0(6l),y*-d52
g62-x,q0(11l))g62
o82,-y);}
q3
t59
oT1
mI),aD
x))+(mI)-aD
x))+((fp_sinh(x)-hZ2
x))-(fp_sinh(x)/hZ2
x)mY
q0(1l
qQ
I1
hM
aL1+wW1+q0(3l)-q0(4l)mV)*q0(6l)/q0(3l)+mC1/wW1-q0(9l)%wW1+(x+y-q0(11l)*x+z/mC1+x/(z+q0(31l)qQ
I2
hM((fp_abs(x*y)<q0(20l))||(((x+y)>q0(30l))&&(z>o82)))?fp_min(x,wW1*y):w42
y,z*q0(2l
qQ
I3
hM(x+y)+wW1*(x-z)+q0(3l)*(x*y)+q0(4l)*(y/z)+g02
fp_mod(x,z)+q0(6l)*(x<y)+aT1*(x<=z)+q0(8l)*(x>wW1*z)+q0(9l)*(y>=q0(3l)*z)+mC1*(x+y!=z)+q0(11l)*(q0(100l)+x)+q0(12l)*(q0(101l)-y)+q0(13l)*(q0(102l)*z)+q0(14l)*(q0(103l)/x);}
}
#define Value_t double
#undef Value_t
#undef N
#undef P
#ifdef FP_TEST_WANT_COMPLEX_DOUBLE_TYPE
#define N(x,y) (q0(x,y))
#define Value_t std::complex<double>
namespace
cpp_02unit_functions
wH2
Cos_cd(qK
cos
hX3
Sin_cd(qK
sin(x);}
}
template<>const
wI2
RegressionTests<q0>::Tests[]={W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52
T52
U52
W52
Y52
S62{1,N(-dV3,+200.0),N(dV3,-200.0),N(5.0,-0.025)dP
Cos_cd
qF"/cos_cd"
,"cos(x)"
}
,T62
U62
W62
Y62
S72
T72
U72{1,N(-dV3,+200.0),N(dV3,-200.0),N(5.0,-0.025)dP
Sin_cd
qF"/sin_cd"
,wQ1}
,W72
Y72
S82
T82
U82
W82
Y82
S92
T92
U92
W92
Y92
SA2
TA2
UA2
WA2
YA2
SB2
TB2
UB2
WB2
YB2
SC2
TC2
UC2
WC2
YC2
SD2
TD2
UD2
WD2
YD2
SE2
TE2
UE2
WE2
YE2
SF2
TF2
UF2
WF2
YF2
SG2
TG2
UG2
WG2
YG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
Y13
S23
T23
wI2()}
;
#undef Value_t
#undef N
#endif /*FP_TEST_WANT_COMPLEX_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_COMPLEX_FLOAT_TYPE
#define N(x,y) (q0(APP(x,f),APP(y,f)))
#define Value_t std::complex<float>
namespace
cpp_02unit_functions
wH2
Cos_cf(qK
cos
hX3
Sin_cf(qK
sin(x);}
}
template<>const
wI2
RegressionTests<q0>::Tests[]={W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52
T52
U52
W52
Y52
S62{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)dP
Cos_cf
qF"/cos_cf"
,"cos(x)"
}
,T62
W62
Y62
S72
T72
U72{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)dP
Sin_cf
qF"/sin_cf"
,wQ1}
,W72
UG2
WG2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
Y13
S23
T23
wI2()}
;
#undef Value_t
#undef N
#endif /*FP_TEST_WANT_COMPLEX_FLOAT_TYPE */
#ifdef FP_TEST_WANT_COMPLEX_LONG_DOUBLE_TYPE
#define N(x,y) (q0(APP(x,l),APP(y,l)))
#define Value_t std::complex<long double>
template<>const
wI2
RegressionTests<q0>::Tests[]={Y02
T12
U12
Y12
S22
T22
U22
W22
S32
T32
U32
W32
S42
U42
W42
Y42
S52
U52
Y52
S62
T62
Y62
S72
T72
U72
UG2
WG2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
Y13
S23
T23
wI2()}
;
#undef Value_t
#undef N
#endif /*FP_TEST_WANT_COMPLEX_LONG_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_DOUBLE_TYPE
#define N(x) (x)
#define P(x) N(x##.0)
#define Value_t double
template<>const
wI2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Mod,aC2(aF2
Mod)qA",z"
,g7"mod"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{oJ1
dP
Acos,aC2(aJ2
Acos)qO"/acos"
,"acos"
qV1,gL1
Acos_deg,aC2(aJ2
Acos_deg)qO"/acos_deg"
,"acos"
hC
1
mR
dP
Acosh,aC2(aJ2
Acosh)qO"/"
oB2,oB2
hC
1
mR,gL1
Acosh_deg,aC2(aJ2
Acosh_deg)qO"/acosh_deg"
,oB2
qV1
dP
Asin,aC2(aJ2
Asin)qO"/asin"
,"a"
wQ1}
,{oJ1,gL1
Asin_deg,aC2(aJ2
Asin_deg)qO"/asin_deg"
,"a"
wQ1}
,{oJ1
dP
Asinh,aC2(aJ2
Asinh)qO"/a"
gK2,a92
qV1,gL1
Asinh_deg,aC2(aJ2
Asinh_deg)qO"/asinh_deg"
,a92
hC
a12
dP
Atan,aC2(aJ2
Atan)qO"/atan"
,"atan(x)"
gM1
dP
Atan2,aC2(aJ2
Atan2)qA
oJ"/"
hT2,hT2"(x,y)"
gM1,gL1
Atan2_deg,aC2(aJ2
Atan2_deg)qA
oJ"/atan2_deg"
,hT2"(x"
gT2
1,a12,gL1
Atan_deg,aC2(aJ2
Atan_deg)qO"/atan_deg"
,"atan"
qV1
dP
Atanh,aC2(aJ2
Atanh)qO"/atanh"
,"atanh"
hC-50000,50000,1000
dP
Cbrt,aC2(aJ2
Cbrt)qO"/cbrt"
,"cbrt"
hC-10,10
mR1
dP
Ceil,aC2(aJ2
Ceil)qO"/ceil"
,"ceil"
hC-m4
dP
Cos,aC2(aJ2
Cos)qO"/cos"
,"cos"
hC-m4,gL1
Cos_deg,aC2(aJ2
Cos_deg)qO"/cos_deg"
,"cos"
hC-140,140,N(0.1)dP
Cosh,aC2(aJ2
Cosh)qO"/cosh"
,"cosh"
hC-140,140,N(0.1),gL1
Cosh_deg,aC2(aJ2
Cosh_deg)qO"/cosh_deg"
,"cosh"
hC-90,90,N(0.01)dP
Exp,aC2(aJ2
Exp)qO"/exp"
,"exp"
hC-90,90,N(0.01)dP
Exp2,aC2(aJ2
Exp2)qO"/exp2"
,"exp2"
hC-10,10
mR1
dP
Floor,aC2(aJ2
Floor)qO"/floor"
,"floor(x)"
gM1
dP
Hypot,aC2(aJ2
Hypot)qA
oJ"/hypot"
,"hypot(x,y"
gO2
Tn
Un
SO1{1,N(1e-6),dL1
Log2,aC2(aJ2
Log2)qO"/log2"
,"log2"
hC
N(1e-6),dL1
Log10,aC2(aJ2
Log10)qO"/log10"
,w0}
,T4
U4{2,1,20,1
dP
Pow_neg,aC2(aJ2
Pow_neg)qA
oJ"/pow_neg"
,"pow(-x*0.25,y"
gO2{2,N(0.01),4,N(0.05)dP
Pow_pos,aC2(aJ2
Pow_pos)qA
oJ"/pow_pos"
,qH2
gT2
1,-m4
dP
Sin,aC2(aJ2
Sin)qO"/sin"
,wQ1}
,{1,-m4,gL1
Sin_deg,aC2(aJ2
Sin_deg)qO"/sin_deg"
,wQ1}
,{1,a12
dP
Sinh,aC2(aJ2
Sinh)qO"/sinh"
,gK2
hC
a12,gL1
Sinh_deg,aC2(aJ2
Sinh_deg)qO"/sinh_deg"
,gK2
hC
0,100000,1000
dP
Sqrt,aC2(aJ2
Sqrt)qO"/sqrt"
,"sqrt"
hC
N(-1.3),N(1.3),N(0.05)dP
Tan,aC2(aJ2
Tan)qO"/tan"
,"tan"
hC-89,89
mR1,gL1
Tan_deg,aC2(aJ2
Tan_deg)qO"/tan_deg"
,"tan"
hC-m4
dP
Tanh,aC2(aJ2
Tanh)qO"/tanh"
,"tanh"
hC-m4,gL1
Tanh_deg,aC2(aJ2
Tanh_deg)qO"/tanh_deg"
,"tanh"
hC-4000,dL1
Trunc,aC2(aJ2
Trunc)qO"/trunc"
,"trunc"
hC
0,dD
E_d,aC2(aL2
E_d)wJ"e_d"
,dW3"naturalnumber"
}
,a52
L2_d,aC2(aL2
L2_d)wJ"l2_d"
,dW3"logtwo"
}
,a52
L10_d,aC2(aL2
L10_d)wJ"l10_d"
,dW3"logten"
}
,a52
Pi_d,aC2(aL2
Pi_d)wJ"pi_d"
,dW3"pi"
}
,W4
TO1
UO1
WO1
YO1
SP1
TP1
Wn
Y4
Yn
So
To
S5
T5
U5
W5
wU2
N(0.1)qL
Absyxpow_neg,aC2(aE2
Absyxpow_neg)qZ"absyxpow_neg"
,"(x^-4)^1.5"
}
,wU2
N(0.1)qL
Absyxpow_pos,aC2(aE2
Absyxpow_pos)qZ"absyxpow_pos"
,"(x^4)^1.5"
}
,a62
Acos,aC2(aE2
Acos)qZ"acos"
,"acos"
w72,d62
Acos_deg,aC2(aE2
Acos_deg)qZ"acos_deg"
,"acos"
w72
qL
Acosh,aC2(aE2
Acosh)qZ
oB2,oB2"("
oH
Acosh_deg,aC2(aE2
Acosh_deg)qZ"acosh_deg"
,oB2
w82
Uo
Wo
UP1
WP1
Yo
Sp
YP1
a62
Asin,aC2(aE2
Asin)qZ"asin"
,"asin("
aZ1,d62
Asin_deg,aC2(aE2
Asin_deg)qZ"asin_deg"
,"asin("
aZ1
qL
Asinh,aC2(aE2
Asinh)qZ
a92,a92"("
oH
Asinh_deg,aC2(aE2
Asinh_deg)qZ"asinh_deg"
,a92
w82
Tp
Up
a62
Atan,aC2(aE2
Atan)qZ"atan"
,"atan"
aO
Atan2,aC2(aE2
Atan2)qZ
hT2,hT2"(5,4"
gG,d62
Atan2_deg,aC2(aE2
Atan2_deg)qZ"atan2_deg"
,hT2"(5,4)+x"
}
,Wp{1,0,1,1,d62
Atan_deg,aC2(aE2
Atan_deg)qZ"atan_deg"
,"atan"
aO
Atanh,aC2(aE2
Atanh)qZ"atanh"
,"atanh"
w72
qL
Cbrt,aC2(aE2
Cbrt)qZ"cbrt"
,"cbrt"
aO
Ceil,aC2(aE2
Ceil)qZ"ceil"
,"ceil"
w82
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1
a62
Cos,aC2(aE2
Cos)qZ"cos"
,"cos("
oH
Cos_deg,aC2(aE2
Cos_deg)qZ"cos_deg"
,"cos"
aO
Cosh,aC2(aE2
Cosh)qZ"cosh"
,"cosh("
oH
Cosh_deg,aC2(aE2
Cosh_deg)qZ"cosh_deg"
,"cosh"
w82
Sq
Tq
Ua1
Wa1
Ya1
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
a62
Exp,aC2(aE2
Exp)qZ"exp"
,"exp"
aO
Exp2,aC2(aE2
Exp2)qZ"exp2"
,"exp2"
w82
Tr
Ur{1,wK
Exp2xpow,aC2(aE2
Exp2xpow)qZ"exp2xpow"
,aS
gA2
Wr
Yr
Ss
Ts{1,wK
Expxpow,aC2(aE2
Expxpow)qZ"expxpow"
,aR
gA2
a62
Floor,aC2(aE2
Floor)qZ"floor"
,"floor"
w82
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
Se1
a62
Hypot,aC2(aE2
Hypot)qZ"hypot"
,"hypot(5,4)+x"
}
,Te1
Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Ue1
a62
Log,aC2(aE2
Log)qZ"log"
,"log"
aO
Log2,aC2(aE2
Log2)qZ"log2"
,"log2"
w82
We1
Ye1
a62
Log10,aC2(aE2
Log10)qZ"log10"
,"log10"
w82
Sf1
Tf1
Uf1
Wf1
Yf1
Sg1
Tg1
S7
T7
Ug1
Wg1
Yg1
Sh1
U7
W7
Th1
a62
Mulminus1,aC2(aE2
Mulminus1)qZ"mulminus1"
,"x*-1"
}
,Uh1
Wh1
a62
Neg,aC2(aE2
Neg)qZ"neg"
,"((-((5))))+x"
}
,Y7
Yh1
Su
Si1
Ti1
S8
Tu
Ui1
T8
U8
Wi1
Yi1
W8
Sj1
Tj1
Uj1
Wj1
Yj1
Sk1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Tk1
a62
Pow_neg,aC2(aE2
Pow_neg)w6"_neg"
,"pow(-0.25,4"
gG
qL
Pow_pos,aC2(aE2
Pow_pos)w6"_pos"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv{1,wK
Powxpow,aC2(aE2
Powxpow)LNG_ONLY(0)q5"/powxpow"
,"(x^1.7)"
gA2
Yv
Sw{1,N(0.01),10,N(0.05)qL
Rsqrt,aC2(aE2
Rsqrt)qZ"rsqrt"
,"1/sqrt"
hC
0,1,1
qL
Sin,aC2(aE2
Sin)hP,"sin("
oH
Sin_deg,aC2(aE2
Sin_deg)hP"_deg"
,"sin("
w5
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1
a62
Sinh,aC2(aE2
Sinh)hP"h"
,gK2"("
oH
Sinh_deg,aC2(aE2
Sinh_deg)hP"h_deg"
,gK2
w82
WA
YA
SB
TB
UB
WB
Tm1
Tw
Uw
Ww
Um1
wU2
N(0.1)qL
Sqrsqrt,aC2(aE2
Sqrsqrt)qZ"sqrsqrt"
,"sqrt"
qI2
a62
Sqrt,aC2(aE2
Sqrt)qZ"sqrt"
,"sqrt"
w82
Wm1
Ym1{1,wK
Sqrxpow,aC2(aE2
Sqrxpow)qZ"sqrxpow"
,"(x^2)^2402"
}
,wU2
N(0.1)qL
Sqrxpow_nonint,aC2(aE2
Sqrxpow_nonint)qZ"sqrxpow_nonint"
,"(x^2)^3.5"
}
,Sn1
Tn1
Un1
a62
Tan,aC2(aE2
Tan)qZ"tan"
,"tan("
oH
Tan_deg,aC2(aE2
Tan_deg)qZ"tan_deg"
,"tan"
aO
Tanh,aC2(aE2
Tanh)qZ"tanh"
,"tanh("
oH
Tanh_deg,aC2(aE2
Tanh_deg)qZ"tanh_deg"
,"tanh"
aO
Trunc,aC2(aE2
Trunc)qZ"trunc"
,"trunc"
w82
YB
SC
Yw
Wn1
Yn1
So1
To1
Uo1
Wo1
TC
Sx
UC{1,0,10,N(0.01)qL
Ypowxpow,aC2(aE2
Ypowxpow)qZ"ypowxpow"
,"(x^38.5)^5"
}
,Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
Tx
Ux
Ux1
Wx1
WC
YC
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Wy1
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Tz1
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
Sg
Yz1
S_1
T_1
U_1
W_1
Y_1
S02
T02
Tg
WE1
YE1
SF1
TF1
Ug
U02
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wI2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_FLOAT_TYPE
#define N(x) (APP(x,f))
#define P(x) N(x##.0)
#define Value_t float
namespace
cpp_01unit_operators
wH2
Modf(qC,&z=vars[1
mE1
fmodf(x,z);}
}
namespace
cpp_02unit_functions
wH2
Acosf(qK
acosf
hX3
Acosf_deg(aY1
acosf(x)mP
Acoshf(qK
d72+wA2-1.0f)mP
Acoshf_deg(aY1
fp_acosh(x)mP
Asinf(qK
asinf
hX3
Asinf_deg(aY1
asinf(x)mP
Asinhf(qK
d72+wA2+1.0f)mP
Asinhf_deg(aY1
fp_asinh(x)mP
Atan2f(qH
gB2
x,y
mP
Atan2f_deg(qH
r2d(gB2
x,y)mP
Atanf(qK
atanf
hX3
Atanf_deg(aY1
atanf(x)mP
Atanhf(qK
logf((1.0f+x)/(1.0f-x))*0.5f;}
q0
Cbrtf(qK
fp_cbrt
hX3
Ceilf(qK
ceilf
hX3
Cosf(qK
cosf
hX3
Cosf_deg(qK
cosf(oK1
Coshf(qK
coshf
hX3
Coshf_deg(qK
coshf(oK1
Exp2f(qK
expf(x*fp_const_log2<q0>()mP
Expf(qK
expf
hX3
Floorf(qK
floorf
hX3
Hypotf(qH
wA2+y*y
mP
Log2f(qK
d72)*1.4426950408889634073599246810018921374266f;}
q0
Log10f(qK
log10f
hX3
Logf(qK
d72
mP
Pow_negf(qH
powf(-x*0.25f,y
mP
Pow_posf(qH
powf(x,y
mP
Sinf(qK
sinf
hX3
Sinf_deg(qK
sinf(oK1
Sinhf(qK
sinhf
hX3
Sinhf_deg(qK
sinhf(oK1
Sqrtf(qK
q42
x
mP
Tanf
wS2
hX3
Tanf_deg
wS2(oK1
Tanhf(qK
tanhf
hX3
Tanhf_deg(qK
tanhf(oK1
Truncf(qK
fp_trunc(x);}
}
namespace
cpp_03unit_constants
wH2
E_f(qK
expf(x*0.0f+1.0f
mP
L2_f(qK
d72*0.0f+2.0f
mP
L10_f(qK
d72*0.0f+10.0f
mP
Pi_f(qK
gB2
x*0.0f,-1.0f);}
}
namespace
cpp_10optimizer_bytecode
wH2
Acosf(qK
acosf(0.7f
hU
Acosf_deg(aY1
acosf(0.7f)hU
Acoshf
oM1+q42
1.1f*1.1f-1.0f)hU
Acoshf_deg(aY1
fp_acosh
wC2)hU
Asinf(qK
asinf(0.7f
hU
Asinf_deg(aY1
asinf(0.7f)hU
Asinhf
oM1+q42
1.1f*1.1f+1.0f)hU
Asinhf_deg(aY1
fp_asinh
wC2)hU
Atan2f(qK
gB2
5.0f,wB2
Atan2f_deg(aY1
gB2
5.0f,4.0f)hU
Atanf(qK
atanf
wC2
hU
Atanf_deg(aY1
atanf
wC2)hU
Atanhf(qK
logf((1.0f+0.7f)/(1.0f-0.7f))*0.5f+x;}
q0
Cbrtf(qK
fp_cbrt
wC2
hU
Ceilf(qK
ceilf
wC2
hU
Cosf(qK
cosf
wC2
hU
Cosf_deg(qK
cosf(gS1
Coshf(qK
coshf
wC2
hU
Coshf_deg(qK
coshf(gS1
Exp2f(qK
expf
wC2*0.693147180559945309417232121458176568075500134f
hU
Expf(qK
expf
wC2
hU
Floorf(qK
floorf
wC2
hU
Hypotf(qK
q42
5.0f*5.0f+4.0f*wB2
Log2f
oM1)*1.4426950408889634073599246810018921374266f+x;}
q0
Log10f(qK
log10f
wC2
hU
Logf
oM1
hU
Pow_negf(qK
powf(-0.25f,wB2
Pow_posf(qK
powf
wC2,7.1f
hU
Sinf(qK
sinf
wC2
hU
Sinf_deg(qK
sinf(gS1
Sinhf(qK
sinhf
wC2
hU
Sinhf_deg(qK
sinhf(gS1
Sqrtf(qK
q42
1.1f
hU
Tanf
wS2
wC2
hU
Tanf_deg
wS2(gS1
Tanhf(qK
tanhf
wC2
hU
Tanhf_deg(qK
tanhf(gS1
Truncf(qK
1.0f+x;}
}
template<>const
wI2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Modf,hA
qA",z"
,g7"modf"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{oJ1
dP
Acosf
qF"/acosf"
,"acos"
qV1,gL1
Acosf_deg
qF"/acosf_deg"
,"acos"
hC
1
mR
dP
Acoshf
qF"/acoshf"
,oB2
hC
1
mR,gL1
Acoshf_deg
qF"/acoshf_deg"
,oB2
qV1
dP
Asinf
qF"/asinf"
,"a"
wQ1}
,{oJ1,gL1
Asinf_deg
qF"/asinf_deg"
,"a"
wQ1}
,{oJ1
dP
Asinhf
qF"/asinhf"
,a92
qV1,gL1
Asinhf_deg
qF"/asinhf_deg"
,a92"(x)"
gM1
dP
Atan2f,d82"/atan2f"
,hT2"(x,y)"
gM1,gL1
Atan2f_deg,d82"/atan2f_deg"
,hT2"(x"
gT2
1,a12
dP
Atanf
qF"/atanf"
,"atan"
hC
a12,gL1
Atanf_deg
qF"/atanf_deg"
,"atan"
qV1
dP
Atanhf
qF"/atanhf"
,"atanh"
hC-50000,50000,1000
dP
Cbrtf
qF"/cbrtf"
,"cbrt"
hC-10,10
mR1
dP
Ceilf
qF"/ceilf"
,"ceil"
hC-m4
dP
Cosf
qF"/cosf"
,"cos"
hC-400,400,5,gL1
Cosf_deg
qF"/cosf_deg"
,"cos"
hC-40,40,N(0.025)dP
Coshf
qF"/coshf"
,"cosh"
hC-40,40,N(0.1),gL1
Coshf_deg
qF"/coshf_deg"
,"cosh"
hC-90,90,N(0.01)dP
Exp2f
qF"/exp2f"
,"exp2"
hC-20,20,N(0.01)dP
Expf
qF"/expf"
,"exp"
hC-10,10
mR1
dP
Floorf
qF"/floorf"
,"floor(x)"
gM1
dP
Hypotf,d82"/hypotf"
,"hypot(x,y"
gO2
Tn
Un{1,oO1
Log2f
qF"/log2f"
,"log2"
hC
oO1
Log10f
qF"/log10f"
,"log10"
hC
oO1
Logf
qF"/logf"
,aH1
T4
U4{2,1,20,1
dP
Pow_negf,d82"/pow_negf"
,"pow(-x*0.25,y"
gO2{2,N(0.01),4,N(0.05)dP
Pow_posf,d82"/pow_posf"
,qH2
gT2
1,-m4
dP
Sinf
qF"/sinf"
,wQ1}
,{1,-400,400,5,gL1
Sinf_deg
qF"/sinf_deg"
,wQ1}
,{1,-40,40,N(0.1)dP
Sinhf
qF"/sinhf"
,gK2
hC
a12,gL1
Sinhf_deg
qF"/sinhf_deg"
,gK2
hC
0,100000,1000
dP
Sqrtf
qF"/sqrtf"
,"sqrt"
hC
N(-1.3),N(1.3),N(0.05)dP
Tanf
qF"/tanf"
,"tan"
hC-89,89
mR1,gL1
Tanf_deg
qF"/tanf_deg"
,"tan"
hC-m4
dP
Tanhf
qF"/tanhf"
,"tanh"
hC-m4,gL1
Tanhf_deg
qF"/tanhf_deg"
,"tanh"
hC
a12
dP
Truncf
qF"/truncf"
,"trunc"
hC
0,dD
E_f,oQ"e_f"
,dW3"naturalnumber"
}
,a52
L2_f,oQ"l2_f"
,dW3"logtwo"
}
,a52
L10_f,oQ"l10_f"
,dW3"logten"
}
,a52
Pi_f,oQ"pi_f"
,dW3"pi"
}
,W4
TO1
UO1
YO1
SP1
Wn
Y4
Yn
So
To
S5
W5
a62
Acosf
aK"acosf"
,"acos"
w72,d62
Acosf_deg
aK"acosf_deg"
,"acos(0.7)+x"
}
,Uo
a62
Acoshf
aK"acoshf"
,oB2"("
oH
Acoshf_deg
aK"acoshf_deg"
,oB2
w82
Wo
Yo
Sp
a62
Asinf
aK"asinf"
,"asin("
aZ1,d62
Asinf_deg
aK"asinf_deg"
,"asin(0.7)+x"
}
,Tp
a62
Asinhf
aK"asinhf"
,a92"("
oH
Asinhf_deg
aK"asinhf_deg"
,a92
w82
Up
a62
Atan2f
aK"atan2f"
,hT2"(5,4"
gG,d62
Atan2f_deg
aK"atan2f_deg"
,hT2"(5,4)+x"
}
,Wp
a62
Atanf
aK"atanf"
,"atan("
oH
Atanf_deg
aK"atanf_deg"
,"atan"
aO
Atanhf
aK"atanhf"
,"atanh"
w72
qL
Cbrtf
aK"cbrtf"
,"cbrt"
aO
Ceilf
aK"ceilf"
,"ceil"
w82
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
a62
Cosf
aK"cosf"
,"cos("
oH
Cosf_deg
aK"cosf_deg"
,"cos"
aO
Coshf
aK"coshf"
,"cosh("
oH
Coshf_deg
aK"coshf_deg"
,"cosh"
w82
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
Tr
a62
Exp2f
aK"exp2f"
,"exp2"
w82
Ur
Wr
a62
Expf
aK"expf"
,dJ2
w5
Yr
Ss
Ts
a62
Floorf
aK"floorf"
,"floor"
w82
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
Se1
a62
Hypotf
aK"hypotf"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Ue1
We1
Ye1
a62
Log2f
aK"log2f"
,"log2"
aO
Log10f
aK"log10f"
,"log10"
w82
Sf1
Tf1
a62
Logf
aK"logf"
,"log"
w82
Uf1
Wf1
Yf1
Sg1
Tg1
S7
T7
Sh1
U7
W7
Th1
Y7
Su
Si1
Ti1
S8
Tu
T8
U8
Wi1
Yi1
W8
Tj1
Uj1
Wj1
Yj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
a62
Pow_negf,qG"/pow_negf"
,"pow(-0.25,4"
gG
qL
Pow_posf,qG"/pow_posf"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1
a62
Sinf
a11"f"
,"sin("
oH
Sinf_deg
a11"f_deg"
,"sin(1.1"
gG
qL
Sinhf
a11"hf"
,gK2"("
oH
Sinhf_deg
a11"hf_deg"
,gK2
w82
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww
a62
Sqrtf
aK"sqrtf"
,"sqrt"
w82
Wm1
Ym1
Un1
a62
Tanf
aK"tanf"
,"tan("
oH
Tanf_deg
aK"tanf_deg"
,"tan"
aO
Tanhf
aK"tanhf"
,"tanh("
oH
Tanhf_deg
aK"tanhf_deg"
,"tanh"
aO
Truncf
aK"truncf"
,"trunc"
w82
YB
SC
Yw
Wn1
Yn1
So1
To1
Uo1
Wo1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Wy1
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Tz1
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
S_1
S02
T02
Tg
WE1
YE1
SF1
TF1
Ug
U02
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
SK1
Si
Ti
UK1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wI2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_FLOAT_TYPE */
#ifdef FP_TEST_WANT_GMP_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t GmpInt
template<>const
wI2
RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
Y4
S5
T5
U5
W5
Y5
S6
T6
U6
W6
Y6
S7
T7
U7
W7
Y7
S8
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
WA
YA
SB
TB
UB
WB
YB
SC
TC
UC
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
wI2()}
;
#undef Value_t
#undef P
#endif /*FP_TEST_WANT_GMP_INT_TYPE */
#ifdef FP_TEST_WANT_LONG_DOUBLE_TYPE
#define N(x) (APP(x,l))
#define P(x) N(x##.0)
#define Value_t long double
namespace
cpp_01unit_operators
wH2
Modl(qC,&z=vars[1
mE1
fmodl(x,z);}
}
namespace
cpp_02unit_functions
wH2
Acoshl(mJ
x+gC2-1.0l)mP
Acoshl_deg(aY1
fp_acosh(x)mP
Acosl(qK
acosl
hX3
Acosl_deg(aY1
acosl(x)mP
Asinhl(mJ
x+gC2+1.0l)mP
Asinhl_deg(aY1
fp_asinh(x)mP
Asinl(qK
asinl
hX3
Asinl_deg(aY1
asinl(x)mP
Atan2l(qH
gD2
x,y
mP
Atan2l_deg(qH
r2d(gD2
x,y)mP
Atanhl(mJ(1.0l+x)/(1.0l-x))*0.5l;}
q0
Atanl(qK
atanl
hX3
Atanl_deg(aY1
atanl(x)mP
Cbrtl(qK
fp_cbrt
hX3
Ceill(qK
ceill
hX3
Coshl(qK
coshl
hX3
Coshl_deg(qK
coshl(oK1
Cosl(qK
cosl
hX3
Cosl_deg(qK
cosl(oK1
Exp2l(qK
expl(x*fp_const_log2<q0>()mP
Expl(qK
expl
hX3
Floorl(qK
floorl
hX3
Hypotl(qH
gC2+y*y
mP
Log2l(mJ
x)*1.4426950408889634073599246810018921374266l;}
q0
Log10l(qK
log10l
hX3
Logl(mJ
x
mP
Pow_negl(qH
powl(-x*0.25l,y
mP
Pow_posl(qH
powl(x,y
mP
Sinhl(qK
sinhl
hX3
Sinhl_deg(qK
sinhl(oK1
Sinl(qK
sinl
hX3
Sinl_deg(qK
sinl(oK1
Sqrtl(qK
sqrtl
hX3
Tanhl(qK
tanhl
hX3
Tanhl_deg(qK
tanhl(oK1
Tanl(qK
tanl
hX3
Tanl_deg(qK
tanl(oK1
Truncl(qK
fp_trunc(x);}
}
namespace
cpp_03unit_constants
wH2
E_ld(qK
expl(x*0.0l+1.0l
mP
L2_ld(mJ
x*0.0l+2.0l
mP
L10_ld(mJ
x*0.0l+10.0l
mP
Pi_ld(qK
gD2
x*0.0l,-1.0l);}
}
namespace
cpp_10optimizer_bytecode
wH2
Acoshl(mJ
1.1l+sqrtl(1.1l*1.1l-1.0l)hU
Acoshl_deg(aY1
fp_acosh(1.1l)hU
Acosl(qK
acosl(0.7l
hU
Acosl_deg(aY1
acosl(0.7l)hU
Asinhl(mJ
1.1l+sqrtl(1.1l*1.1l+1.0l)hU
Asinhl_deg(aY1
fp_asinh(1.1l)hU
Asinl(qK
asinl(0.7l
hU
Asinl_deg(aY1
asinl(0.7l)hU
Atan2l(qK
gD2
5.0l,wG2
Atan2l_deg(aY1
gD2
5.0l,4.0l)hU
Atanhl(mJ(1.0l+0.7l)/(1.0l-0.7l))*0.5l+x;}
q0
Atanl(qK
atanl
m5
Atanl_deg(aY1
atanl(1.1l)hU
Cbrtl(qK
fp_cbrt
m5
Ceill(qK
ceill
m5
Coshl(qK
coshl
m5
Coshl_deg(qK
coshl(qL1
Cosl(qK
cosl
m5
Cosl_deg(qK
cosl(qL1
Exp2l(qK
expl(1.1l*0.693147180559945309417232121458176568075500134l
hU
Expl(qK
expl
m5
Floorl(qK
floorl
m5
Hypotl(qK
sqrtl(5.0l*5.0l+4.0l*wG2
Invsincostan(qH
x/aD
y)+x/oP1
x/mD1
x*aD
y)+x*oP1
x*mD1
1.0l/aD
y)+1.0l/oP1
1.0l/mD1
1.0l*aD
y)+1.0l*oP1
1.0l*qZ2
y
mP
Log2l(mJ
1.1l)*1.4426950408889634073599246810018921374266l+x;}
q0
Log10l(qK
log10l
m5
Logl(qK
logl
m5
Pow_negl(qK
powl(-0.25l,wG2
Pow_posl(qK
powl(1.1l,7.1l
hU
Sinhl(qK
sinhl
m5
Sinhl_deg(qK
sinhl(qL1
Sinl(qK
sinl
m5
Sinl_deg(qK
sinl(qL1
Sqrtl(qK
sqrtl
m5
Tanhl(qK
tanhl
m5
Tanhl_deg(qK
tanhl(qL1
Tanl(qK
tanl
m5
Tanl_deg(qK
tanl(qL1
Truncl(qK
1.0l+x;}
}
template<>const
wI2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Modl,hA
qA",z"
,g7"modl"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1
mR
dP
Acoshl
qF"/acoshl"
,oB2
hC
1
mR,gL1
Acoshl_deg
qF"/acoshl_deg"
,oB2
qV1
dP
Acosl
qF"/acosl"
,"acos"
qV1,gL1
Acosl_deg
qF"/acosl_deg"
,"acos"
qV1
dP
Asinhl
qF"/asinhl"
,a92
qV1,gL1
Asinhl_deg
qF"/asinhl_deg"
,a92
qV1
dP
Asinl
qF"/asinl"
,"a"
wQ1}
,{oJ1,gL1
Asinl_deg
qF"/asinl_deg"
,"a"
wQ1
gM1
dP
Atan2l,d82"/atan2l"
,hT2"(x,y)"
gM1,gL1
Atan2l_deg,d82"/atan2l_deg"
,hT2"(x"
gT2
oJ1
dP
Atanhl
qF"/atanhl"
,"atanh"
hC
a12
dP
Atanl
qF"/atanl"
,"atan"
hC
a12,gL1
Atanl_deg
qF"/atanl_deg"
,"atan"
hC-50000,50000,1000
dP
Cbrtl
qF"/cbrtl"
,"cbrt"
hC-10,10
mR1
dP
Ceill
qF"/ceill"
,"ceil"
hC-140,140,N(0.1)dP
Coshl
qF"/coshl"
,"cosh"
hC-140,140,N(0.1),gL1
Coshl_deg
qF"/coshl_deg"
,"cosh"
hC-m4
dP
Cosl
qF"/cosl"
,"cos"
hC-m4,gL1
Cosl_deg
qF"/cosl_deg"
,"cos"
hC-90,90,N(0.01)dP
Exp2l
qF"/exp2l"
,"exp2"
hC-90,90,N(0.01)dP
Expl
qF"/expl"
,"exp"
hC-10,10
mR1
dP
Floorl
qF"/floorl"
,"floor(x)"
gM1
dP
Hypotl,d82"/hypotl"
,"hypot(x,y"
gO2
Tn
Un{1,oO1
Log2l
qF"/log2l"
,"log2"
hC
oO1
Log10l
qF"/log10l"
,"log10"
hC
oO1
Logl
qF"/logl"
,aH1
T4
U4{2,1,20,1
dP
Pow_negl,d82"/pow_negl"
,"pow(-x*0.25,y"
gO2{2,N(0.01),4,N(0.05)dP
Pow_posl,d82"/pow_posl"
,qH2
gT2
1,a12
dP
Sinhl
qF"/sinhl"
,gK2
hC
a12,gL1
Sinhl_deg
qF"/sinhl_deg"
,gK2
hC-m4
dP
Sinl
qF"/sinl"
,wQ1}
,{1,-m4,gL1
Sinl_deg
qF"/sinl_deg"
,wQ1}
,{1,0,100000,1000
dP
Sqrtl
qF"/sqrtl"
,"sqrt"
hC-m4
dP
Tanhl
qF"/tanhl"
,"tanh"
hC-m4,gL1
Tanhl_deg
qF"/tanhl_deg"
,"tanh"
hC
N(-1.3),N(1.3),N(0.05)dP
Tanl
qF"/tanl"
,"tan"
hC-89,89
mR1,gL1
Tanl_deg
qF"/tanl_deg"
,"tan"
hC
a12
dP
Truncl
qF"/truncl"
,"trunc"
hC
0,dD
E_ld,oQ"e_ld"
,dW3"naturalnumber"
}
,a52
L2_ld,oQ"l2_ld"
,dW3"logtwo"
}
,a52
L10_ld,oQ"l10_ld"
,dW3"logten"
}
,a52
Pi_ld,oQ"pi_ld"
,dW3"pi"
}
,W4
YO1
SP1
Wn
Y4
Yn
So
To
S5
W5
Uo
a62
Acoshl
aK"acoshl"
,oB2"("
oH
Acoshl_deg
aK"acoshl_deg"
,oB2
w82
Wo
a62
Acosl
aK"acosl"
,"acos"
w72,d62
Acosl_deg
aK"acosl_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp
a62
Asinhl
aK"asinhl"
,a92"("
oH
Asinhl_deg
aK"asinhl_deg"
,a92
w82
Up
a62
Asinl
aK"asinl"
,"asin("
aZ1,d62
Asinl_deg
aK"asinl_deg"
,"asin("
aZ1
qL
Atan2l
aK"atan2l"
,hT2"(5,4"
gG,d62
Atan2l_deg
aK"atan2l_deg"
,hT2"(5,4)+x"
}
,Wp
a62
Atanhl
aK"atanhl"
,"atanh"
w72
qL
Atanl
aK"atanl"
,"atan("
oH
Atanl_deg
aK"atanl_deg"
,"atan"
aO
Cbrtl
aK"cbrtl"
,"cbrt"
aO
Ceill
aK"ceill"
,"ceil"
w82
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
a62
Coshl
aK"coshl"
,"cosh("
oH
Coshl_deg
aK"coshl_deg"
,"cosh"
aO
Cosl
aK"cosl"
,"cos("
oH
Cosl_deg
aK"cosl_deg"
,"cos"
w82
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
Tr
a62
Exp2l
aK"exp2l"
,"exp2"
w82
Ur
Wr
a62
Expl
aK"expl"
,dJ2
w5
Yr
Ss
Ts
a62
Floorl
aK"floorl"
,"floor"
w82
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
a62
Hypotl
aK"hypotl"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6{2,N(-0.7),N(0.7),N(0.28)qL
Invsincostan,hA
dI2"invsincostan"
,"x/sin("
dQ1"cos"
w92"tan"
w92"csc"
w92"sec"
w92"cot(y"
o42"  1/sin(y"
o42" 1/cos(y"
o42" 1/tan(y"
o42" 1/csc(y"
o42" 1/sec(y"
o42" 1/cot("
oS2
a62
Log2l
aK"log2l"
,"log2"
aO
Log10l
aK"log10l"
,"log10"
aO
Logl
aK"logl"
,"log"
w82
Uf1
Wf1
Yf1
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Wj1
Yj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
a62
Pow_negl,qG"/pow_negl"
,"pow(-0.25,4"
gG
qL
Pow_posl,qG"/pow_posl"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1
a62
Sinhl
a11"hl"
,gK2"("
oH
Sinhl_deg
a11"hl_deg"
,gK2
aO
Sinl
a11"l"
,"sin("
oH
Sinl_deg
a11"l_deg"
,"sin("
w5
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww
a62
Sqrtl
aK"sqrtl"
,"sqrt"
w82
Un1
a62
Tanhl
aK"tanhl"
,"tanh("
oH
Tanhl_deg
aK"tanhl_deg"
,"tanh"
aO
Tanl
aK"tanl"
,"tan("
oH
Tanl_deg
aK"tanl_deg"
,"tan"
aO
Truncl
aK"truncl"
,"trunc"
w82
YB
SC
Yw
Uo1
Wo1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
S02
T02
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wI2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_LONG_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_LONG_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t long
template<>const
wI2
RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
WO1
TP1
Y4
S5
T5
U5
W5
UP1
WP1
YP1
UQ1
UU1
WU1
YU1
UY1
WY1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1
Ua1
Wa1
Ya1
Y5
S6
T6
U6
W6
Sb1
Tb1
Ub1
Sc1
Yc1
Ud1
Te1
Y6
Sg1
S7
T7
Ug1
Wg1
Yg1
U7
W7
Uh1
Wh1
Y7
Yh1
S8
Ui1
T8
U8
W8
Sj1
Wj1
Yj1
Sk1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Tk1
WA
YA
SB
TB
UB
WB
Tm1
Um1
Sn1
Tn1
Un1
YB
SC
TC
UC
Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
Ux1
Wx1
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
Yx1
Sy1
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Yz1
T_1
U_1
W_1
Y_1
Tg
Ug
U02
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
wI2()}
;
#undef Value_t
#undef P
#endif /*FP_TEST_WANT_LONG_INT_TYPE */
#ifdef FP_TEST_WANT_MPFR_FLOAT_TYPE
#define N(x) (q0(#x,0))
#define P(x) N(x)
#define Value_t MpfrFloat
static
const
q0
a21("0.5"
,0),o62("0.25"
,0),mflit1_1("1.1"
,0),mflit0_7("0.7"
,0),mflit1_6("1.6"
,0),mflit1_5("1.5"
,0),mflitm1_1("-1.1"
,0),mflitm1_6("-1.6"
,0),mflitm1_5("-1.5"
,0),mflitm0_25("-0.25"
,0),dC2("7.1"
,0),mflit0_015625("0.015625"
,0),mflit0_0625("0.0625"
,0),mflit5_0625("5.0625"
,0),mflit1_2("1.2"
,0),mflitm5_1("-5.1"
,0),mflitm7_1("-7.1"
,0),mflit5_1("5.1"
,0),mflit_5(".5"
,0),mflit3_1("3.1"
,0),mflit4e2("4e2"
,0),mflit3_5("3.5"
,0),mflit57_295779513082320877("57.295779513082320877"
,0),mflit0_2("0.2"
,0),mflit7_5("7.5"
,0),dD2("2.5"
,0),mflit1_3("1.3"
,0),mflit1_4("1.4"
,0),mflit1_7("1.7"
,0),mflit1_8("1.8"
,0),mflit1_25("1.25"
,0),mflit1_75("1.75"
,0),mflit2_25("2.25"
,0),mflit3_3("3.3"
,0),mflit0_6("0.6"
,0),mflit2_1("2.1"
,0),mflit1_75e21("1.75e21"
,0);namespace
cpp_01unit_operators
wH2
And_d
oA2(g31?fp_abs(y)>=a21:q0(0)mP
Div_d(qH(x-o62)/y;}
q0
Divmul_d
hM
x*y*x*x/z*(x-o62
mP
Modm(qC,&z=vars[1
mE1
x%z;}
q0
Not_d(qK
oR1<a21
mP
Notnot_d(qK
q0(g31
mP
Or_d(qH
oR1<a21?fp_abs(y)>=a21:q0(1));}
}
namespace
cpp_02unit_functions
wH2
Acoshm(qB
acosh
hX3
Acoshm_deg(d92
acosh(x)mP
Acosm(qB
acos
hX3
Acosm_deg(d92
acos(x)mP
Asinhm(qB
asinh
hX3
Asinhm_deg(d92
asinh(x)mP
Asinm(qB
asin
hX3
Asinm_deg(d92
asin(x)mP
Atan2m
oA2::atan2(x,y
mP
Atan2m_deg(qH
oQ1
atan2(x,y)mP
Atanhm(qB
atanh
hX3
Atanm(qB
atan
hX3
Atanm_deg(d92
atan(x)mP
Cbrtm(qB
cbrt
hX3
Ceilm(qB
ceil
hX3
Coshm(qB
cosh
hX3
Coshm_deg(qB
cosh(oK1
Cosm(qB
cos
hX3
Cosm_deg(qB
cos(oK1
Exp2m(qB
exp2
hX3
Expm(qB
exp
hX3
Floorm(qB
floor
hX3
Hypotm
oA2::hypot(x,y
mP
If_d
hM
g31?y:z;}
q0
Int(qK
fp_floor(x+a21
mP
Log2m(qB
log2
hX3
Log10m(qB
log10
hX3
Logm(qB
log
hX3
Pow_negm
oA2::pow(-x*o62,y
mP
Pow_posm
oA2::pow(x,y
mP
Sinhm(qB
sinh
hX3
Sinhm_deg(qB
sinh(oK1
Sinm(qB
sin
hX3
Sinm_deg(qB
sin(oK1
Sqrtm(qB
sqrt
hX3
Tanhm(qB
tanh
hX3
Tanhm_deg(qB
tanh(oK1
Tanm(qB
tan
hX3
Tanm_deg(qB
tan(oK1
Truncm(qB
trunc(x);}
}
namespace
cpp_03unit_constants
wH2
E_mpfr(qB
exp(x
wP2
1)mP
L2_mpfr(qB
log(x
wP2
2)mP
L10_mpfr(qB
log(x
wP2
10)mP
Pi_mpfr(qB
atan2(x*q0(0),-q0(1));}
}
namespace
cpp_10optimizer_bytecode
wH2
Acoshm(qB
acosh(gQ
Acoshm_deg(d92
acosh(wZ
Acosm(qB
acos(w91
Acosm_deg(d92
acos(mflit0_7)hU
Asinhm(qB
asinh(gQ
Asinhm_deg(d92
asinh(wZ
Asinm(qB
asin(w91
Asinm_deg(d92
asin(mflit0_7)hU
Atan2m(qB
atan2(q0(dA2
hU
Atan2m_deg(d92
atan2(q0(dA2)hU
Atanhm(qB
atanh(w91
Atanm(qB
atan(gQ
Atanm_deg(d92
atan(wZ
Cbrtm(qB
cbrt(gQ
Ceilm(qB
ceil(gQ
Coshm(qB
cosh(gQ
Coshm_deg(qB
cosh(dB2
Cosm(qB
cos(gQ
Cosm_deg(qB
cos(dB2
Exp2m(qB
exp2(gQ
Expm(qB
exp(gQ
Floorm(qB
floor(gQ
Hypotm(qB
hypot(q0(dA2
hU
Int(qK
x+(((((fp_int(mflit1_1
oB1
mflit1_6)oB1
mflit1_5)oB1
mflitm1_1)oB1
mflitm1_6)oB1
mflitm1_5)mP
Log2m(qB
log2(gQ
Log10m(qB
log10(gQ
Logm(qB
log(gQ
Pow_negm(qB
pow(mflitm0_25,q0(4)hU
Pow_posm(qB
pow(mflit1_1,dC2
hU
Powhalf
a72
a21
mP
Powminushalf
a72-a21
mP
Sinhm(qB
sinh(gQ
Sinhm_deg(qB
sinh(dB2
Sinm(qB
sin(gQ
Sinm_deg(qB
sin(dB2
Sqrtm(qB
sqrt(gQ
Tanhm(qB
tanh(gQ
Tanhm_deg(qB
tanh(dB2
Tanm(qB
tan(gQ
Tanm_deg(qB
tan(dB2
Truncm(qK
q0(1)+x;}
}
namespace
cpp_20optimizer_optimizations
wH2
Cmpeq_pow_imm_negneg
gF1(gL2
Cmpeq_pow_imm_negpos
gF1(a82
Cmpeq_pow_imm_pospos_base
gF1(gN2
Cmpge_pow_imm_negneg(wM
gL2
Cmpge_pow_imm_negpos(wM
a82
Cmpge_pow_imm_pospos_base(wM
gN2
Cmpgt_pow_imm_negneg(mX
gL2
Cmpgt_pow_imm_negpos(mX
a82
Cmpgt_pow_imm_pospos_base(mX
gN2
Cmple_pow_imm_negneg
gW1
gL2
Cmple_pow_imm_negpos
gW1
a82
Cmple_pow_imm_pospos_base
gW1
gN2
Cmplt_pow_imm_negneg
oT1
gL2
Cmplt_pow_imm_negpos
oT1
a82
Cmplt_pow_imm_pospos_base
oT1
gN2
Cmpne_pow_imm_negneg(oU1
gL2
Cmpne_pow_imm_negpos(oU1
a82
Cmpne_pow_imm_pospos_base(oU1
gN2
Cmpzz_pow_imm_negneg(qH1
gJ
aN
gJ
m7
gJ
m8
gJ
mA
gJ
mN
gL2
Cmpzz_pow_imm_negpos(qH1
qP
gY
aN
qP
gY
m7
qP
gY
m8
qP
gY
mA
qP
gY
mN
a82
Cmpzz_pow_imm_pospos_base(qH1
gK
aN
gK
m7
gK
m8
gK
mA
gK
mN
gN2
Ifabsnot
hM
fp_truth(hW1)!=q0(0)?z:y;}
q0
Posnot(qB2
hW1
mP
Posnotnot(qK
fp_notNot(hW1
mP
Powmulimm_fnen(a5(q0(-8))mP
Powmulimm_fnep(a5(q0(4))mP
Powmulimm_fnfn(g12(mflitm5_1)*x,(mflitm7_1)mP
Powmulimm_fnfp(a5
dC2
mP
Powmulimm_fpfp(qH
a42
mflit5_1*x*y,dC2);}
}
namespace
cpp_50regressions
wH2
t42(qH
q22
x*x)+gG2(a42
y*y,o62))+fp_hypot(x,y);}
}
namespace
cpp_99misc
wH2
t2(qK
q0(2)*x+aD
x)/mflit_5+q0(2)-aD
x)*aD
x
mP
t3
hM
wY2
gG1,y),fp_equal(y,x
mY
1)+q0(2)-mflit3_1*mflit4e2/mflit_5+x*x+y*y+z*z+wY2
x,x)+fp_or(y,y
mP
t9
hM
mflit1_5+x*y-gE2
4)/q0(8)+z+z+z+z+x/(y*z
mP
t11
hM(-x-x)+y+hQ
a42
mflit1_1,z)mP
t22(qH(mflit3_5*q0(2
mY
10)*(x*q0(3))-(aD
y)*q0(2
mY
100)*((x*q0(2))-(y*q0(3)))*gE2
5)/(q0(2)*q0(2))+a42
mflit1_1,x*q0(2))+a42
mflit1_1*q0(2),x*q0(2)mP
t26_deg(qK
aD
d2r(x))+gX2
d2r(x*mflit1_5))+r2d(fp_asin(x/q0(110)))+r2d
wX2
x/q0(120))mP
t30(qH
x-y*q0(1)+fp_mod(x,y)+x/a42
y,mflit1_1)+qN
2),q0(3))+fp_mod(q0(5),q0(3))+qP
a42
y,q0(0)))+qP
a21
mP
t32
hM
x+y/y-m61
3),q0(4))-x-m71
4),q0(3))+m71
3),q0(4))-m61
4),q0(3
mY
0)+(z*oY3(x-gE2
2))+(x*a21*q0(2))+y*q0(0)+fp_min(fp_min(m61
4),gZ1
1))oZ2
x
oZ2
fp_min(y,q0(4)),z)))+w42
w42
m71
4),gZ1
1))wO1
w42
y,q0(4)),z)))+(fp_abs
gF2
fp_acos
gF2
fp_asin
gF2
fp_atan
gF2
wR2
mflit1_1)+gX2
q0(0))+hZ2
q0(0))+fp_floor(mflit1_1)+hQ
oY3
aD
q0(0))+fp_sinh(q0(0))+qZ2
oY3
fp_tanh
gF2
wU1
q0(1),q0(1)))+(x-(y-z))+(x+y)+(x*y)+w42
x
wO1
x
w02
x,x))))*-q0(1)+(z-z)+q0(1)/aD
x/wA1
gW2/wA1
qZ2
z/q0(5))+gP
q0(1)/qZ2
z/wA1
aD
y/wA1
mI/q0(5)))+hQ
q0(30)+x)*hQ
q0(40)+y)/hQ
q0(50)+z)+aD
x/mflit57_295779513082320877)+fp_asin(x/q0(10))*mflit57_295779513082320877+fp_floor(-x)+q0(1)/wR2
x)+w81
5)*mflit0_2)+(-x+-x+-x+-x+-x+-x
mP
t37(qK
q0(5)+mflit7_5*q0(8)/q0(3)-qN
2),q0(4))*q0(2)+fp_mod(q0(7),q0(2
mY
4
hU
t38
hM
fp_asinh(x)+gG2
fp_acosh(y+q0(3))+dD2*fp_atanh(z
mP
t39
hM
aD
x+qM1)-mI+aD
y*mflit1_5))+z*z*z*aD
z*z*z-x*x-y*y)-qM1*aD
x+qM1)+x*y*z+x*y*dD2+x*y*z*mI)+x*y*mI)+x*z*mI)+y*z*dD2+(x*y*z*mI)-x*y*z-y*mI)-x*z*y+x*y+x*z-mI)*x
mP
t44(qK
wE
wF
8
wB1
wE*x
wF
7
wC1
wE*x*x
wF
6))+mflit1_3*wE*x*x*x
wF
5))+mflit1_4*wE
mU
wF
6))+gG2
wE
mU*x
wF
4))+mflit1_6
oH2*x
wF
3))+mflit1_7
oH2*x*x
wF
2))+mflit1_8*(q22
a42
fp_abs(-q22
x)),q0(3)))mP
t45(qK
wE
wF
7
wB1
wE*x*x
wF
5
wC1
wE
mU
wF
3)mP
t46(qH
fp_abs(fp_floor
wX2
x)+q0(4)wB1
fp_abs(fp_floor
wX2
y)+mflit1_5))g62
fp_acos(x),wX2
y)-q0(10)wC1
m71-4),fp_acos(x))+mflit1_3*m61
9),fp_acos(x)-q0(9)mP
t47(qH
mflit1_25*(gH2+gI2)+gG2(fp_exp(y)-fp_exp(-y))+mflit1_75*((gI2+gH2)/q0(2
mY
2)*((gI2-gH2)/q0(2))+mflit2_25*(hZ2
y)+fp_sinh(y)mP
t48(qK
fp_sinh((hQ
x)/q0(5)+q0(1))*q0(5
wC1
hZ2(hQ
x)/hQ
q0(2
mY
1))*hQ
q0(2)))+fp_not(fp_or
aL
x),fp_not(x/q0(4)))mP
t49(qK
wU1
q0(0),x)+qN-4)*(x-q0(100)),mflit3_3
mP
t52(qK
x+(q0(1)+gE2
3)+q0(4)-q0(5)-q0(6)-q0(7)-q0(8))/q0(3)+q0(4)*(q0(1)+aD
q0(2))+gX2
q0(4)*q0(5)+q0(6))/q0(2))+gX2
a21)*qZ2
mflit0_6+mflit0_2)-mflit1_1/hQ
mflit2_1)*q22
mflit3_3)+qN
2),q0(3)mP
t55(qH
a22
qP
mflit1_2),q0(0))g62
a42
y,dD2),aA2
2)*m2*x,aA2
3)*a22
a42
y,q0(3)),aA2
4)*a22
qP
q0(4)),q0(0)mP
t56(qK
fp_mod(mflit1_75e21,x);}
}
template<>const
wI2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Modm,hA
qA",z"
,g7"modm"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1
mR
dP
Acoshm
qF"/acoshm"
,oB2
hC
1
mR,gL1
Acoshm_deg
qF"/acoshm_deg"
,oB2
qV1
dP
Acosm
qF"/acosm"
,"acos"
qV1,gL1
Acosm_deg
qF"/acosm_deg"
,"acos"
qV1
dP
Asinhm
qF"/asinhm"
,a92
qV1,gL1
Asinhm_deg
qF"/asin"
gU2
a92
qV1
dP
Asinm
qF"/asinm"
,"a"
wQ1}
,{oJ1,gL1
Asinm_deg
qF"/asin"
dE2"a"
wQ1}
,{2,-4,4,N(0.15)dP
Atan2m,d82"/atan2m"
,hT2"(x"
gT2
2,-4,4,N(0.15),gL1
Atan2m_deg,d82"/atan2m_deg"
,hT2"(x"
gT2
oJ1
dP
Atanhm
qF"/atanhm"
,"atanh"
hC
a12
dP
Atanm
qF"/atanm"
,"atan"
hC
a12,gL1
Atanm_deg
qF"/atanm_deg"
,"atan"
hC-50000,50000,1000
dP
Cbrtm
qF"/cbrtm"
,"cbrt"
hC-10,10
mR1
dP
Ceilm
qF"/ceilm"
,"ceil"
hC-140,140,N(0.1)dP
Coshm
qF"/coshm"
,"cosh"
hC-140,140,N(0.1),gL1
Coshm_deg
qF"/coshm_deg"
,"cosh"
hC-m4
dP
Cosm
qF"/cosm"
,"cos"
hC-m4,gL1
Cosm_deg
qF"/cosm_deg"
,"cos"
hC-90,90,N(0.02)dP
Exp2m
qF"/exp2m"
,"exp2"
hC-90,90,N(0.02)dP
Expm
qF"/expm"
,"exp"
hC-10,10
mR1
dP
Floorm
qF"/floorm"
,"floor(x)"
gM1
dP
Hypotm,d82"/hypotm"
,"hypot(x,y"
gO2
Tn
Un{1,oO1
Log2m
qF"/log2m"
,"log2"
hC
oO1
Log10m
qF"/log10m"
,"log10"
hC
oO1
Logm
qF"/logm"
,aH1
T4
U4{2,1,20,1
dP
Pow_negm,d82"/pow_negm"
,"pow(-x*0.25,y"
gO2{2,N(0.01),4,N(0.05)dP
Pow_posm,d82"/pow_posm"
,qH2
gT2
1,a12
dP
Sinhm
qF"/sinhm"
,gK2
hC
a12,gL1
Sinhm_deg
qF"/sin"
gU2
gK2
hC-m4
dP
Sinm
qF"/sinm"
,wQ1}
,{1,-m4,gL1
Sinm_deg
qF"/sin"
dE2
wQ1}
,{1,0,100000,1000
dP
Sqrtm
qF"/sqrtm"
,"sqrt"
hC-m4
dP
Tanhm
qF"/tanhm"
,"tanh"
hC-m4,gL1
Tanhm_deg
qF"/tanhm_deg"
,"tanh"
hC
N(-1.3),N(1.3),N(0.05)dP
Tanm
qF"/tanm"
,"tan"
hC-89,89
mR1,gL1
Tanm_deg
qF"/tanm_deg"
,"tan"
hC
a12
dP
Truncm
qF"/truncm"
,"trunc"
hC
0,dD
E_mpfr,oQ"e_mpfr"
,dW3"naturalnumber"
}
,a52
L2_mpfr,oQ"l2_mpfr"
,dW3"logtwo"
}
,a52
L10_mpfr,oQ"l10_mpfr"
,dW3"logten"
}
,a52
Pi_mpfr,oQ"pi_mpfr"
,dW3"pi"
}
,W4
Wn
Y4
Yn
So
To
S5
W5
Uo
a62
Acoshm
aK"acoshm"
,oB2"("
oH
Acoshm_deg
aK"acoshm_deg"
,oB2
w82
Wo
a62
Acosm
aK"acosm"
,"acos"
w72,d62
Acosm_deg
aK"acosm_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp
a62
Asinhm
aK"asinhm"
,a92"("
oH
Asinhm_deg
aK"asin"
gU2
a92
w82
Up
a62
Asinm
aK"asinm"
,"asin("
aZ1,d62
Asinm_deg
aK"asin"
dE2"asin("
aZ1
qL
Atan2m
aK"atan2m"
,hT2"(5,4"
gG,d62
Atan2m_deg
aK"atan2m_deg"
,hT2"(5,4)+x"
}
,Wp
a62
Atanhm
aK"atanhm"
,"atanh"
w72
qL
Atanm
aK"atanm"
,"atan("
oH
Atanm_deg
aK"atanm_deg"
,"atan"
aO
Cbrtm
aK"cbrtm"
,"cbrt"
aO
Ceilm
aK"ceilm"
,"ceil"
w82
Yp
a62
Coshm
aK"coshm"
,"cosh("
oH
Coshm_deg
aK"coshm_deg"
,"cosh"
aO
Cosm
aK"cosm"
,"cos("
oH
Cosm_deg
aK"cosm_deg"
,"cos"
w82
Sq
Tq
Y5
Uq
Wq
Yq
W6
Sr
Tr
Ur
a62
Exp2m
aK"exp2m"
,"exp2"
w82
Wr
Yr
Ss
Ts
a62
Expm
aK"expm"
,"exp"
aO
Floorm
aK"floorm"
,"floor"
w82
Us
a62
Hypotm
aK"hypotm"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
a62
Log2m
aK"log2m"
,"log2"
aO
Log10m
aK"log10m"
,"log10"
aO
Logm
aK"logm"
,"log"
w82
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
a62
Pow_negm,qG"/pow_negm"
,"pow(-0.25,4"
gG
qL
Pow_posm,qG"/pow_posm"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
a62
Sinhm
a11"hm"
,gK2"("
oH
Sinhm_deg
a11
gU2
gK2
aO
Sinm
a11"m"
,"sin("
oH
Sinm_deg
a11
dE2"sin("
w5
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww
a62
Sqrtm
aK"sqrtm"
,"sqrt"
aO
Tanhm
aK"tanhm"
,"tanh("
oH
Tanhm_deg
aK"tanhm_deg"
,"tanh"
aO
Tanm
aK"tanm"
,"tan("
oH
Tanm_deg
aK"tanm_deg"
,"tan"
aO
Truncm
aK"truncm"
,"trunc"
w82
Yw
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
T61
U61
W61
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Tf
Uf
Wf
Yf
UE1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wI2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_MPFR_FLOAT_TYPE */
